# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: audience/v1/audience.proto for package 'rover.audience.v1'

require 'grpc'
require 'audience/v1/audience_pb'

module Rover
  module Audience
    module V1
      module Audience
        # Audience service is responsible for managing profiles & devices as well as static & dynamic segments.
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'rover.audience.v1.Audience'

          #
          # Profiles
          #
          #
          # CreateProfile creates a new empty profile under a given account.
          rpc :CreateProfile, CreateProfileRequest, Profile
          #  DeleteProfile deletes a profile from db and all segments
          rpc :DeleteProfile, DeleteProfileRequest, Profile
          # UpdateProfile updates profile with provided subset of attributes
          rpc :UpdateProfile, UpdateProfileRequest, Profile
          # GetProfileByDeviceId returns a profile which is associated to the device id
          rpc :GetProfileByDeviceId, GetProfileByDeviceIdRequest, Profile
          # GetProfileSchema returns the currently tracked profiles schema by account id
          rpc :GetProfileSchema, GetProfileSchemaRequest, ProfileSchema
          #
          # Devices
          #
          #
          # CreateDevice creates a an "empty" device under a given account.
          rpc :CreateDevice, CreateDeviceRequest, Device
          # DeleteDevice deletes device from the database and removes it from any segments
          rpc :DeleteDevice, DeleteDeviceRequest, Device
          # PutDevice updates the device
          rpc :PutDevice, PutDeviceRequest, Device
          # SetDevicePushToken
          rpc :SetDevicePushToken, SetDevicePushTokenRequest, Google::Protobuf::Empty
          # PutDevice updates the device
          rpc :SetDeviceProfile, SetDeviceProfileRequest, Device
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
