test:
    adapter: postgresql
    encoding: unicode
    database: rover-test
    pool: 5
    username: rover_test
    password: password1
    host: <%= ENV['POSTGRESQL_DB_HOST'] || "localhost" %>

development:
    adapter: postgresql
    encoding: unicode
    database: rover-local
    pool: 5
    username: rover_development
    password: password1
    host: <%= ENV['POSTGRESQL_DB_HOST'] || "localhost" %>

production:
    adapter: postgresql
    encoding: unicode
    database: rover
    pool: 5
    username: <%=ENV['POSTGRESQL_DB_USERNAME']%>
    password: <%=ENV['POSTGRESQL_DB_PASSWORD']%>
    host: <%=ENV['POSTGRESQL_DB_HOST']%>
    port: <%=ENV['POSTGRESQL_DB_PORT']%>
