test:
    urls: <%= ENV['ELASTICSEARCH_URLS'] || "127.0.0.1:9200" %>
development:
    urls: <%= ENV['ELASTICSEARCH_URLS'] || "127.0.0.1:9200" %>
production:
    urls: <%= ENV['ELASTICSEARCH_URLS'] %>
    max_shards_per_index: <%= ENV['ELASTICSEARCH_MAX_SHARDS_PER_INDEX'] %>
