production:
    uri: <%= ENV["MONGODB_URI"] %>
    ssl: true
    ssl_cert_string: <%= ENV["MONGODB_SSL_CERT"] %>

development:
    uri: <%= ENV.fetch("MONGODB_URI", "mongodb://localhost:27017/rover-local") %>
    ssl: false
    monitoring: true

test:
    uri: <%= ENV.fetch("MONGODB_URI", "mongodb://localhost:27017/rover-test") %>
    ssl: false
    monitoring: true
