version: "3"

services:
  bulk-gateway:
    links: [auth-service]
    image: node:7.10.1
    volumes:
      - ../../rover:/rover/
    working_dir: /rover/bulk-gateway
    environment:
      AUTH_V1_SERVICE_HOST: auth-service
      NODE_ENV: development
