#!/bin/sh


run() {
  go run ./transformer/service/cmd/service/main.go
}

test() {
	go test github.com/roverplatform/rover/transformer/...
}

integration_test() {
	# Wait for kafka to be up and running
	while :
    do
        nc -z kafka 9092
		result=$?
		if [[ $result -eq 0 ]]; then
			break
		fi
        sleep 1
    done

    go test -tags integration github.com/roverplatform/rover/transformer/...
}


for cmd in $*; do
  $cmd
done