/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var auth_v1_auth_pb = require('../../auth/v1/auth_pb.js');
var protobuf_version_pb = require('../../protobuf/version_pb.js');
goog.exportSymbol('proto.rover.notification.v1.NotificationAttachmentType', null, global);
goog.exportSymbol('proto.rover.notification.v1.NotificationAttachmentType.Enum', null, global);
goog.exportSymbol('proto.rover.notification.v1.NotificationTapBehaviorType', null, global);
goog.exportSymbol('proto.rover.notification.v1.NotificationTapBehaviorType.Enum', null, global);
goog.exportSymbol('proto.rover.notification.v1.NotificationTapPresentationType', null, global);
goog.exportSymbol('proto.rover.notification.v1.NotificationTapPresentationType.Enum', null, global);
goog.exportSymbol('proto.rover.notification.v1.PushEnvironment', null, global);
goog.exportSymbol('proto.rover.notification.v1.PushEnvironment.Enum', null, global);
goog.exportSymbol('proto.rover.notification.v1.SendCampaignNotificationRequest', null, global);
goog.exportSymbol('proto.rover.notification.v1.SendCampaignNotificationRequest.Message', null, global);
goog.exportSymbol('proto.rover.notification.v1.SendCampaignNotificationResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.PushEnvironment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.notification.v1.PushEnvironment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.PushEnvironment.displayName = 'proto.rover.notification.v1.PushEnvironment';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.PushEnvironment.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.PushEnvironment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.PushEnvironment} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.PushEnvironment.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.PushEnvironment}
 */
proto.rover.notification.v1.PushEnvironment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.PushEnvironment;
  return proto.rover.notification.v1.PushEnvironment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.PushEnvironment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.PushEnvironment}
 */
proto.rover.notification.v1.PushEnvironment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.PushEnvironment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.PushEnvironment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.PushEnvironment} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.PushEnvironment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.rover.notification.v1.PushEnvironment.Enum = {
  UNKNOWN: 0,
  PRODUCTION: 1,
  DEVELOPMENT: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.NotificationTapBehaviorType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.notification.v1.NotificationTapBehaviorType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.NotificationTapBehaviorType.displayName = 'proto.rover.notification.v1.NotificationTapBehaviorType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.NotificationTapBehaviorType.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.NotificationTapBehaviorType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.NotificationTapBehaviorType} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.NotificationTapBehaviorType.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.NotificationTapBehaviorType}
 */
proto.rover.notification.v1.NotificationTapBehaviorType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.NotificationTapBehaviorType;
  return proto.rover.notification.v1.NotificationTapBehaviorType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.NotificationTapBehaviorType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.NotificationTapBehaviorType}
 */
proto.rover.notification.v1.NotificationTapBehaviorType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.NotificationTapBehaviorType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.NotificationTapBehaviorType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.NotificationTapBehaviorType} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.NotificationTapBehaviorType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.rover.notification.v1.NotificationTapBehaviorType.Enum = {
  OPEN_EXPERIENCE: 0,
  OPEN_APP: 1,
  OPEN_DEEP_LINK: 2,
  OPEN_WEBSITE: 3
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.NotificationTapPresentationType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.notification.v1.NotificationTapPresentationType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.NotificationTapPresentationType.displayName = 'proto.rover.notification.v1.NotificationTapPresentationType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.NotificationTapPresentationType.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.NotificationTapPresentationType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.NotificationTapPresentationType} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.NotificationTapPresentationType.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.NotificationTapPresentationType}
 */
proto.rover.notification.v1.NotificationTapPresentationType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.NotificationTapPresentationType;
  return proto.rover.notification.v1.NotificationTapPresentationType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.NotificationTapPresentationType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.NotificationTapPresentationType}
 */
proto.rover.notification.v1.NotificationTapPresentationType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.NotificationTapPresentationType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.NotificationTapPresentationType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.NotificationTapPresentationType} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.NotificationTapPresentationType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.rover.notification.v1.NotificationTapPresentationType.Enum = {
  UNKNOWN: 0,
  IN_APP: 1,
  IN_BROWSER: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.NotificationAttachmentType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.notification.v1.NotificationAttachmentType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.NotificationAttachmentType.displayName = 'proto.rover.notification.v1.NotificationAttachmentType';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.NotificationAttachmentType.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.NotificationAttachmentType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.NotificationAttachmentType} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.NotificationAttachmentType.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.NotificationAttachmentType}
 */
proto.rover.notification.v1.NotificationAttachmentType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.NotificationAttachmentType;
  return proto.rover.notification.v1.NotificationAttachmentType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.NotificationAttachmentType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.NotificationAttachmentType}
 */
proto.rover.notification.v1.NotificationAttachmentType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.NotificationAttachmentType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.NotificationAttachmentType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.NotificationAttachmentType} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.NotificationAttachmentType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.rover.notification.v1.NotificationAttachmentType.Enum = {
  UNKNOWN: 0,
  IMAGE: 1,
  AUDIO: 2,
  VIDEO: 3
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.SendCampaignNotificationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rover.notification.v1.SendCampaignNotificationRequest.repeatedFields_, null);
};
goog.inherits(proto.rover.notification.v1.SendCampaignNotificationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.SendCampaignNotificationRequest.displayName = 'proto.rover.notification.v1.SendCampaignNotificationRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.repeatedFields_ = [30];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.SendCampaignNotificationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    authContext: (f = msg.getAuthContext()) && auth_v1_auth_pb.AuthContext.toObject(includeInstance, f),
    campaignId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    experienceId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    notificationAttachmentUrl: jspb.Message.getFieldWithDefault(msg, 10, ""),
    notificationAttachmentType: jspb.Message.getFieldWithDefault(msg, 11, 0),
    notificationTapBehaviorType: jspb.Message.getFieldWithDefault(msg, 12, 0),
    notificationTapBehaviorPresentationType: jspb.Message.getFieldWithDefault(msg, 13, 0),
    notificationTapBehaviorUrl: jspb.Message.getFieldWithDefault(msg, 14, ""),
    notificationIosContentAvailable: jspb.Message.getFieldWithDefault(msg, 15, false),
    notificationIosMutableContent: jspb.Message.getFieldWithDefault(msg, 16, false),
    notificationIosSound: jspb.Message.getFieldWithDefault(msg, 17, ""),
    notificationIosCategoryIdentifier: jspb.Message.getFieldWithDefault(msg, 18, ""),
    notificationIosThreadIdentifier: jspb.Message.getFieldWithDefault(msg, 19, ""),
    notificationAndroidChannelId: jspb.Message.getFieldWithDefault(msg, 20, ""),
    notificationAndroidSound: jspb.Message.getFieldWithDefault(msg, 21, ""),
    notificationAndroidTag: jspb.Message.getFieldWithDefault(msg, 22, ""),
    notificationExpiration: jspb.Message.getFieldWithDefault(msg, 23, 0),
    notificationAttributesMap: (f = msg.getNotificationAttributesMap()) ? f.toObject(includeInstance, undefined) : [],
    notificationAlertOptionPushNotification: jspb.Message.getFieldWithDefault(msg, 25, false),
    notificationAlertOptionNotificationCenter: jspb.Message.getFieldWithDefault(msg, 26, false),
    notificationAlertOptionBadgeNumber: jspb.Message.getFieldWithDefault(msg, 27, false),
    messagesList: jspb.Message.toObjectList(msg.getMessagesList(),
    proto.rover.notification.v1.SendCampaignNotificationRequest.Message.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.SendCampaignNotificationRequest}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.SendCampaignNotificationRequest;
  return proto.rover.notification.v1.SendCampaignNotificationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.SendCampaignNotificationRequest}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new auth_v1_auth_pb.AuthContext;
      reader.readMessage(value,auth_v1_auth_pb.AuthContext.deserializeBinaryFromReader);
      msg.setAuthContext(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCampaignId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setExperienceId(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationAttachmentUrl(value);
      break;
    case 11:
      var value = /** @type {!proto.rover.notification.v1.NotificationAttachmentType.Enum} */ (reader.readEnum());
      msg.setNotificationAttachmentType(value);
      break;
    case 12:
      var value = /** @type {!proto.rover.notification.v1.NotificationTapBehaviorType.Enum} */ (reader.readEnum());
      msg.setNotificationTapBehaviorType(value);
      break;
    case 13:
      var value = /** @type {!proto.rover.notification.v1.NotificationTapPresentationType.Enum} */ (reader.readEnum());
      msg.setNotificationTapBehaviorPresentationType(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationTapBehaviorUrl(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotificationIosContentAvailable(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotificationIosMutableContent(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationIosSound(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationIosCategoryIdentifier(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationIosThreadIdentifier(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationAndroidChannelId(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationAndroidSound(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationAndroidTag(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNotificationExpiration(value);
      break;
    case 24:
      var value = msg.getNotificationAttributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 25:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotificationAlertOptionPushNotification(value);
      break;
    case 26:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotificationAlertOptionNotificationCenter(value);
      break;
    case 27:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setNotificationAlertOptionBadgeNumber(value);
      break;
    case 30:
      var value = new proto.rover.notification.v1.SendCampaignNotificationRequest.Message;
      reader.readMessage(value,proto.rover.notification.v1.SendCampaignNotificationRequest.Message.deserializeBinaryFromReader);
      msg.addMessages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.SendCampaignNotificationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      auth_v1_auth_pb.AuthContext.serializeBinaryToWriter
    );
  }
  f = message.getCampaignId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getExperienceId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNotificationAttachmentUrl();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getNotificationAttachmentType();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getNotificationTapBehaviorType();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getNotificationTapBehaviorPresentationType();
  if (f !== 0.0) {
    writer.writeEnum(
      13,
      f
    );
  }
  f = message.getNotificationTapBehaviorUrl();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getNotificationIosContentAvailable();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getNotificationIosMutableContent();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getNotificationIosSound();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getNotificationIosCategoryIdentifier();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getNotificationIosThreadIdentifier();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getNotificationAndroidChannelId();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getNotificationAndroidSound();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getNotificationAndroidTag();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getNotificationExpiration();
  if (f !== 0) {
    writer.writeInt32(
      23,
      f
    );
  }
  f = message.getNotificationAttributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(24, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getNotificationAlertOptionPushNotification();
  if (f) {
    writer.writeBool(
      25,
      f
    );
  }
  f = message.getNotificationAlertOptionNotificationCenter();
  if (f) {
    writer.writeBool(
      26,
      f
    );
  }
  f = message.getNotificationAlertOptionBadgeNumber();
  if (f) {
    writer.writeBool(
      27,
      f
    );
  }
  f = message.getMessagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      30,
      f,
      proto.rover.notification.v1.SendCampaignNotificationRequest.Message.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.notification.v1.SendCampaignNotificationRequest.Message, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.SendCampaignNotificationRequest.Message.displayName = 'proto.rover.notification.v1.SendCampaignNotificationRequest.Message';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.SendCampaignNotificationRequest.Message.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.toObject = function(includeInstance, msg) {
  var f, obj = {
    notificationBody: jspb.Message.getFieldWithDefault(msg, 1, ""),
    notificationTitle: jspb.Message.getFieldWithDefault(msg, 2, ""),
    deviceId: jspb.Message.getFieldWithDefault(msg, 10, ""),
    devicePushToken: jspb.Message.getFieldWithDefault(msg, 11, ""),
    devicePushTokenEnvironment: jspb.Message.getFieldWithDefault(msg, 12, 0),
    deviceAppNamespace: jspb.Message.getFieldWithDefault(msg, 13, ""),
    deviceBadgeCount: jspb.Message.getFieldWithDefault(msg, 14, 0),
    osName: jspb.Message.getFieldWithDefault(msg, 15, ""),
    sdkVersion: (f = msg.getSdkVersion()) && protobuf_version_pb.Version.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.SendCampaignNotificationRequest.Message;
  return proto.rover.notification.v1.SendCampaignNotificationRequest.Message.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationBody(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationTitle(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceId(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicePushToken(value);
      break;
    case 12:
      var value = /** @type {!proto.rover.notification.v1.PushEnvironment.Enum} */ (reader.readEnum());
      msg.setDevicePushTokenEnvironment(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceAppNamespace(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDeviceBadgeCount(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsName(value);
      break;
    case 16:
      var value = new protobuf_version_pb.Version;
      reader.readMessage(value,protobuf_version_pb.Version.deserializeBinaryFromReader);
      msg.setSdkVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.SendCampaignNotificationRequest.Message.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNotificationBody();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNotificationTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDeviceId();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getDevicePushToken();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getDevicePushTokenEnvironment();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getDeviceAppNamespace();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getDeviceBadgeCount();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getOsName();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getSdkVersion();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      protobuf_version_pb.Version.serializeBinaryToWriter
    );
  }
};


/**
 * optional string notification_body = 1;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getNotificationBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setNotificationBody = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string notification_title = 2;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getNotificationTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setNotificationTitle = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string device_id = 10;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getDeviceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setDeviceId = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional string device_push_token = 11;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getDevicePushToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setDevicePushToken = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional PushEnvironment.Enum device_push_token_environment = 12;
 * @return {!proto.rover.notification.v1.PushEnvironment.Enum}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getDevicePushTokenEnvironment = function() {
  return /** @type {!proto.rover.notification.v1.PushEnvironment.Enum} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {!proto.rover.notification.v1.PushEnvironment.Enum} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setDevicePushTokenEnvironment = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional string device_app_namespace = 13;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getDeviceAppNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setDeviceAppNamespace = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional int32 device_badge_count = 14;
 * @return {number}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getDeviceBadgeCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/** @param {number} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setDeviceBadgeCount = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional string os_name = 15;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getOsName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setOsName = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional rover.protobuf.Version sdk_version = 16;
 * @return {?proto.rover.protobuf.Version}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.getSdkVersion = function() {
  return /** @type{?proto.rover.protobuf.Version} */ (
    jspb.Message.getWrapperField(this, protobuf_version_pb.Version, 16));
};


/** @param {?proto.rover.protobuf.Version|undefined} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.setSdkVersion = function(value) {
  jspb.Message.setWrapperField(this, 16, value);
};


proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.clearSdkVersion = function() {
  this.setSdkVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.Message.prototype.hasSdkVersion = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional rover.auth.v1.AuthContext auth_context = 1;
 * @return {?proto.rover.auth.v1.AuthContext}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getAuthContext = function() {
  return /** @type{?proto.rover.auth.v1.AuthContext} */ (
    jspb.Message.getWrapperField(this, auth_v1_auth_pb.AuthContext, 1));
};


/** @param {?proto.rover.auth.v1.AuthContext|undefined} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setAuthContext = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.clearAuthContext = function() {
  this.setAuthContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.hasAuthContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 campaign_id = 2;
 * @return {number}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getCampaignId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setCampaignId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string experience_id = 3;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getExperienceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setExperienceId = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string notification_attachment_url = 10;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAttachmentUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAttachmentUrl = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional NotificationAttachmentType.Enum notification_attachment_type = 11;
 * @return {!proto.rover.notification.v1.NotificationAttachmentType.Enum}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAttachmentType = function() {
  return /** @type {!proto.rover.notification.v1.NotificationAttachmentType.Enum} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {!proto.rover.notification.v1.NotificationAttachmentType.Enum} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAttachmentType = function(value) {
  jspb.Message.setField(this, 11, value);
};


/**
 * optional NotificationTapBehaviorType.Enum notification_tap_behavior_type = 12;
 * @return {!proto.rover.notification.v1.NotificationTapBehaviorType.Enum}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationTapBehaviorType = function() {
  return /** @type {!proto.rover.notification.v1.NotificationTapBehaviorType.Enum} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {!proto.rover.notification.v1.NotificationTapBehaviorType.Enum} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationTapBehaviorType = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional NotificationTapPresentationType.Enum notification_tap_behavior_presentation_type = 13;
 * @return {!proto.rover.notification.v1.NotificationTapPresentationType.Enum}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationTapBehaviorPresentationType = function() {
  return /** @type {!proto.rover.notification.v1.NotificationTapPresentationType.Enum} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {!proto.rover.notification.v1.NotificationTapPresentationType.Enum} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationTapBehaviorPresentationType = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional string notification_tap_behavior_url = 14;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationTapBehaviorUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationTapBehaviorUrl = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional bool notification_ios_content_available = 15;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationIosContentAvailable = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 15, false));
};


/** @param {boolean} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationIosContentAvailable = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional bool notification_ios_mutable_content = 16;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationIosMutableContent = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 16, false));
};


/** @param {boolean} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationIosMutableContent = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * optional string notification_ios_sound = 17;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationIosSound = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationIosSound = function(value) {
  jspb.Message.setField(this, 17, value);
};


/**
 * optional string notification_ios_category_identifier = 18;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationIosCategoryIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationIosCategoryIdentifier = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * optional string notification_ios_thread_identifier = 19;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationIosThreadIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationIosThreadIdentifier = function(value) {
  jspb.Message.setField(this, 19, value);
};


/**
 * optional string notification_android_channel_id = 20;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAndroidChannelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAndroidChannelId = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * optional string notification_android_sound = 21;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAndroidSound = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAndroidSound = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * optional string notification_android_tag = 22;
 * @return {string}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAndroidTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/** @param {string} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAndroidTag = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * optional int32 notification_expiration = 23;
 * @return {number}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationExpiration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/** @param {number} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationExpiration = function(value) {
  jspb.Message.setField(this, 23, value);
};


/**
 * map<string, string> notification_attributes = 24;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAttributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 24, opt_noLazyCreate,
      null));
};


proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.clearNotificationAttributesMap = function() {
  this.getNotificationAttributesMap().clear();
};


/**
 * optional bool notification_alert_option_push_notification = 25;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAlertOptionPushNotification = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 25, false));
};


/** @param {boolean} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAlertOptionPushNotification = function(value) {
  jspb.Message.setField(this, 25, value);
};


/**
 * optional bool notification_alert_option_notification_center = 26;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAlertOptionNotificationCenter = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 26, false));
};


/** @param {boolean} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAlertOptionNotificationCenter = function(value) {
  jspb.Message.setField(this, 26, value);
};


/**
 * optional bool notification_alert_option_badge_number = 27;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getNotificationAlertOptionBadgeNumber = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 27, false));
};


/** @param {boolean} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setNotificationAlertOptionBadgeNumber = function(value) {
  jspb.Message.setField(this, 27, value);
};


/**
 * repeated Message messages = 30;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.rover.notification.v1.SendCampaignNotificationRequest.Message>}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.getMessagesList = function() {
  return /** @type{!Array.<!proto.rover.notification.v1.SendCampaignNotificationRequest.Message>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rover.notification.v1.SendCampaignNotificationRequest.Message, 30));
};


/** @param {!Array.<!proto.rover.notification.v1.SendCampaignNotificationRequest.Message>} value */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.setMessagesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 30, value);
};


/**
 * @param {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rover.notification.v1.SendCampaignNotificationRequest.Message}
 */
proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.addMessages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 30, opt_value, proto.rover.notification.v1.SendCampaignNotificationRequest.Message, opt_index);
};


proto.rover.notification.v1.SendCampaignNotificationRequest.prototype.clearMessagesList = function() {
  this.setMessagesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.notification.v1.SendCampaignNotificationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.notification.v1.SendCampaignNotificationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.notification.v1.SendCampaignNotificationResponse.displayName = 'proto.rover.notification.v1.SendCampaignNotificationResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.notification.v1.SendCampaignNotificationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.notification.v1.SendCampaignNotificationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.notification.v1.SendCampaignNotificationResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.notification.v1.SendCampaignNotificationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.notification.v1.SendCampaignNotificationResponse}
 */
proto.rover.notification.v1.SendCampaignNotificationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.notification.v1.SendCampaignNotificationResponse;
  return proto.rover.notification.v1.SendCampaignNotificationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.notification.v1.SendCampaignNotificationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.notification.v1.SendCampaignNotificationResponse}
 */
proto.rover.notification.v1.SendCampaignNotificationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.notification.v1.SendCampaignNotificationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.notification.v1.SendCampaignNotificationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.notification.v1.SendCampaignNotificationResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.notification.v1.SendCampaignNotificationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.rover.notification.v1);
