# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/v1/auth.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rover.auth.v1.Token" do
    optional :account_id, :int32, 1
    optional :key, :string, 2
    repeated :permission_scopes, :string, 3
    optional :updated_at, :message, 6, "google.protobuf.Timestamp"
    optional :created_at, :message, 7, "google.protobuf.Timestamp"
  end
  add_message "rover.auth.v1.Account" do
    optional :id, :int32, 1
    optional :name, :string, 2
    optional :updated_at, :message, 3, "google.protobuf.Timestamp"
    optional :created_at, :message, 4, "google.protobuf.Timestamp"
  end
  add_message "rover.auth.v1.User" do
    optional :id, :int32, 1
    optional :account_id, :int32, 2
    optional :name, :string, 3
    optional :email, :string, 4
    repeated :permission_scopes, :string, 6
    optional :updated_at, :message, 7, "google.protobuf.Timestamp"
    optional :created_at, :message, 8, "google.protobuf.Timestamp"
  end
  add_message "rover.auth.v1.UserSession" do
    optional :user_id, :int32, 2
    optional :key, :string, 3
    optional :last_seen_IP, :string, 4
    optional :expires_at, :message, 5, "google.protobuf.Timestamp"
    optional :created_at, :message, 6, "google.protobuf.Timestamp"
    optional :updated_at, :message, 7, "google.protobuf.Timestamp"
  end
  add_message "rover.auth.v1.GetAccountRequest" do
    optional :account_id, :int32, 1
  end
  add_message "rover.auth.v1.CreateAccountRequest" do
    optional :name, :string, 1
  end
  add_message "rover.auth.v1.UpdateAccountRequest" do
    optional :account_id, :int32, 1
    optional :name, :string, 2
  end
  add_message "rover.auth.v1.GetUserRequest" do
    optional :account_id, :int32, 1
    optional :user_id, :int32, 2
  end
  add_message "rover.auth.v1.CreateUserRequest" do
    optional :account_id, :int32, 1
    optional :name, :string, 2
    optional :email, :string, 3
    optional :password, :string, 4
  end
  add_message "rover.auth.v1.UpdateUserRequest" do
    optional :account_id, :int32, 1
    optional :user_id, :int32, 2
    optional :name, :string, 3
    optional :email, :string, 4
    optional :password, :string, 5
  end
  add_message "rover.auth.v1.CreateUserSessionRequest" do
    optional :email, :string, 1
    optional :password, :string, 2
    optional :last_seen_IP, :string, 3
  end
  add_message "rover.auth.v1.AuthenticateRequest" do
    optional :key, :string, 1
    optional :last_seen_IP, :string, 2
  end
  add_message "rover.auth.v1.AuthContext" do
    optional :account_id, :int32, 1
    optional :user_id, :int32, 2
    repeated :permission_scopes, :string, 3
  end
end

module Rover
  module Auth
    module V1
      Token = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.Token").msgclass
      Account = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.Account").msgclass
      User = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.User").msgclass
      UserSession = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.UserSession").msgclass
      GetAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.GetAccountRequest").msgclass
      CreateAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.CreateAccountRequest").msgclass
      UpdateAccountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.UpdateAccountRequest").msgclass
      GetUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.GetUserRequest").msgclass
      CreateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.CreateUserRequest").msgclass
      UpdateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.UpdateUserRequest").msgclass
      CreateUserSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.CreateUserSessionRequest").msgclass
      AuthenticateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.AuthenticateRequest").msgclass
      AuthContext = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.auth.v1.AuthContext").msgclass
    end
  end
end
