#!/bin/sh

set -e
# set -x


SVC_HOME=./campaigns

run() {
	go run $SVC_HOME/cmd/campaigns-service/main.go
}

test() {
  go test $SVC_HOME/...
}

migrate() {
  go run ./go/postgres-cli/main.go \
    --migration-path=$SVC_HOME/db/migrations
}

for cmd in $@; do
  $cmd
done
