steps:
- name: 'gcr.io/cloud-builders/go:alpine'
  env:
    - PROJECT_ROOT=github.com/roverplatform/rover
  args:
    - install
    - github.com/roverplatform/rover/audience/service/cmd/audience-service
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - --tag=gcr.io/$PROJECT_ID/audience-service:$REVISION_ID
    - -f=./docker/audience-service/Dockerfile
    - .
images: ['gcr.io/$PROJECT_ID/audience-service:$REVISION_ID']
