#!/bin/sh

set -e

run() {
  go run ./audience/service/cmd/audience-service/main.go
}

test() {
  go test -tags integration \
    github.com/roverplatform/rover/audience/service/...
}

bench() {
  go test -tags integration -bench . -run NONE -benchtime 10s \
    ./audience/service/...
}


for cmd in $*; do
  $cmd
done
