#!/bin/sh

set -e

run() {
	go run ./audience/service/cmd/audience-serivce/main.go
}

test() {
  go test -tags integration \
    github.com/roverplatform/rover/audience/service/...
}

bench() {
  go test -tags integration -bench . -run NONE -benchtime 10s \
    ./audience/service/... \
    -service.DSN=${DB_DSN}
}


for cmd in $*; do
  $cmd
done
