# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: campaigns/v1/campaigns.proto for package 'rover.campaigns.v1'

require 'grpc'
require 'campaigns/v1/campaigns_pb'

module Rover
  module Campaigns
    module V1
      module Campaigns
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'rover.campaigns.v1.Campaigns'

          #
          # CRUD
          #
          rpc :List, ListRequest, ListResponse
          rpc :Get, GetRequest, GetResponse
          rpc :Create, CreateRequest, CreateResponse
          rpc :Duplicate, DuplicateRequest, DuplicateResponse
          rpc :Rename, RenameRequest, RenameResponse
          rpc :Publish, PublishRequest, PublishResponse
          rpc :Unpublish, UnpublishRequest, UnpublishResponse
          rpc :Archive, ArchiveRequest, ArchiveResponse
          rpc :Unarchive, UnarchiveRequest, UnarchiveResponse
          rpc :SendTest, SendTestRequest, SendTestResponse
          rpc :UpdateNotificationSettings, UpdateNotificationSettingsRequest, UpdateNotificationSettingsResponse
          rpc :UpdateScheduledDeliverySettings, UpdateScheduledDeliverySettingsRequest, UpdateScheduledDeliverySettingsResponse
          rpc :UpdateAutomatedDeliverySettings, UpdateAutomatedDeliverySettingsRequest, UpdateAutomatedDeliverySettingsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
