# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/struct.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rover.protobuf.Struct" do
    map :fields, :string, :message, 1, "rover.protobuf.Value"
  end
  add_message "rover.protobuf.Value" do
    oneof :kind do
      optional :null_value, :enum, 1, "rover.protobuf.NullValue"
      optional :number_value, :int64, 2
      optional :double_value, :double, 3
      optional :string_value, :string, 4
      optional :bool_value, :bool, 5
      optional :struct_value, :message, 6, "rover.protobuf.Struct"
      optional :list_value, :message, 7, "rover.protobuf.ListValue"
    end
  end
  add_message "rover.protobuf.ListValue" do
    repeated :values, :message, 1, "rover.protobuf.Value"
  end
  add_enum "rover.protobuf.NullValue" do
    value :NULL_VALUE, 0
  end
end

module Rover
  module Protobuf
    Struct = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.protobuf.Struct").msgclass
    Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.protobuf.Value").msgclass
    ListValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.protobuf.ListValue").msgclass
    NullValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("rover.protobuf.NullValue").enummodule
  end
end
