#!/bin/sh

set -e
source ./docker/functions.bash

run() {
	go run ./events/cmd/pipeline/main.go
}

test() {
	# wait for kafka client
	waiton kafka 9092
	# wait for zookeeper client
	waiton kafka 2181
	go test github.com/roverplatform/rover/events/backend/...
}

main $@
