#!/bin/bash

set -e

PROTO_PATH=./protos/

# map google.protobuf.timestamp.proto to our extended timestamp wich extends original Timesatmp
# in order to be able serialize it to the DB
# MAP="Mgoogle/protobuf/timestamp.proto=github.com/golang/protobuf/ptypes/timestamp"
GO_MAPS="Mgoogle/protobuf/timestamp.proto=github.com/roverplatform/rover/go/protobuf/ptypes/timestamp"
GO_MAPS+=",Mauth/v1/auth.proto=github.com/roverplatform/rover/apis/go/auth/v1"

echo "Generating from: $PROTO_PATH"

RUBY_DIR=./apis/ruby/rover-apis
GO_DIR=./apis/go
NODE_DIR=./apis/node

FILES="`find ./protos/ -name *.proto`"

for proto in $FILES; do
	protoc -I ${PROTO_PATH} --go_out=plugins=grpc,$GO_MAPS:$GO_DIR $proto
done

protoc -I ${PROTO_PATH} --ruby_out=$RUBY_DIR --grpc_out=$RUBY_DIR --plugin=protoc-gen-grpc=`which grpc_tools_ruby_protoc_plugin` $FILES
protoc -I ${PROTO_PATH} --js_out=import_style=commonjs,binary:$NODE_DIR --grpc_out=$NODE_DIR --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` $FILES
