#!/bin/bash

set -e


PATH=$PATH:./node_modules/.bin

PROTO_PATH=./protos/
PROTO_PATH=${PROTO_PATH}:${GOPATH}/src

# map google.protobuf.timestamp.proto to our extended timestamp wich extends original Timesatmp
# in order to be able serialize it to the DB
# MAP="Mgoogle/protobuf/timestamp.proto=github.com/golang/protobuf/ptypes/timestamp"
MAP="Mgoogle/protobuf/timestamp.proto=github.com/roverplatform/rover/go/protobuf/ptypes/timestamp"


echo $PROTO_PATH

FILES="`find ./protos/ -name *.proto`"

for proto in $FILES; do
	protoc -I ${PROTO_PATH} --go_out=plugins=grpc,$MAP:./apis/go $proto
done

protoc -I ${PROTO_PATH} --ruby_out=./apis/ruby/rover-apis --grpc_out=./apis/ruby/rover-apis --plugin=protoc-gen-grpc=`which grpc_tools_ruby_protoc_plugin` $FILES
protoc -I ${PROTO_PATH} --js_out=import_style=commonjs,binary:./apis/node --grpc_out=./apis/node --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` $FILES
