#!/bin/sh

# set -x

source ./docker/functions.bash

SVC_HOME=./notification

run() {
    go run $SVC_HOME/cmd/notification-service/main.go
}

test() {
    waiton postgres 5432
    waiton scylla 9042

    go test $SVC_HOME/...
}

migrate() {
  set -e
  waiton postgres 5432
  waiton scylla 9042
  
  go run ./go/cmd/postgres-cli/main.go \
    --db-dsn=$POSTGRES_DSN \
    --migration-path=$SVC_HOME/postgres/migrations

  go run ./go/cmd/scylla-cli/main.go --dsn=$SCYLLA_DSN \
    --migration-path=$SVC_HOME/scylla/migrations \
    --create-keyspace \
    --keyspace-replicas=1
}

main $@
