version: "3"

volumes:
  cachefs:
  pgdata:
  esdata:
  mongodata:

services:

  pubsub:
    build:
      context: ./pubsub
    volumes:
      - ../../rover:/rover
    ports: 
      - "8085"

  # DATABASES
  mongo:
    image: mongo:3.4.4
    ports:
      - 27017
    volumes:
      - ../../rover:/rover
      - mongodata:/data/db

  kafka:
      image: spotify/kafka
      environment:
        - AUTO_CREATE_TOPICS=true
        - ADVERTISED_HOST=kafka
        - NUM_PARTITIONS=3

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - 9200
      - 9300
    volumes:
      - ../:/rover
      - esdata:/usr/share/elasticsearch/data
    environment:
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
      transport.host: "127.0.0.1"
      network.host: "0.0.0.0"
      http.host: "0.0.0.0"
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  postgres:
    image: postgres:9.6-alpine
    ports: [5432]
    volumes:
      # postgres runs *.sql from /docker-entrypoint-initdb.d on startup
      - ./vendor/postgres/initdb.d:/docker-entrypoint-initdb.d/

  scylla:
    image: scylladb/scylla:2.1.1

  redis:
    image: redis:4.0.2-alpine

  rabbitmq:
    build:
      context: ./vendor/rabbitmq
    ports:
      - 15672

  kafka:
    image: spotify/kafka
    environment:
      - AUTO_CREATE_TOPICS=true
      - ADVERTISED_HOST=kafka
      - NUM_PARTITIONS=3

  influxdb:
    image: influxdb:1.5.3

        
  # ROVER PROJECTS
  analytics-collector:
    image: roverio/golang-rdkafka:1.10-alpine
    command: ./docker/analytics/cmd run_collector
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - kafka
      - influxdb
    environment:
      CGO_ENABLED: 1
      KAFKA_DSN: kafka:9092
      INPUT_TOPICS: events.output
      LOG_LEVEL: debug

  analytics-service:
    image: golang:1.10-alpine
    command: ./docker/analytics/cmd run_service
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - influxdb
    environment:
      CGO_ENABLED: 1
      LOG_LEVEL: debug

  audience-frontend:
    image: node:6.12.0
    depends_on:
      - graphql-gateway
    volumes:
      - ../:/rover:delegated
    working_dir: /rover/react-audience
    command: bash -c "/rover/docker/scripts/wait.sh graphql-gateway:80 -t 60 -- npm install && npm run schema && npm run relay && npm start"
    environment:
      NODE_ENV: development
      GRAPHQL_HOST: "http://graphql-gateway/graphql"

  audience-service:
    image: golang:1.10-alpine
    depends_on:
      - mongo
      - elastic
      - pubsub
      - audience-segments-worker
    command: ./docker/audience/cmd configure_pubsub run
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      AUDIENCE_SERVICE_PUBSUB_TOPIC_NAME: "audience-service-dev-topic"
      AUDIENCE_SERVICE_MONGO_DSN: "mongodb://mongo:27017/audience_service_dev"
      AUDIENCE_SERVICE_ELASTIC_DSN: "http://elastic:9200"
      AUDIENCE_SERVICE_NOTIFIER_FLUSH_INTERVAL: 5s
      AUDIENCE_SERVICE_GCP_PROJECT_ID: "rover-development"
      PUBSUB_EMULATOR_HOST: "pubsub:8085"
      GCP_PROJECT_ID: "rover-development"
      PUBSUB_TOPIC_NAME: "audience-service-dev-topic"           # Used in pubsub-cli to configure the topic
      PUBSUB_SUBSCRIPTION: "audience-service-dev-subscription"  # Used in pubsub-cli to configure the topic

  audience-segments-worker:
    image: golang:1.10-alpine
    depends_on:
      - pubsub
      - elastic
      - mongo
    command: ./docker/audience/cmd configure_pubsub run_worker
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    environment: 
      SEGMENTS_WORKER_MONGO_DSN: "mongodb://mongo:27017/audience_service_dev"
      SEGMENTS_WORKER_ELASTIC_DSN: "http://elastic:9200"
      SEGMENTS_WORKER_PUBSUB_SUBSCRIPTION: "audience-service-dev-subscription"
      SEGMENTS_WORKER_GCP_PROJECT_ID: "rover-development"
      PUBSUB_EMULATOR_HOST: "pubsub:8085"
      GCP_PROJECT_ID: "rover-development"
      PUBSUB_TOPIC_NAME: "audience-service-dev-topic"           # Used in pubsub-cli to configure the topic
      PUBSUB_SUBSCRIPTION: "audience-service-dev-subscription"  # Used in pubsub-cli to configure the topic

  auth-service:
    image: golang:1.10-alpine
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - postgres
    command: ./docker/auth/cmd migrate run
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      TEST_DB_DSN: "postgres://postgres:@postgres:5432/authsvc_test?sslmode=disable"
      DB_DSN: "postgres://postgres:@postgres:5432/authsvc_dev?sslmode=disable"
      MIGRATION_DIR: ./auth/service/db/migrations/postgres

  campaigns-service:
    image: golang:1.10-alpine
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - postgres
      - campaigns-scheduled_notification_tasks-worker
      - notification-service
    command: ./docker/campaigns/cmd migrate run
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      DB_DSN: "postgres://postgres:@postgres:5432/campaigns_dev?sslmode=disable"
      TEST_DB_DSN: "postgres://postgres:@postgres:5432/campaigns_test?sslmode=disable"
      POSTGRES_DSN: "postgres://postgres:@postgres:5432/campaigns_dev?sslmode=disable"
      TEST_POSTGRES_DSN: "postgres://postgres:@postgres:5432/campaigns_test?sslmode=disable"
      NOTIFICATION_SERVICE_URL: "notification-service:5100"

  campaigns-scheduled_notification_tasks-worker:
    image: golang:1.10-alpine
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - postgres
      - audience-service
    command: ./docker/campaigns/cmd migrate run_worker
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      POSTGRES_DSN: "postgres://postgres:@postgres:5432/campaigns_dev?sslmode=disable"
      AUDIENCE_SERVICE_URL: "audience-service:5100"

  notification-service:
    ports: [5080]
    image: golang:1.10-alpine
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - postgres
      - scylla
      - pubsub
    command: ./docker/notification/cmd migrate run
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0

      POSTGRES_DSN: "postgres://postgres:@postgres:5432/notification_dev?sslmode=disable"
      TEST_POSTGRES_DSN: "postgres://postgres:@postgres:5432/notification_test?sslmode=disable"
      SCYLLA_DSN: "scylla://scylla:9042/notification_dev"
      TEST_SCYLLA_DSN: "scylla://scylla:9042/notification_test?timeout=5s"
      GCP_PROJECT_ID: "rover-development"
      PUBSUB_EMULATOR_HOST: "pubsub:8085"
      PUBSUB_TOPIC: "notification-service-dev-topic"


  campaigns-frontend:
    image: node:7.5.0
    depends_on:
      - graphql-gateway
    volumes:
      - ../:/rover:delegated
    working_dir: /rover/react-campaigns
    command: bash -c "npm install && npm start"
    environment:
      NODE_ENV: development
      GRAPHQL_HOST: "http://graphql-gateway/graphql"

  graphql-gateway:
    image: node:7.10.1
    depends_on:
      - auth-service
      - audience-service
      - campaigns-service
      - notification-service
      - kafka
    ports:
      - "4000:80"
    command: bash -c "rm -rf node_modules/@rover && npm install && npm run build && node dist"
    volumes:
      - ../:/rover:delegated
    working_dir: /rover/graphql-gateway
    environment:
      AUTH_V1_SERVICE_HOST: auth-service
      AUDIENCE_V1_SERVICE_HOST: audience-service
      CAMPAIGNS_V1_SERVICE_HOST: campaigns-service
      NOTIFICATION_V1_SERVICE_HOST: notification-service
      KAFKA_DSN: kafka:9092
      EVENTS_PIPELINE_INPUT_TOPIC: events.input
      NODE_ENV: development
  
  graphql-admin:
    image: node:7.10.1
    depends_on:
      - auth-service
    ports:
      - "4001:80"
    command: bash -c "rm -rf node_modules/@rover && npm install && npm run build && node dist"
    volumes:
      - ../:/rover:delegated
    working_dir: /rover/graphql-admin
    environment:
      AUTH_V1_SERVICE_HOST: auth-service
      AUTH_CLIENT_ID: "1025209954364-pgmntrdfq5526cq2slgsa4ao82a3qtls.apps.googleusercontent.com"
      AUTH_CLIENT_SECRET: "DPD50JrQqU5Xbsgdk2PkxSJh"
      NODE_ENV: development
 
  admin-dashboard:
    image: node:7.10.1
    depends_on:
      - graphql-admin
    volumes:
      - ../:/rover:delegated
    working_dir: /rover/admin-dashboard
    command: bash -c "npm install && npm start"
    environment:
      NODE_ENV: development
      AUTH_CLIENT_ID: "1025209954364-pgmntrdfq5526cq2slgsa4ao82a3qtls.apps.googleusercontent.com"

  geocoder-service:
    image: golang:1.10-alpine
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - redis
    command: go run ./geocoder/service/cmd/service/main.go
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    environment:
      REDIS_DSN: "redis://redis:6379/3"
      LOCATIONIQ_API_KEY: "926b09abbef41a"
      LOCATIONIQ_ZOOM_LEVEL: 10
      COUNTRY_MAPPING: "./geocoder/service/mappings/ISO3166Countries.json"

  events-pipeline:
    image: roverio/golang-rdkafka:1.10-alpine
    command: ./docker/events/pipeline/cmd run
    volumes:
      - ../:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - kafka
      - audience-service
      - geocoder-service
      - postgres
    environment:
      CGO_ENABLED: 1
      KAFKA_DSN: kafka:9092
      INPUT_TOPIC: events.input
      OUTPUT_TOPIC: events.output
      AUDIENCE_SERVICE_DSN: audience-service:5100
      GEOCODER_SERVICE_DSN: geocoder-service:5100
      LOG_LEVEL: debug
      POSTGRES_DSN: "postgres://postgres:@postgres:5432/events_pipeline_dev?sslmode=disable"
      DEVICE_MODEL_NAME_MAP_PATH: ./events/backend/sample-device-mapping.json

  smw:
    image: node:6.9.1
    working_dir: /rover/scheduled-messages-worker
    volumes:
      - ../:/rover/
    depends_on:
      - mongo
      - rabbitmq
      - redis
      - audience-service
    command: bash -c "/rover/docker/scripts/wait.sh rabbitmq:5672 -s -- npm install && npm start"
    environment:
      NODE_ENV: production
      LOG_LEVEL: DEBUG
      DEBUG: job:*
      DEBUG_COLORS: 1
      REDIS_URL: redis://redis/1
      REDIS_INBOX_URL: redis://redis/2
      RAVEN_ENABLED: "false"
      CLOUDAMQP_URL: amqp://rabbitmq
      MONGODB_URI: mongodb://mongo:27017/rover-local
      AUDIENCE_V1_SERVICE_HOST: audience-service
      NPM_TOKEN: dad33a01-0f48-47df-9797-9b36dd5f957c

  sdk-api:
    image: node:7.5
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - audience-service
      - auth-service
      - geocoder-service
      - notification-service
    working_dir: /rover/sdk-api
    ports: [3100]
    volumes:
      - ../:/rover
    command: bash -c "/rover/docker/scripts/wait.sh rabbitmq:5672 -- npm install && npm run dev"
    environment:
      NODE_ENV: production

      POSTGRESQL_DB_HOST: postgres
      POSTGRESQL_DB_NAME: rover-local

      REDIS_URL: redis://redis:6379/0
      REDIS_INBOX_URL: redis://redis:6379/1

      AUDIENCE_V1_SERVICE_HOST: audience-service
      AUTH_V1_SERVICE_HOST: auth-service
      GEOCODER_V1_SERVICE_HOST: geocoder-service
      NOTIFICATION_V1_SERVICE_HOST: notification-service

      MONGODB_URI: mongodb://mongo:27017/rover-local

      ELASTICSEARCH_URLS: http://elastic:9200/

      CLOUDAMQP_URL: amqp://rabbitmq

      LOG_LEVEL: "debug"
      PORT: 3100
