version: "3"

volumes:
  cachefs:
  pgdata:
  esdata:

services:

  mongo:
    image: mongo:3.4.4
    ports: [27017]
    volumes:
      - ../../rover:/rover

  elastic:
    container_name: elastic5
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports: [9200, 9300]
    volumes:
      - ../../rover:/rover
      - esdata:/usr/share/elasticsearch/data
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   mem_limit: 1g
    environment:
      # xpack.graph.enabled: "false"
      # xpack.ml.enabled: "false"
      # xpack.reporting.enabled: "false"
      # xpack.watcher.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
      transport.host: "127.0.0.1"
      network.host: "0.0.0.0"
      http.host: "0.0.0.0"
      # discovery.zen.minimum_master_nodes: 1
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  postgres:
    image: postgres:9.6-alpine
    ports: [5432]
    volumes:
      # postgres runs *.sql from /docker-entrypoint-initdb.d on startup
      - ./vendor/postgres/initdb.d:/docker-entrypoint-initdb.d/

  auth-service:
    image: golang:1.9-alpine
    links: [postgres]
    ports: [5100, 5080]
    command: ./docker/auth-service/cmd test run
    volumes:
      - ../../rover:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      DB_DSN: "postgres://postgres:@postgres:5432/authsvc_test?sslmode=disable"

  audience-service:
    image: golang:1.9-alpine
    links: [mongo, elastic]
    ports: [5100, 5080]
    command: ./docker/audience-service/cmd test run
    volumes:
      - ../../rover:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      AUDIENCE_SERVICE_MONGO_DSN: "mongodb://mongo:27017/audience_service_test"
      AUDIENCE_SERVICE_ELASTIC_DSN: "http://elastic5:9200"
