version: "3"

volumes:
  cachefs:
  pgdata:

services:

  mongo:
    image: mongo
    ports: [27017]
    volumes:
      - ../../rover:/rover

  elasticsearch:
    image: elasticsearch:2.4
    ports: [9200, 9300]
    volumes:
      - ../../rover:/rover

  postgres:
    image: rover/postgres
    ports: [5432]
    build:
      context: ../../rover
      dockerfile: ./docker/vendor/postgres/Dockerfile
    volumes:
      - ../../rover:/rover
      - pgdata:/var/lib/postgresql/data

  auth-service:
    image: golang:1.8-alpine
    links: [postgres]
    ports: [5100, 5080]
    command: ./docker/auth-service/cmd test run
    volumes:
      - ../../rover:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      DB_DSN: "postgres://postgres:@postgres:5432/authsvc_test?sslmode=disable"

  audience-service:
    image: golang:1.8-alpine
    links: [mongo]
    ports: [5100, 5080]
    command: ./docker/audience-service/cmd test run
    volumes:
      - ../../rover:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    environment:
      CGO_ENABLED: 0
      MONGO_DSN: "mongodb://mongo:27017/audience_service_test"
