// Code generated by protoc-gen-go. DO NOT EDIT.
// source: csv-processor/v1/csv-processor.proto

/*
Package csv_processor is a generated protocol buffer package.

It is generated from these files:
	csv-processor/v1/csv-processor.proto

It has these top-level messages:
	GCSObject
	LoadJob
	SegmentLoadJobConfig
	SegmentLoadJobWithCsvFileConfig
	ProfileLoadJobConfig
	ProfileTagJobConfig
	GetLoadJobRequest
	GetLoadJobReply
	CreateLoadJobRequest
	CreateLoadJobReply
*/
package csv_processor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/roverplatform/rover/go/protobuf/ptypes/timestamp"
import rover_auth_v1 "github.com/roverplatform/rover/apis/go/auth/v1"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobType int32

const (
	JobType_SEGMENT               JobType = 0
	JobType_SEGMENT_WITH_CSV_FILE JobType = 1
	JobType_PROFILE_IMPORT        JobType = 2
	JobType_PROFILE_TAG           JobType = 3
)

var JobType_name = map[int32]string{
	0: "SEGMENT",
	1: "SEGMENT_WITH_CSV_FILE",
	2: "PROFILE_IMPORT",
	3: "PROFILE_TAG",
}
var JobType_value = map[string]int32{
	"SEGMENT":               0,
	"SEGMENT_WITH_CSV_FILE": 1,
	"PROFILE_IMPORT":        2,
	"PROFILE_TAG":           3,
}

func (x JobType) String() string {
	return proto.EnumName(JobType_name, int32(x))
}
func (JobType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type JobStatus int32

const (
	JobStatus_UNKNOWN    JobStatus = 0
	JobStatus_ENQUEUED   JobStatus = 1
	JobStatus_PROCESSING JobStatus = 2
	JobStatus_FAILED     JobStatus = 3
	JobStatus_COMPLETED  JobStatus = 4
)

var JobStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENQUEUED",
	2: "PROCESSING",
	3: "FAILED",
	4: "COMPLETED",
}
var JobStatus_value = map[string]int32{
	"UNKNOWN":    0,
	"ENQUEUED":   1,
	"PROCESSING": 2,
	"FAILED":     3,
	"COMPLETED":  4,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GCSObject struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Bucket    string `protobuf:"bytes,2,opt,name=bucket" json:"bucket,omitempty"`
	FileId    string `protobuf:"bytes,3,opt,name=file_id,json=fileId" json:"file_id,omitempty"`
}

func (m *GCSObject) Reset()                    { *m = GCSObject{} }
func (m *GCSObject) String() string            { return proto.CompactTextString(m) }
func (*GCSObject) ProtoMessage()               {}
func (*GCSObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GCSObject) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *GCSObject) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GCSObject) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type LoadJob struct {
	Id        int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AccountId int32                      `protobuf:"varint,2,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Type      JobType                    `protobuf:"varint,3,opt,name=type,enum=rover.csv_processor.v1.JobType" json:"type,omitempty"`
	Status    JobStatus                  `protobuf:"varint,4,opt,name=status,enum=rover.csv_processor.v1.JobStatus" json:"status,omitempty"`
	Progress  int32                      `protobuf:"varint,5,opt,name=progress" json:"progress,omitempty"`
	CreatedAt *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// Optional
	FailedReason string `protobuf:"bytes,7,opt,name=failed_reason,json=failedReason" json:"failed_reason,omitempty"`
}

func (m *LoadJob) Reset()                    { *m = LoadJob{} }
func (m *LoadJob) String() string            { return proto.CompactTextString(m) }
func (*LoadJob) ProtoMessage()               {}
func (*LoadJob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoadJob) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoadJob) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *LoadJob) GetType() JobType {
	if m != nil {
		return m.Type
	}
	return JobType_SEGMENT
}

func (m *LoadJob) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_UNKNOWN
}

func (m *LoadJob) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *LoadJob) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *LoadJob) GetFailedReason() string {
	if m != nil {
		return m.FailedReason
	}
	return ""
}

//
// Load Job Configs
type SegmentLoadJobConfig struct {
	AccountId int32      `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	SegmentId int32      `protobuf:"varint,2,opt,name=segment_id,json=segmentId" json:"segment_id,omitempty"`
	Csv       *GCSObject `protobuf:"bytes,3,opt,name=csv" json:"csv,omitempty"`
}

func (m *SegmentLoadJobConfig) Reset()                    { *m = SegmentLoadJobConfig{} }
func (m *SegmentLoadJobConfig) String() string            { return proto.CompactTextString(m) }
func (*SegmentLoadJobConfig) ProtoMessage()               {}
func (*SegmentLoadJobConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SegmentLoadJobConfig) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *SegmentLoadJobConfig) GetSegmentId() int32 {
	if m != nil {
		return m.SegmentId
	}
	return 0
}

func (m *SegmentLoadJobConfig) GetCsv() *GCSObject {
	if m != nil {
		return m.Csv
	}
	return nil
}

type SegmentLoadJobWithCsvFileConfig struct {
	AccountId       int32 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	StaticSegmentId int32 `protobuf:"varint,2,opt,name=static_segment_id,json=staticSegmentId" json:"static_segment_id,omitempty"`
	CsvFileId       int32 `protobuf:"varint,3,opt,name=csv_file_id,json=csvFileId" json:"csv_file_id,omitempty"`
}

func (m *SegmentLoadJobWithCsvFileConfig) Reset()                    { *m = SegmentLoadJobWithCsvFileConfig{} }
func (m *SegmentLoadJobWithCsvFileConfig) String() string            { return proto.CompactTextString(m) }
func (*SegmentLoadJobWithCsvFileConfig) ProtoMessage()               {}
func (*SegmentLoadJobWithCsvFileConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SegmentLoadJobWithCsvFileConfig) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *SegmentLoadJobWithCsvFileConfig) GetStaticSegmentId() int32 {
	if m != nil {
		return m.StaticSegmentId
	}
	return 0
}

func (m *SegmentLoadJobWithCsvFileConfig) GetCsvFileId() int32 {
	if m != nil {
		return m.CsvFileId
	}
	return 0
}

type ProfileLoadJobConfig struct {
	AccountId int32                          `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	CsvFileId int32                          `protobuf:"varint,2,opt,name=csv_file_id,json=csvFileId" json:"csv_file_id,omitempty"`
	Schema    []*ProfileLoadJobConfig_Schema `protobuf:"bytes,3,rep,name=schema" json:"schema,omitempty"`
}

func (m *ProfileLoadJobConfig) Reset()                    { *m = ProfileLoadJobConfig{} }
func (m *ProfileLoadJobConfig) String() string            { return proto.CompactTextString(m) }
func (*ProfileLoadJobConfig) ProtoMessage()               {}
func (*ProfileLoadJobConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProfileLoadJobConfig) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *ProfileLoadJobConfig) GetCsvFileId() int32 {
	if m != nil {
		return m.CsvFileId
	}
	return 0
}

func (m *ProfileLoadJobConfig) GetSchema() []*ProfileLoadJobConfig_Schema {
	if m != nil {
		return m.Schema
	}
	return nil
}

type ProfileLoadJobConfig_Schema struct {
	Type        string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Field       string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *ProfileLoadJobConfig_Schema) Reset()                    { *m = ProfileLoadJobConfig_Schema{} }
func (m *ProfileLoadJobConfig_Schema) String() string            { return proto.CompactTextString(m) }
func (*ProfileLoadJobConfig_Schema) ProtoMessage()               {}
func (*ProfileLoadJobConfig_Schema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *ProfileLoadJobConfig_Schema) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProfileLoadJobConfig_Schema) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *ProfileLoadJobConfig_Schema) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ProfileTagJobConfig struct {
	AccountId int32    `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	CsvFileId int32    `protobuf:"varint,2,opt,name=csv_file_id,json=csvFileId" json:"csv_file_id,omitempty"`
	Tags      []string `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *ProfileTagJobConfig) Reset()                    { *m = ProfileTagJobConfig{} }
func (m *ProfileTagJobConfig) String() string            { return proto.CompactTextString(m) }
func (*ProfileTagJobConfig) ProtoMessage()               {}
func (*ProfileTagJobConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProfileTagJobConfig) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *ProfileTagJobConfig) GetCsvFileId() int32 {
	if m != nil {
		return m.CsvFileId
	}
	return 0
}

func (m *ProfileTagJobConfig) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GetLoadJobRequest struct {
	AuthContext *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	LoadJobId   int32                      `protobuf:"varint,2,opt,name=load_job_id,json=loadJobId" json:"load_job_id,omitempty"`
	//
	// 0 -> static-segments (default)
	// 1 -> static-segments
	// 2 -> load-jobs
	QueueVersion int32 `protobuf:"varint,3,opt,name=queue_version,json=queueVersion" json:"queue_version,omitempty"`
}

func (m *GetLoadJobRequest) Reset()                    { *m = GetLoadJobRequest{} }
func (m *GetLoadJobRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLoadJobRequest) ProtoMessage()               {}
func (*GetLoadJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetLoadJobRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *GetLoadJobRequest) GetLoadJobId() int32 {
	if m != nil {
		return m.LoadJobId
	}
	return 0
}

func (m *GetLoadJobRequest) GetQueueVersion() int32 {
	if m != nil {
		return m.QueueVersion
	}
	return 0
}

type GetLoadJobReply struct {
	Job *LoadJob `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *GetLoadJobReply) Reset()                    { *m = GetLoadJobReply{} }
func (m *GetLoadJobReply) String() string            { return proto.CompactTextString(m) }
func (*GetLoadJobReply) ProtoMessage()               {}
func (*GetLoadJobReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetLoadJobReply) GetJob() *LoadJob {
	if m != nil {
		return m.Job
	}
	return nil
}

type CreateLoadJobRequest struct {
	AuthContext *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	Type        JobType                    `protobuf:"varint,2,opt,name=type,enum=rover.csv_processor.v1.JobType" json:"type,omitempty"`
	// Types that are valid to be assigned to JobConfig:
	//	*CreateLoadJobRequest_SegmentLoadJobConfig
	//	*CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig
	//	*CreateLoadJobRequest_ProfileLoadJobConfig
	//	*CreateLoadJobRequest_ProfileTagJobConfig
	JobConfig isCreateLoadJobRequest_JobConfig `protobuf_oneof:"job_config"`
}

func (m *CreateLoadJobRequest) Reset()                    { *m = CreateLoadJobRequest{} }
func (m *CreateLoadJobRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLoadJobRequest) ProtoMessage()               {}
func (*CreateLoadJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isCreateLoadJobRequest_JobConfig interface {
	isCreateLoadJobRequest_JobConfig()
}

type CreateLoadJobRequest_SegmentLoadJobConfig struct {
	SegmentLoadJobConfig *SegmentLoadJobConfig `protobuf:"bytes,3,opt,name=segment_load_job_config,json=segmentLoadJobConfig,oneof"`
}
type CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig struct {
	SegmentLoadJobWithCsvFileConfig *SegmentLoadJobWithCsvFileConfig `protobuf:"bytes,4,opt,name=segment_load_job_with_csv_file_config,json=segmentLoadJobWithCsvFileConfig,oneof"`
}
type CreateLoadJobRequest_ProfileLoadJobConfig struct {
	ProfileLoadJobConfig *ProfileLoadJobConfig `protobuf:"bytes,5,opt,name=profile_load_job_config,json=profileLoadJobConfig,oneof"`
}
type CreateLoadJobRequest_ProfileTagJobConfig struct {
	ProfileTagJobConfig *ProfileTagJobConfig `protobuf:"bytes,6,opt,name=profile_tag_job_config,json=profileTagJobConfig,oneof"`
}

func (*CreateLoadJobRequest_SegmentLoadJobConfig) isCreateLoadJobRequest_JobConfig()            {}
func (*CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig) isCreateLoadJobRequest_JobConfig() {}
func (*CreateLoadJobRequest_ProfileLoadJobConfig) isCreateLoadJobRequest_JobConfig()            {}
func (*CreateLoadJobRequest_ProfileTagJobConfig) isCreateLoadJobRequest_JobConfig()             {}

func (m *CreateLoadJobRequest) GetJobConfig() isCreateLoadJobRequest_JobConfig {
	if m != nil {
		return m.JobConfig
	}
	return nil
}

func (m *CreateLoadJobRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *CreateLoadJobRequest) GetType() JobType {
	if m != nil {
		return m.Type
	}
	return JobType_SEGMENT
}

func (m *CreateLoadJobRequest) GetSegmentLoadJobConfig() *SegmentLoadJobConfig {
	if x, ok := m.GetJobConfig().(*CreateLoadJobRequest_SegmentLoadJobConfig); ok {
		return x.SegmentLoadJobConfig
	}
	return nil
}

func (m *CreateLoadJobRequest) GetSegmentLoadJobWithCsvFileConfig() *SegmentLoadJobWithCsvFileConfig {
	if x, ok := m.GetJobConfig().(*CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig); ok {
		return x.SegmentLoadJobWithCsvFileConfig
	}
	return nil
}

func (m *CreateLoadJobRequest) GetProfileLoadJobConfig() *ProfileLoadJobConfig {
	if x, ok := m.GetJobConfig().(*CreateLoadJobRequest_ProfileLoadJobConfig); ok {
		return x.ProfileLoadJobConfig
	}
	return nil
}

func (m *CreateLoadJobRequest) GetProfileTagJobConfig() *ProfileTagJobConfig {
	if x, ok := m.GetJobConfig().(*CreateLoadJobRequest_ProfileTagJobConfig); ok {
		return x.ProfileTagJobConfig
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateLoadJobRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateLoadJobRequest_OneofMarshaler, _CreateLoadJobRequest_OneofUnmarshaler, _CreateLoadJobRequest_OneofSizer, []interface{}{
		(*CreateLoadJobRequest_SegmentLoadJobConfig)(nil),
		(*CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig)(nil),
		(*CreateLoadJobRequest_ProfileLoadJobConfig)(nil),
		(*CreateLoadJobRequest_ProfileTagJobConfig)(nil),
	}
}

func _CreateLoadJobRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateLoadJobRequest)
	// job_config
	switch x := m.JobConfig.(type) {
	case *CreateLoadJobRequest_SegmentLoadJobConfig:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SegmentLoadJobConfig); err != nil {
			return err
		}
	case *CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SegmentLoadJobWithCsvFileConfig); err != nil {
			return err
		}
	case *CreateLoadJobRequest_ProfileLoadJobConfig:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProfileLoadJobConfig); err != nil {
			return err
		}
	case *CreateLoadJobRequest_ProfileTagJobConfig:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ProfileTagJobConfig); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateLoadJobRequest.JobConfig has unexpected type %T", x)
	}
	return nil
}

func _CreateLoadJobRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateLoadJobRequest)
	switch tag {
	case 3: // job_config.segment_load_job_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SegmentLoadJobConfig)
		err := b.DecodeMessage(msg)
		m.JobConfig = &CreateLoadJobRequest_SegmentLoadJobConfig{msg}
		return true, err
	case 4: // job_config.segment_load_job_with_csv_file_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SegmentLoadJobWithCsvFileConfig)
		err := b.DecodeMessage(msg)
		m.JobConfig = &CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig{msg}
		return true, err
	case 5: // job_config.profile_load_job_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProfileLoadJobConfig)
		err := b.DecodeMessage(msg)
		m.JobConfig = &CreateLoadJobRequest_ProfileLoadJobConfig{msg}
		return true, err
	case 6: // job_config.profile_tag_job_config
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ProfileTagJobConfig)
		err := b.DecodeMessage(msg)
		m.JobConfig = &CreateLoadJobRequest_ProfileTagJobConfig{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateLoadJobRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateLoadJobRequest)
	// job_config
	switch x := m.JobConfig.(type) {
	case *CreateLoadJobRequest_SegmentLoadJobConfig:
		s := proto.Size(x.SegmentLoadJobConfig)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateLoadJobRequest_SegmentLoadJobWithCsvFileConfig:
		s := proto.Size(x.SegmentLoadJobWithCsvFileConfig)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateLoadJobRequest_ProfileLoadJobConfig:
		s := proto.Size(x.ProfileLoadJobConfig)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateLoadJobRequest_ProfileTagJobConfig:
		s := proto.Size(x.ProfileTagJobConfig)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateLoadJobReply struct {
	Job *LoadJob `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *CreateLoadJobReply) Reset()                    { *m = CreateLoadJobReply{} }
func (m *CreateLoadJobReply) String() string            { return proto.CompactTextString(m) }
func (*CreateLoadJobReply) ProtoMessage()               {}
func (*CreateLoadJobReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateLoadJobReply) GetJob() *LoadJob {
	if m != nil {
		return m.Job
	}
	return nil
}

func init() {
	proto.RegisterType((*GCSObject)(nil), "rover.csv_processor.v1.GCSObject")
	proto.RegisterType((*LoadJob)(nil), "rover.csv_processor.v1.LoadJob")
	proto.RegisterType((*SegmentLoadJobConfig)(nil), "rover.csv_processor.v1.SegmentLoadJobConfig")
	proto.RegisterType((*SegmentLoadJobWithCsvFileConfig)(nil), "rover.csv_processor.v1.SegmentLoadJobWithCsvFileConfig")
	proto.RegisterType((*ProfileLoadJobConfig)(nil), "rover.csv_processor.v1.ProfileLoadJobConfig")
	proto.RegisterType((*ProfileLoadJobConfig_Schema)(nil), "rover.csv_processor.v1.ProfileLoadJobConfig.Schema")
	proto.RegisterType((*ProfileTagJobConfig)(nil), "rover.csv_processor.v1.ProfileTagJobConfig")
	proto.RegisterType((*GetLoadJobRequest)(nil), "rover.csv_processor.v1.GetLoadJobRequest")
	proto.RegisterType((*GetLoadJobReply)(nil), "rover.csv_processor.v1.GetLoadJobReply")
	proto.RegisterType((*CreateLoadJobRequest)(nil), "rover.csv_processor.v1.CreateLoadJobRequest")
	proto.RegisterType((*CreateLoadJobReply)(nil), "rover.csv_processor.v1.CreateLoadJobReply")
	proto.RegisterEnum("rover.csv_processor.v1.JobType", JobType_name, JobType_value)
	proto.RegisterEnum("rover.csv_processor.v1.JobStatus", JobStatus_name, JobStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CsvProcessor service

type CsvProcessorClient interface {
	GetLoadJob(ctx context.Context, in *GetLoadJobRequest, opts ...grpc.CallOption) (*GetLoadJobReply, error)
	CreateLoadJob(ctx context.Context, in *CreateLoadJobRequest, opts ...grpc.CallOption) (*CreateLoadJobReply, error)
}

type csvProcessorClient struct {
	cc *grpc.ClientConn
}

func NewCsvProcessorClient(cc *grpc.ClientConn) CsvProcessorClient {
	return &csvProcessorClient{cc}
}

func (c *csvProcessorClient) GetLoadJob(ctx context.Context, in *GetLoadJobRequest, opts ...grpc.CallOption) (*GetLoadJobReply, error) {
	out := new(GetLoadJobReply)
	err := grpc.Invoke(ctx, "/rover.csv_processor.v1.CsvProcessor/GetLoadJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *csvProcessorClient) CreateLoadJob(ctx context.Context, in *CreateLoadJobRequest, opts ...grpc.CallOption) (*CreateLoadJobReply, error) {
	out := new(CreateLoadJobReply)
	err := grpc.Invoke(ctx, "/rover.csv_processor.v1.CsvProcessor/CreateLoadJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CsvProcessor service

type CsvProcessorServer interface {
	GetLoadJob(context.Context, *GetLoadJobRequest) (*GetLoadJobReply, error)
	CreateLoadJob(context.Context, *CreateLoadJobRequest) (*CreateLoadJobReply, error)
}

func RegisterCsvProcessorServer(s *grpc.Server, srv CsvProcessorServer) {
	s.RegisterService(&_CsvProcessor_serviceDesc, srv)
}

func _CsvProcessor_GetLoadJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsvProcessorServer).GetLoadJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.csv_processor.v1.CsvProcessor/GetLoadJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsvProcessorServer).GetLoadJob(ctx, req.(*GetLoadJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CsvProcessor_CreateLoadJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoadJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CsvProcessorServer).CreateLoadJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.csv_processor.v1.CsvProcessor/CreateLoadJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CsvProcessorServer).CreateLoadJob(ctx, req.(*CreateLoadJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CsvProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rover.csv_processor.v1.CsvProcessor",
	HandlerType: (*CsvProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLoadJob",
			Handler:    _CsvProcessor_GetLoadJob_Handler,
		},
		{
			MethodName: "CreateLoadJob",
			Handler:    _CsvProcessor_CreateLoadJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "csv-processor/v1/csv-processor.proto",
}

func init() { proto.RegisterFile("csv-processor/v1/csv-processor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x72, 0xdb, 0x54,
	0x10, 0x8e, 0xff, 0xeb, 0xb5, 0x93, 0xb8, 0xa7, 0x21, 0x35, 0x9e, 0xa1, 0x09, 0x02, 0x06, 0x08,
	0xe0, 0x4c, 0x92, 0x0b, 0x86, 0x61, 0xb8, 0x48, 0x1d, 0xc5, 0x35, 0x4d, 0x6c, 0x57, 0x52, 0x92,
	0x19, 0xb8, 0xd0, 0xc8, 0xd2, 0xb1, 0xa3, 0xd6, 0xb1, 0x84, 0x74, 0x6c, 0xe8, 0x23, 0x30, 0xc3,
	0x3d, 0x2f, 0xc0, 0x33, 0x71, 0xcb, 0x6b, 0x70, 0xc9, 0x9e, 0x1f, 0x39, 0x8e, 0x7f, 0xda, 0x94,
	0xe9, 0x95, 0x75, 0xf6, 0xec, 0x7e, 0xdf, 0xee, 0xa7, 0xdd, 0x95, 0xe1, 0x53, 0x37, 0x9e, 0x7c,
	0x13, 0x46, 0x81, 0x4b, 0xe3, 0x38, 0x88, 0xf6, 0x27, 0x07, 0xfb, 0x77, 0x0c, 0x75, 0x7c, 0x62,
	0x01, 0xd9, 0x8e, 0x82, 0x09, 0x8d, 0xea, 0x78, 0x65, 0xdf, 0x5e, 0x4d, 0x0e, 0x6a, 0x3b, 0x83,
	0x20, 0x18, 0x0c, 0xe9, 0xbe, 0xf0, 0xea, 0x8d, 0xfb, 0xfb, 0xcc, 0xbf, 0xa1, 0x31, 0x73, 0x6e,
	0x42, 0x19, 0x58, 0x23, 0xce, 0x98, 0x5d, 0x73, 0x54, 0xfe, 0x2b, 0x6d, 0xda, 0xcf, 0x50, 0x6c,
	0x36, 0xcc, 0x4e, 0xef, 0x25, 0x75, 0x19, 0xf9, 0x08, 0x00, 0xad, 0xfc, 0xd1, 0xf6, 0xbd, 0x6a,
	0x6a, 0x37, 0xf5, 0x45, 0xd1, 0x28, 0x2a, 0x4b, 0xcb, 0x23, 0xdb, 0x90, 0xef, 0x8d, 0xdd, 0x57,
	0x94, 0x55, 0xd3, 0xe2, 0x4a, 0x9d, 0xc8, 0x63, 0x28, 0xf4, 0xfd, 0x21, 0xe5, 0x31, 0x19, 0x79,
	0xc1, 0x8f, 0x2d, 0x4f, 0xfb, 0x2b, 0x0d, 0x85, 0xb3, 0xc0, 0xf1, 0x7e, 0x0c, 0x7a, 0x64, 0x03,
	0xd2, 0x0a, 0x33, 0x67, 0xe0, 0x13, 0xe7, 0x72, 0x5c, 0x37, 0x18, 0x8f, 0x04, 0x57, 0x5a, 0xd8,
	0x8b, 0xca, 0x82, 0x5c, 0x47, 0x90, 0x65, 0xaf, 0x43, 0x2a, 0x00, 0x37, 0x0e, 0x77, 0xea, 0xcb,
	0x6b, 0xae, 0x23, 0xb2, 0x85, 0x6e, 0x86, 0x70, 0x26, 0xdf, 0x41, 0x1e, 0xeb, 0x65, 0xe3, 0xb8,
	0x9a, 0x15, 0x61, 0x1f, 0xbf, 0x21, 0xcc, 0x14, 0x8e, 0x86, 0x0a, 0x20, 0x35, 0x78, 0x80, 0x1e,
	0x83, 0x08, 0x5d, 0xaa, 0x39, 0x91, 0xcc, 0xf4, 0x8c, 0xb0, 0xe0, 0x46, 0xd4, 0x61, 0xd4, 0xb3,
	0x1d, 0x56, 0xcd, 0xe3, 0x6d, 0xe9, 0xb0, 0x56, 0x97, 0x6a, 0xd7, 0x13, 0xb5, 0xeb, 0x56, 0xa2,
	0xb6, 0x51, 0x54, 0xde, 0xc7, 0x8c, 0x7c, 0x02, 0xeb, 0x7d, 0x07, 0xc5, 0xf0, 0x6c, 0x34, 0xc5,
	0xc1, 0xa8, 0x5a, 0x10, 0x02, 0x95, 0xa5, 0xd1, 0x10, 0x36, 0xed, 0xf7, 0x14, 0x6c, 0x99, 0x74,
	0x70, 0x43, 0x47, 0x4c, 0xa9, 0xd5, 0x08, 0x46, 0x7d, 0x7f, 0x30, 0xa7, 0x51, 0x6a, 0x5e, 0x23,
	0xbc, 0x8e, 0x65, 0xd8, 0x8c, 0x84, 0xca, 0x22, 0x24, 0xcc, 0x60, 0xe1, 0x42, 0xc1, 0xd2, 0x6a,
	0x29, 0xa6, 0x6f, 0xdf, 0xe0, 0xde, 0xda, 0x1f, 0x29, 0xd8, 0xb9, 0x9b, 0xcb, 0x95, 0xcf, 0xae,
	0x1b, 0xf1, 0xe4, 0x14, 0x13, 0xbe, 0x5f, 0x5a, 0x7b, 0xf0, 0x90, 0x8b, 0xea, 0xbb, 0xf6, 0x42,
	0x76, 0x9b, 0xf2, 0xc2, 0x9c, 0xe6, 0xf8, 0x04, 0x4a, 0x3c, 0xa3, 0xd9, 0xf6, 0x41, 0x2c, 0x57,
	0xd2, 0x61, 0x07, 0xfd, 0x8b, 0xd2, 0x74, 0xa3, 0x80, 0xdf, 0xbf, 0x93, 0x34, 0x73, 0xb8, 0xe9,
	0x39, 0x5c, 0xf2, 0x1c, 0x3b, 0xc5, 0xbd, 0xa6, 0x37, 0x0e, 0x52, 0x66, 0x50, 0x9e, 0xa3, 0x55,
	0xf2, 0x2c, 0x23, 0xaf, 0x9b, 0x22, 0xd4, 0x50, 0x10, 0x35, 0x0b, 0xf2, 0xd2, 0x42, 0x88, 0xea,
	0x5a, 0x39, 0x3a, 0xb2, 0x29, 0xb7, 0x20, 0xd7, 0xf7, 0xe9, 0xd0, 0x53, 0x43, 0x23, 0x0f, 0x64,
	0x17, 0x4a, 0x1e, 0x8d, 0xdd, 0xc8, 0x0f, 0x99, 0x8f, 0x6d, 0x21, 0xe7, 0x66, 0xd6, 0xa4, 0x5d,
	0xc3, 0x23, 0x45, 0x6e, 0x39, 0x83, 0xf7, 0x56, 0x38, 0xcf, 0xd0, 0x19, 0xc4, 0xa2, 0x6c, 0x9e,
	0x21, 0x3e, 0x6b, 0x7f, 0xa6, 0xe0, 0x61, 0x93, 0x26, 0xef, 0xdb, 0xa0, 0xbf, 0x8c, 0xb1, 0x91,
	0xc9, 0x0f, 0x50, 0xe6, 0x7b, 0xc2, 0x76, 0x83, 0x11, 0xa3, 0xbf, 0x31, 0x41, 0xc5, 0xfb, 0x5e,
	0x0a, 0x25, 0x56, 0x08, 0xea, 0x73, 0x8c, 0xbf, 0x0d, 0xe9, 0x61, 0x94, 0x9c, 0xdb, 0x03, 0x4f,
	0x64, 0x88, 0x80, 0xf6, 0xcb, 0xa0, 0x37, 0x93, 0xc8, 0x50, 0x72, 0x60, 0x22, 0x38, 0x19, 0xc8,
	0x33, 0xa6, 0x36, 0xa2, 0xc5, 0x89, 0x04, 0x39, 0xa3, 0x2c, 0x8c, 0x97, 0xd2, 0xa6, 0x9d, 0xc0,
	0xe6, 0x6c, 0x62, 0xe1, 0xf0, 0x35, 0x39, 0x80, 0x0c, 0x42, 0xaa, 0x6c, 0x56, 0xee, 0x85, 0x24,
	0x84, 0xfb, 0x6a, 0x7f, 0x67, 0x61, 0xab, 0x21, 0x46, 0xf2, 0xfd, 0x96, 0x98, 0xec, 0xa8, 0xf4,
	0xbb, 0xec, 0x28, 0x0a, 0x8f, 0x93, 0xb1, 0x98, 0xea, 0xe3, 0x8a, 0x57, 0xab, 0x26, 0xf5, 0xeb,
	0x55, 0x38, 0xcb, 0x56, 0xc4, 0xb3, 0x35, 0x63, 0x2b, 0x5e, 0xb6, 0x3a, 0x70, 0xa7, 0x7c, 0xb6,
	0xc0, 0xf3, 0xab, 0xcf, 0x8b, 0x4d, 0xda, 0x43, 0xb1, 0x66, 0x05, 0xeb, 0xb7, 0xf7, 0x63, 0x5d,
	0x58, 0x06, 0x98, 0xc0, 0x4e, 0xfc, 0x96, 0x7d, 0x81, 0x25, 0x87, 0xb2, 0x93, 0x17, 0x4a, 0xce,
	0xbd, 0xb9, 0xe4, 0x65, 0xd3, 0xc7, 0x4b, 0x0e, 0x97, 0xad, 0x84, 0x1e, 0x6c, 0x27, 0x34, 0xd8,
	0xd6, 0xb3, 0x2c, 0x72, 0x65, 0x7f, 0xf5, 0x16, 0x96, 0xd9, 0x31, 0x43, 0x92, 0x47, 0xe1, 0xa2,
	0xf9, 0x69, 0x19, 0xe0, 0x16, 0x57, 0x6b, 0x02, 0x99, 0xeb, 0xab, 0xff, 0xd7, 0xa1, 0x7b, 0x97,
	0x50, 0x50, 0x5d, 0x42, 0x4a, 0x50, 0x30, 0xf5, 0xe6, 0xb9, 0xde, 0xb6, 0x2a, 0x6b, 0xe4, 0x43,
	0xf8, 0x40, 0x1d, 0xec, 0xab, 0x96, 0xf5, 0xcc, 0x6e, 0x98, 0x97, 0xf6, 0x69, 0xeb, 0x4c, 0xaf,
	0xa4, 0x70, 0x90, 0x37, 0xba, 0x46, 0x87, 0x1f, 0xec, 0xd6, 0x79, 0xb7, 0x63, 0x58, 0x95, 0x34,
	0xd9, 0x84, 0x52, 0x62, 0xb3, 0x8e, 0x9b, 0x95, 0xcc, 0xde, 0x0b, 0x28, 0x4e, 0x3f, 0x75, 0x1c,
	0xf9, 0xa2, 0xfd, 0xbc, 0xdd, 0xb9, 0x6a, 0x23, 0x72, 0x19, 0x1e, 0xe8, 0xed, 0x17, 0x17, 0xfa,
	0x85, 0x7e, 0x82, 0x60, 0x1b, 0x00, 0x18, 0xd8, 0xd0, 0x4d, 0xb3, 0xd5, 0x6e, 0x22, 0x10, 0x40,
	0xfe, 0xf4, 0x18, 0x61, 0x4e, 0x2a, 0x19, 0xb2, 0x0e, 0xc5, 0x46, 0xe7, 0xbc, 0x7b, 0xa6, 0x5b,
	0x78, 0xcc, 0x1e, 0xfe, 0x93, 0x82, 0x32, 0xbe, 0xde, 0x6e, 0x52, 0x0b, 0xca, 0x0e, 0xb7, 0x33,
	0x4a, 0xbe, 0x5c, 0xf9, 0x9d, 0x99, 0x5f, 0x30, 0xb5, 0xcf, 0xef, 0xe3, 0x8a, 0x82, 0x6a, 0x6b,
	0xe4, 0x15, 0xac, 0xdf, 0x11, 0x9a, 0xac, 0xec, 0x98, 0x65, 0x73, 0x5e, 0xdb, 0xbb, 0xa7, 0xb7,
	0x20, 0x7b, 0xba, 0xfb, 0xd3, 0x93, 0xf9, 0xff, 0x61, 0xdf, 0xdf, 0x31, 0xf4, 0xf2, 0xe2, 0xa3,
	0x7f, 0xf4, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x29, 0x63, 0xac, 0xb0, 0x09, 0x00, 0x00,
}
