#!/bin/sh

set -e
source ./docker/functions.bash

SVC_HOME=./campaigns

run() {
	go run $SVC_HOME/cmd/campaigns-service/main.go
}

run_worker() {
  go run $SVC_HOME/cmd/campaigns-scheduled_notification_tasks-worker
}

test() {
  waiton postgres 5432

  go test $SVC_HOME/...
}

migrate() {
  waiton postgres 5432

  go run ./go/cmd/postgres-cli/main.go \
    --db-dsn=${POSTGRES_DSN} \
    --migration-path=$SVC_HOME/db/migrations
}

main $@
