// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification/v1/notification.proto

/*
Package notification is a generated protocol buffer package.

It is generated from these files:
	notification/v1/notification.proto

It has these top-level messages:
	PushEnvironment
	NotificationTapBehaviorType
	NotificationTapPresentationType
	NotificationAttachmentType
	SendCampaignNotificationRequest
	SendCampaignNotificationResponse
	NotificationItem
	ListNotificationsRequest
	ListNotificationsResponse
	GetNotificationRequest
	GetNotificationResponse
	UpdateNotificationReadStatusRequest
	UpdateNotificationReadStatusResponse
	DeleteNotificationRequest
	DeleteNotificationResponse
	Platform
	IosPlatform
	AndroidPlatform
	CreateIosPlatformRequest
	CreateIosPlatformResponse
	GetIosPlatformRequest
	GetIosPlatformResponse
	UpdateIosPlatformPushCertificateRequest
	UpdateIosPlatformPushCertificateResponse
	CreateAndroidPlatformRequest
	CreateAndroidPlatformResponse
	GetAndroidPlatformRequest
	GetAndroidPlatformResponse
	UpdateAndroidPlatformPushCredentialsRequest
	UpdateAndroidPlatformPushCredentialsResponse
*/
package notification

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import rover_auth_v1 "github.com/roverplatform/rover/apis/go/auth/v1"
import rover_protobuf "github.com/roverplatform/rover/apis/go/protobuf"
import rover_protobuf1 "github.com/roverplatform/rover/apis/go/protobuf/wrappers"
import google_protobuf "github.com/roverplatform/rover/go/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PushEnvironment_Enum int32

const (
	PushEnvironment_UNKNOWN     PushEnvironment_Enum = 0
	PushEnvironment_PRODUCTION  PushEnvironment_Enum = 1
	PushEnvironment_DEVELOPMENT PushEnvironment_Enum = 2
)

var PushEnvironment_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "PRODUCTION",
	2: "DEVELOPMENT",
}
var PushEnvironment_Enum_value = map[string]int32{
	"UNKNOWN":     0,
	"PRODUCTION":  1,
	"DEVELOPMENT": 2,
}

func (x PushEnvironment_Enum) String() string {
	return proto.EnumName(PushEnvironment_Enum_name, int32(x))
}
func (PushEnvironment_Enum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type NotificationTapBehaviorType_Enum int32

const (
	NotificationTapBehaviorType_OPEN_EXPERIENCE NotificationTapBehaviorType_Enum = 0
	NotificationTapBehaviorType_OPEN_APP        NotificationTapBehaviorType_Enum = 1
	NotificationTapBehaviorType_OPEN_DEEP_LINK  NotificationTapBehaviorType_Enum = 2
	NotificationTapBehaviorType_OPEN_WEBSITE    NotificationTapBehaviorType_Enum = 3
)

var NotificationTapBehaviorType_Enum_name = map[int32]string{
	0: "OPEN_EXPERIENCE",
	1: "OPEN_APP",
	2: "OPEN_DEEP_LINK",
	3: "OPEN_WEBSITE",
}
var NotificationTapBehaviorType_Enum_value = map[string]int32{
	"OPEN_EXPERIENCE": 0,
	"OPEN_APP":        1,
	"OPEN_DEEP_LINK":  2,
	"OPEN_WEBSITE":    3,
}

func (x NotificationTapBehaviorType_Enum) String() string {
	return proto.EnumName(NotificationTapBehaviorType_Enum_name, int32(x))
}
func (NotificationTapBehaviorType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type NotificationTapPresentationType_Enum int32

const (
	NotificationTapPresentationType_UNKNOWN    NotificationTapPresentationType_Enum = 0
	NotificationTapPresentationType_IN_APP     NotificationTapPresentationType_Enum = 1
	NotificationTapPresentationType_IN_BROWSER NotificationTapPresentationType_Enum = 2
)

var NotificationTapPresentationType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "IN_APP",
	2: "IN_BROWSER",
}
var NotificationTapPresentationType_Enum_value = map[string]int32{
	"UNKNOWN":    0,
	"IN_APP":     1,
	"IN_BROWSER": 2,
}

func (x NotificationTapPresentationType_Enum) String() string {
	return proto.EnumName(NotificationTapPresentationType_Enum_name, int32(x))
}
func (NotificationTapPresentationType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type NotificationAttachmentType_Enum int32

const (
	NotificationAttachmentType_UNKNOWN NotificationAttachmentType_Enum = 0
	NotificationAttachmentType_IMAGE   NotificationAttachmentType_Enum = 1
	NotificationAttachmentType_AUDIO   NotificationAttachmentType_Enum = 2
	NotificationAttachmentType_VIDEO   NotificationAttachmentType_Enum = 3
)

var NotificationAttachmentType_Enum_name = map[int32]string{
	0: "UNKNOWN",
	1: "IMAGE",
	2: "AUDIO",
	3: "VIDEO",
}
var NotificationAttachmentType_Enum_value = map[string]int32{
	"UNKNOWN": 0,
	"IMAGE":   1,
	"AUDIO":   2,
	"VIDEO":   3,
}

func (x NotificationAttachmentType_Enum) String() string {
	return proto.EnumName(NotificationAttachmentType_Enum_name, int32(x))
}
func (NotificationAttachmentType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type PushEnvironment struct {
}

func (m *PushEnvironment) Reset()                    { *m = PushEnvironment{} }
func (m *PushEnvironment) String() string            { return proto.CompactTextString(m) }
func (*PushEnvironment) ProtoMessage()               {}
func (*PushEnvironment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NotificationTapBehaviorType struct {
}

func (m *NotificationTapBehaviorType) Reset()                    { *m = NotificationTapBehaviorType{} }
func (m *NotificationTapBehaviorType) String() string            { return proto.CompactTextString(m) }
func (*NotificationTapBehaviorType) ProtoMessage()               {}
func (*NotificationTapBehaviorType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NotificationTapPresentationType struct {
}

func (m *NotificationTapPresentationType) Reset()                    { *m = NotificationTapPresentationType{} }
func (m *NotificationTapPresentationType) String() string            { return proto.CompactTextString(m) }
func (*NotificationTapPresentationType) ProtoMessage()               {}
func (*NotificationTapPresentationType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NotificationAttachmentType struct {
}

func (m *NotificationAttachmentType) Reset()                    { *m = NotificationAttachmentType{} }
func (m *NotificationAttachmentType) String() string            { return proto.CompactTextString(m) }
func (*NotificationAttachmentType) ProtoMessage()               {}
func (*NotificationAttachmentType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SendCampaignNotificationRequest struct {
	AuthContext                               *rover_auth_v1.AuthContext                 `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	CampaignId                                int32                                      `protobuf:"varint,2,opt,name=campaign_id,json=campaignId" json:"campaign_id,omitempty"`
	ExperienceId                              string                                     `protobuf:"bytes,3,opt,name=experience_id,json=experienceId" json:"experience_id,omitempty"`
	NotificationAttachmentUrl                 string                                     `protobuf:"bytes,10,opt,name=notification_attachment_url,json=notificationAttachmentUrl" json:"notification_attachment_url,omitempty"`
	NotificationAttachmentType                NotificationAttachmentType_Enum            `protobuf:"varint,11,opt,name=notification_attachment_type,json=notificationAttachmentType,enum=rover.notification.v1.NotificationAttachmentType_Enum" json:"notification_attachment_type,omitempty"`
	NotificationTapBehaviorType               NotificationTapBehaviorType_Enum           `protobuf:"varint,12,opt,name=notification_tap_behavior_type,json=notificationTapBehaviorType,enum=rover.notification.v1.NotificationTapBehaviorType_Enum" json:"notification_tap_behavior_type,omitempty"`
	NotificationTapBehaviorPresentationType   NotificationTapPresentationType_Enum       `protobuf:"varint,13,opt,name=notification_tap_behavior_presentation_type,json=notificationTapBehaviorPresentationType,enum=rover.notification.v1.NotificationTapPresentationType_Enum" json:"notification_tap_behavior_presentation_type,omitempty"`
	NotificationTapBehaviorUrl                string                                     `protobuf:"bytes,14,opt,name=notification_tap_behavior_url,json=notificationTapBehaviorUrl" json:"notification_tap_behavior_url,omitempty"`
	NotificationIosContentAvailable           bool                                       `protobuf:"varint,15,opt,name=notification_ios_content_available,json=notificationIosContentAvailable" json:"notification_ios_content_available,omitempty"`
	NotificationIosMutableContent             bool                                       `protobuf:"varint,16,opt,name=notification_ios_mutable_content,json=notificationIosMutableContent" json:"notification_ios_mutable_content,omitempty"`
	NotificationIosSound                      string                                     `protobuf:"bytes,17,opt,name=notification_ios_sound,json=notificationIosSound" json:"notification_ios_sound,omitempty"`
	NotificationIosCategoryIdentifier         string                                     `protobuf:"bytes,18,opt,name=notification_ios_category_identifier,json=notificationIosCategoryIdentifier" json:"notification_ios_category_identifier,omitempty"`
	NotificationIosThreadIdentifier           string                                     `protobuf:"bytes,19,opt,name=notification_ios_thread_identifier,json=notificationIosThreadIdentifier" json:"notification_ios_thread_identifier,omitempty"`
	NotificationAndroidChannelId              string                                     `protobuf:"bytes,20,opt,name=notification_android_channel_id,json=notificationAndroidChannelId" json:"notification_android_channel_id,omitempty"`
	NotificationAndroidSound                  string                                     `protobuf:"bytes,21,opt,name=notification_android_sound,json=notificationAndroidSound" json:"notification_android_sound,omitempty"`
	NotificationAndroidTag                    string                                     `protobuf:"bytes,22,opt,name=notification_android_tag,json=notificationAndroidTag" json:"notification_android_tag,omitempty"`
	NotificationExpiration                    int32                                      `protobuf:"varint,23,opt,name=notification_expiration,json=notificationExpiration" json:"notification_expiration,omitempty"`
	NotificationAttributes                    map[string]string                          `protobuf:"bytes,24,rep,name=notification_attributes,json=notificationAttributes" json:"notification_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NotificationAlertOptionPushNotification   bool                                       `protobuf:"varint,25,opt,name=notification_alert_option_push_notification,json=notificationAlertOptionPushNotification" json:"notification_alert_option_push_notification,omitempty"`
	NotificationAlertOptionNotificationCenter bool                                       `protobuf:"varint,26,opt,name=notification_alert_option_notification_center,json=notificationAlertOptionNotificationCenter" json:"notification_alert_option_notification_center,omitempty"`
	NotificationAlertOptionBadgeNumber        bool                                       `protobuf:"varint,27,opt,name=notification_alert_option_badge_number,json=notificationAlertOptionBadgeNumber" json:"notification_alert_option_badge_number,omitempty"`
	Messages                                  []*SendCampaignNotificationRequest_Message `protobuf:"bytes,30,rep,name=messages" json:"messages,omitempty"`
}

func (m *SendCampaignNotificationRequest) Reset()                    { *m = SendCampaignNotificationRequest{} }
func (m *SendCampaignNotificationRequest) String() string            { return proto.CompactTextString(m) }
func (*SendCampaignNotificationRequest) ProtoMessage()               {}
func (*SendCampaignNotificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SendCampaignNotificationRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *SendCampaignNotificationRequest) GetCampaignId() int32 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *SendCampaignNotificationRequest) GetExperienceId() string {
	if m != nil {
		return m.ExperienceId
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationAttachmentUrl() string {
	if m != nil {
		return m.NotificationAttachmentUrl
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationAttachmentType() NotificationAttachmentType_Enum {
	if m != nil {
		return m.NotificationAttachmentType
	}
	return NotificationAttachmentType_UNKNOWN
}

func (m *SendCampaignNotificationRequest) GetNotificationTapBehaviorType() NotificationTapBehaviorType_Enum {
	if m != nil {
		return m.NotificationTapBehaviorType
	}
	return NotificationTapBehaviorType_OPEN_EXPERIENCE
}

func (m *SendCampaignNotificationRequest) GetNotificationTapBehaviorPresentationType() NotificationTapPresentationType_Enum {
	if m != nil {
		return m.NotificationTapBehaviorPresentationType
	}
	return NotificationTapPresentationType_UNKNOWN
}

func (m *SendCampaignNotificationRequest) GetNotificationTapBehaviorUrl() string {
	if m != nil {
		return m.NotificationTapBehaviorUrl
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationIosContentAvailable() bool {
	if m != nil {
		return m.NotificationIosContentAvailable
	}
	return false
}

func (m *SendCampaignNotificationRequest) GetNotificationIosMutableContent() bool {
	if m != nil {
		return m.NotificationIosMutableContent
	}
	return false
}

func (m *SendCampaignNotificationRequest) GetNotificationIosSound() string {
	if m != nil {
		return m.NotificationIosSound
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationIosCategoryIdentifier() string {
	if m != nil {
		return m.NotificationIosCategoryIdentifier
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationIosThreadIdentifier() string {
	if m != nil {
		return m.NotificationIosThreadIdentifier
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationAndroidChannelId() string {
	if m != nil {
		return m.NotificationAndroidChannelId
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationAndroidSound() string {
	if m != nil {
		return m.NotificationAndroidSound
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationAndroidTag() string {
	if m != nil {
		return m.NotificationAndroidTag
	}
	return ""
}

func (m *SendCampaignNotificationRequest) GetNotificationExpiration() int32 {
	if m != nil {
		return m.NotificationExpiration
	}
	return 0
}

func (m *SendCampaignNotificationRequest) GetNotificationAttributes() map[string]string {
	if m != nil {
		return m.NotificationAttributes
	}
	return nil
}

func (m *SendCampaignNotificationRequest) GetNotificationAlertOptionPushNotification() bool {
	if m != nil {
		return m.NotificationAlertOptionPushNotification
	}
	return false
}

func (m *SendCampaignNotificationRequest) GetNotificationAlertOptionNotificationCenter() bool {
	if m != nil {
		return m.NotificationAlertOptionNotificationCenter
	}
	return false
}

func (m *SendCampaignNotificationRequest) GetNotificationAlertOptionBadgeNumber() bool {
	if m != nil {
		return m.NotificationAlertOptionBadgeNumber
	}
	return false
}

func (m *SendCampaignNotificationRequest) GetMessages() []*SendCampaignNotificationRequest_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SendCampaignNotificationRequest_Message struct {
	NotificationBody           string                      `protobuf:"bytes,1,opt,name=notification_body,json=notificationBody" json:"notification_body,omitempty"`
	NotificationTitle          string                      `protobuf:"bytes,2,opt,name=notification_title,json=notificationTitle" json:"notification_title,omitempty"`
	IsTest                     bool                        `protobuf:"varint,9,opt,name=is_test,json=isTest" json:"is_test,omitempty"`
	DeviceId                   string                      `protobuf:"bytes,10,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	DevicePushToken            string                      `protobuf:"bytes,11,opt,name=device_push_token,json=devicePushToken" json:"device_push_token,omitempty"`
	DevicePushTokenEnvironment PushEnvironment_Enum        `protobuf:"varint,12,opt,name=device_push_token_environment,json=devicePushTokenEnvironment,enum=rover.notification.v1.PushEnvironment_Enum" json:"device_push_token_environment,omitempty"`
	DeviceAppNamespace         string                      `protobuf:"bytes,13,opt,name=device_app_namespace,json=deviceAppNamespace" json:"device_app_namespace,omitempty"`
	DeviceAppBadgeNumber       *rover_protobuf1.Int32Value `protobuf:"bytes,14,opt,name=device_app_badge_number,json=deviceAppBadgeNumber" json:"device_app_badge_number,omitempty"`
	// Either "iOS" or "Android"
	OsName     string                  `protobuf:"bytes,15,opt,name=os_name,json=osName" json:"os_name,omitempty"`
	SdkVersion *rover_protobuf.Version `protobuf:"bytes,16,opt,name=sdk_version,json=sdkVersion" json:"sdk_version,omitempty"`
}

func (m *SendCampaignNotificationRequest_Message) Reset() {
	*m = SendCampaignNotificationRequest_Message{}
}
func (m *SendCampaignNotificationRequest_Message) String() string { return proto.CompactTextString(m) }
func (*SendCampaignNotificationRequest_Message) ProtoMessage()    {}
func (*SendCampaignNotificationRequest_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 1}
}

func (m *SendCampaignNotificationRequest_Message) GetNotificationBody() string {
	if m != nil {
		return m.NotificationBody
	}
	return ""
}

func (m *SendCampaignNotificationRequest_Message) GetNotificationTitle() string {
	if m != nil {
		return m.NotificationTitle
	}
	return ""
}

func (m *SendCampaignNotificationRequest_Message) GetIsTest() bool {
	if m != nil {
		return m.IsTest
	}
	return false
}

func (m *SendCampaignNotificationRequest_Message) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *SendCampaignNotificationRequest_Message) GetDevicePushToken() string {
	if m != nil {
		return m.DevicePushToken
	}
	return ""
}

func (m *SendCampaignNotificationRequest_Message) GetDevicePushTokenEnvironment() PushEnvironment_Enum {
	if m != nil {
		return m.DevicePushTokenEnvironment
	}
	return PushEnvironment_UNKNOWN
}

func (m *SendCampaignNotificationRequest_Message) GetDeviceAppNamespace() string {
	if m != nil {
		return m.DeviceAppNamespace
	}
	return ""
}

func (m *SendCampaignNotificationRequest_Message) GetDeviceAppBadgeNumber() *rover_protobuf1.Int32Value {
	if m != nil {
		return m.DeviceAppBadgeNumber
	}
	return nil
}

func (m *SendCampaignNotificationRequest_Message) GetOsName() string {
	if m != nil {
		return m.OsName
	}
	return ""
}

func (m *SendCampaignNotificationRequest_Message) GetSdkVersion() *rover_protobuf.Version {
	if m != nil {
		return m.SdkVersion
	}
	return nil
}

type SendCampaignNotificationResponse struct {
	Results []*SendCampaignNotificationResponse_Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *SendCampaignNotificationResponse) Reset()         { *m = SendCampaignNotificationResponse{} }
func (m *SendCampaignNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*SendCampaignNotificationResponse) ProtoMessage()    {}
func (*SendCampaignNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *SendCampaignNotificationResponse) GetResults() []*SendCampaignNotificationResponse_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type SendCampaignNotificationResponse_Result struct {
	// indicates if there was an error
	Error   bool   `protobuf:"varint,1,opt,name=error" json:"error,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SendCampaignNotificationResponse_Result) Reset() {
	*m = SendCampaignNotificationResponse_Result{}
}
func (m *SendCampaignNotificationResponse_Result) String() string { return proto.CompactTextString(m) }
func (*SendCampaignNotificationResponse_Result) ProtoMessage()    {}
func (*SendCampaignNotificationResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *SendCampaignNotificationResponse_Result) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *SendCampaignNotificationResponse_Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NotificationItem struct {
	Id                          string                               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CampaignId                  int32                                `protobuf:"varint,2,opt,name=campaign_id,json=campaignId" json:"campaign_id,omitempty"`
	ExperienceId                string                               `protobuf:"bytes,3,opt,name=experience_id,json=experienceId" json:"experience_id,omitempty"`
	Title                       string                               `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Body                        string                               `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	AttachmentUrl               string                               `protobuf:"bytes,6,opt,name=attachment_url,json=attachmentUrl" json:"attachment_url,omitempty"`
	AttachmentType              NotificationAttachmentType_Enum      `protobuf:"varint,7,opt,name=attachment_type,json=attachmentType,enum=rover.notification.v1.NotificationAttachmentType_Enum" json:"attachment_type,omitempty"`
	TapBehaviorUrl              string                               `protobuf:"bytes,8,opt,name=tap_behavior_url,json=tapBehaviorUrl" json:"tap_behavior_url,omitempty"`
	TapBehaviorType             NotificationTapBehaviorType_Enum     `protobuf:"varint,9,opt,name=tap_behavior_type,json=tapBehaviorType,enum=rover.notification.v1.NotificationTapBehaviorType_Enum" json:"tap_behavior_type,omitempty"`
	TapBehaviorPresentationType NotificationTapPresentationType_Enum `protobuf:"varint,10,opt,name=tap_behavior_presentation_type,json=tapBehaviorPresentationType,enum=rover.notification.v1.NotificationTapPresentationType_Enum" json:"tap_behavior_presentation_type,omitempty"`
	IsNotificationCenterEnabled bool                                 `protobuf:"varint,11,opt,name=is_notification_center_enabled,json=isNotificationCenterEnabled" json:"is_notification_center_enabled,omitempty"`
	IsRead                      bool                                 `protobuf:"varint,12,opt,name=is_read,json=isRead" json:"is_read,omitempty"`
	IsDeleted                   bool                                 `protobuf:"varint,13,opt,name=is_deleted,json=isDeleted" json:"is_deleted,omitempty"`
	CreatedAt                   *google_protobuf.Timestamp           `protobuf:"bytes,19,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *NotificationItem) Reset()                    { *m = NotificationItem{} }
func (m *NotificationItem) String() string            { return proto.CompactTextString(m) }
func (*NotificationItem) ProtoMessage()               {}
func (*NotificationItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NotificationItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NotificationItem) GetCampaignId() int32 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *NotificationItem) GetExperienceId() string {
	if m != nil {
		return m.ExperienceId
	}
	return ""
}

func (m *NotificationItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NotificationItem) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *NotificationItem) GetAttachmentUrl() string {
	if m != nil {
		return m.AttachmentUrl
	}
	return ""
}

func (m *NotificationItem) GetAttachmentType() NotificationAttachmentType_Enum {
	if m != nil {
		return m.AttachmentType
	}
	return NotificationAttachmentType_UNKNOWN
}

func (m *NotificationItem) GetTapBehaviorUrl() string {
	if m != nil {
		return m.TapBehaviorUrl
	}
	return ""
}

func (m *NotificationItem) GetTapBehaviorType() NotificationTapBehaviorType_Enum {
	if m != nil {
		return m.TapBehaviorType
	}
	return NotificationTapBehaviorType_OPEN_EXPERIENCE
}

func (m *NotificationItem) GetTapBehaviorPresentationType() NotificationTapPresentationType_Enum {
	if m != nil {
		return m.TapBehaviorPresentationType
	}
	return NotificationTapPresentationType_UNKNOWN
}

func (m *NotificationItem) GetIsNotificationCenterEnabled() bool {
	if m != nil {
		return m.IsNotificationCenterEnabled
	}
	return false
}

func (m *NotificationItem) GetIsRead() bool {
	if m != nil {
		return m.IsRead
	}
	return false
}

func (m *NotificationItem) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *NotificationItem) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type ListNotificationsRequest struct {
	AuthContext *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	DeviceId    string                     `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
}

func (m *ListNotificationsRequest) Reset()                    { *m = ListNotificationsRequest{} }
func (m *ListNotificationsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNotificationsRequest) ProtoMessage()               {}
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListNotificationsRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *ListNotificationsRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type ListNotificationsResponse struct {
	Notifications []*NotificationItem `protobuf:"bytes,1,rep,name=notifications" json:"notifications,omitempty"`
}

func (m *ListNotificationsResponse) Reset()                    { *m = ListNotificationsResponse{} }
func (m *ListNotificationsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListNotificationsResponse) ProtoMessage()               {}
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListNotificationsResponse) GetNotifications() []*NotificationItem {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type GetNotificationRequest struct {
	AuthContext    *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	DeviceId       string                     `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	NotificationId string                     `protobuf:"bytes,3,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
}

func (m *GetNotificationRequest) Reset()                    { *m = GetNotificationRequest{} }
func (m *GetNotificationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationRequest) ProtoMessage()               {}
func (*GetNotificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetNotificationRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *GetNotificationRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *GetNotificationRequest) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

type GetNotificationResponse struct {
	Notification *NotificationItem `protobuf:"bytes,1,opt,name=notification" json:"notification,omitempty"`
}

func (m *GetNotificationResponse) Reset()                    { *m = GetNotificationResponse{} }
func (m *GetNotificationResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNotificationResponse) ProtoMessage()               {}
func (*GetNotificationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetNotificationResponse) GetNotification() *NotificationItem {
	if m != nil {
		return m.Notification
	}
	return nil
}

type UpdateNotificationReadStatusRequest struct {
	AuthContext    *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	DeviceId       string                     `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	NotificationId string                     `protobuf:"bytes,3,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
	Read           bool                       `protobuf:"varint,4,opt,name=read" json:"read,omitempty"`
}

func (m *UpdateNotificationReadStatusRequest) Reset()         { *m = UpdateNotificationReadStatusRequest{} }
func (m *UpdateNotificationReadStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationReadStatusRequest) ProtoMessage()    {}
func (*UpdateNotificationReadStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11}
}

func (m *UpdateNotificationReadStatusRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *UpdateNotificationReadStatusRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *UpdateNotificationReadStatusRequest) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

func (m *UpdateNotificationReadStatusRequest) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

type UpdateNotificationReadStatusResponse struct {
}

func (m *UpdateNotificationReadStatusResponse) Reset()         { *m = UpdateNotificationReadStatusResponse{} }
func (m *UpdateNotificationReadStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationReadStatusResponse) ProtoMessage()    {}
func (*UpdateNotificationReadStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

type DeleteNotificationRequest struct {
	AuthContext    *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	DeviceId       string                     `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	NotificationId string                     `protobuf:"bytes,3,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
}

func (m *DeleteNotificationRequest) Reset()                    { *m = DeleteNotificationRequest{} }
func (m *DeleteNotificationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNotificationRequest) ProtoMessage()               {}
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteNotificationRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *DeleteNotificationRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeleteNotificationRequest) GetNotificationId() string {
	if m != nil {
		return m.NotificationId
	}
	return ""
}

type DeleteNotificationResponse struct {
}

func (m *DeleteNotificationResponse) Reset()                    { *m = DeleteNotificationResponse{} }
func (m *DeleteNotificationResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNotificationResponse) ProtoMessage()               {}
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type Platform struct {
	// Types that are valid to be assigned to Paltform:
	//	*Platform_IosPlatform
	//	*Platform_AndroidPlatform
	Paltform isPlatform_Paltform `protobuf_oneof:"paltform"`
}

func (m *Platform) Reset()                    { *m = Platform{} }
func (m *Platform) String() string            { return proto.CompactTextString(m) }
func (*Platform) ProtoMessage()               {}
func (*Platform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type isPlatform_Paltform interface{ isPlatform_Paltform() }

type Platform_IosPlatform struct {
	IosPlatform *IosPlatform `protobuf:"bytes,1,opt,name=ios_platform,json=iosPlatform,oneof"`
}
type Platform_AndroidPlatform struct {
	AndroidPlatform *AndroidPlatform `protobuf:"bytes,2,opt,name=android_platform,json=androidPlatform,oneof"`
}

func (*Platform_IosPlatform) isPlatform_Paltform()     {}
func (*Platform_AndroidPlatform) isPlatform_Paltform() {}

func (m *Platform) GetPaltform() isPlatform_Paltform {
	if m != nil {
		return m.Paltform
	}
	return nil
}

func (m *Platform) GetIosPlatform() *IosPlatform {
	if x, ok := m.GetPaltform().(*Platform_IosPlatform); ok {
		return x.IosPlatform
	}
	return nil
}

func (m *Platform) GetAndroidPlatform() *AndroidPlatform {
	if x, ok := m.GetPaltform().(*Platform_AndroidPlatform); ok {
		return x.AndroidPlatform
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Platform) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Platform_OneofMarshaler, _Platform_OneofUnmarshaler, _Platform_OneofSizer, []interface{}{
		(*Platform_IosPlatform)(nil),
		(*Platform_AndroidPlatform)(nil),
	}
}

func _Platform_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Platform)
	// paltform
	switch x := m.Paltform.(type) {
	case *Platform_IosPlatform:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IosPlatform); err != nil {
			return err
		}
	case *Platform_AndroidPlatform:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AndroidPlatform); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Platform.Paltform has unexpected type %T", x)
	}
	return nil
}

func _Platform_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Platform)
	switch tag {
	case 1: // paltform.ios_platform
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IosPlatform)
		err := b.DecodeMessage(msg)
		m.Paltform = &Platform_IosPlatform{msg}
		return true, err
	case 2: // paltform.android_platform
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AndroidPlatform)
		err := b.DecodeMessage(msg)
		m.Paltform = &Platform_AndroidPlatform{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Platform_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Platform)
	// paltform
	switch x := m.Paltform.(type) {
	case *Platform_IosPlatform:
		s := proto.Size(x.IosPlatform)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Platform_AndroidPlatform:
		s := proto.Size(x.AndroidPlatform)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IosPlatform struct {
	Id                    int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AccountId             int32                      `protobuf:"varint,2,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Title                 string                     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	BundleId              string                     `protobuf:"bytes,4,opt,name=bundle_id,json=bundleId" json:"bundle_id,omitempty"`
	CertificateData       []byte                     `protobuf:"bytes,5,opt,name=certificate_data,json=certificateData,proto3" json:"certificate_data,omitempty"`
	CertificatePassphrase string                     `protobuf:"bytes,6,opt,name=certificate_passphrase,json=certificatePassphrase" json:"certificate_passphrase,omitempty"`
	CertificateFilename   string                     `protobuf:"bytes,7,opt,name=certificate_filename,json=certificateFilename" json:"certificate_filename,omitempty"`
	CertificateExpiresAt  *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=certificate_expires_at,json=certificateExpiresAt" json:"certificate_expires_at,omitempty"`
	CertificateUpdatedAt  *google_protobuf.Timestamp `protobuf:"bytes,9,opt,name=certificate_updated_at,json=certificateUpdatedAt" json:"certificate_updated_at,omitempty"`
	UpdatedAt             *google_protobuf.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt             *google_protobuf.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *IosPlatform) Reset()                    { *m = IosPlatform{} }
func (m *IosPlatform) String() string            { return proto.CompactTextString(m) }
func (*IosPlatform) ProtoMessage()               {}
func (*IosPlatform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *IosPlatform) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IosPlatform) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *IosPlatform) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *IosPlatform) GetBundleId() string {
	if m != nil {
		return m.BundleId
	}
	return ""
}

func (m *IosPlatform) GetCertificateData() []byte {
	if m != nil {
		return m.CertificateData
	}
	return nil
}

func (m *IosPlatform) GetCertificatePassphrase() string {
	if m != nil {
		return m.CertificatePassphrase
	}
	return ""
}

func (m *IosPlatform) GetCertificateFilename() string {
	if m != nil {
		return m.CertificateFilename
	}
	return ""
}

func (m *IosPlatform) GetCertificateExpiresAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CertificateExpiresAt
	}
	return nil
}

func (m *IosPlatform) GetCertificateUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CertificateUpdatedAt
	}
	return nil
}

func (m *IosPlatform) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *IosPlatform) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type AndroidPlatform struct {
	Id                       int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AccountId                int32                      `protobuf:"varint,2,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Title                    string                     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	PushCredentialsServerKey string                     `protobuf:"bytes,5,opt,name=push_credentials_server_key,json=pushCredentialsServerKey" json:"push_credentials_server_key,omitempty"`
	PushCredentialsSenderId  string                     `protobuf:"bytes,6,opt,name=push_credentials_sender_id,json=pushCredentialsSenderId" json:"push_credentials_sender_id,omitempty"`
	PushCredentialsUpdatedAt *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=push_credentials_updated_at,json=pushCredentialsUpdatedAt" json:"push_credentials_updated_at,omitempty"`
	UpdatedAt                *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	CreatedAt                *google_protobuf.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *AndroidPlatform) Reset()                    { *m = AndroidPlatform{} }
func (m *AndroidPlatform) String() string            { return proto.CompactTextString(m) }
func (*AndroidPlatform) ProtoMessage()               {}
func (*AndroidPlatform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AndroidPlatform) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AndroidPlatform) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *AndroidPlatform) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AndroidPlatform) GetPushCredentialsServerKey() string {
	if m != nil {
		return m.PushCredentialsServerKey
	}
	return ""
}

func (m *AndroidPlatform) GetPushCredentialsSenderId() string {
	if m != nil {
		return m.PushCredentialsSenderId
	}
	return ""
}

func (m *AndroidPlatform) GetPushCredentialsUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.PushCredentialsUpdatedAt
	}
	return nil
}

func (m *AndroidPlatform) GetUpdatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *AndroidPlatform) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

//
// RPC request & response
type CreateIosPlatformRequest struct {
	AuthContext           *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	Title                 string                     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	CertificateData       []byte                     `protobuf:"bytes,5,opt,name=certificate_data,json=certificateData,proto3" json:"certificate_data,omitempty"`
	CertificatePassphrase string                     `protobuf:"bytes,6,opt,name=certificate_passphrase,json=certificatePassphrase" json:"certificate_passphrase,omitempty"`
	CertificateFilename   string                     `protobuf:"bytes,7,opt,name=certificate_filename,json=certificateFilename" json:"certificate_filename,omitempty"`
}

func (m *CreateIosPlatformRequest) Reset()                    { *m = CreateIosPlatformRequest{} }
func (m *CreateIosPlatformRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIosPlatformRequest) ProtoMessage()               {}
func (*CreateIosPlatformRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CreateIosPlatformRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *CreateIosPlatformRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateIosPlatformRequest) GetCertificateData() []byte {
	if m != nil {
		return m.CertificateData
	}
	return nil
}

func (m *CreateIosPlatformRequest) GetCertificatePassphrase() string {
	if m != nil {
		return m.CertificatePassphrase
	}
	return ""
}

func (m *CreateIosPlatformRequest) GetCertificateFilename() string {
	if m != nil {
		return m.CertificateFilename
	}
	return ""
}

type CreateIosPlatformResponse struct {
	IosPlatform *IosPlatform `protobuf:"bytes,1,opt,name=ios_platform,json=iosPlatform" json:"ios_platform,omitempty"`
}

func (m *CreateIosPlatformResponse) Reset()                    { *m = CreateIosPlatformResponse{} }
func (m *CreateIosPlatformResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateIosPlatformResponse) ProtoMessage()               {}
func (*CreateIosPlatformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CreateIosPlatformResponse) GetIosPlatform() *IosPlatform {
	if m != nil {
		return m.IosPlatform
	}
	return nil
}

type GetIosPlatformRequest struct {
	AuthContext   *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	IosPlatformId int32                      `protobuf:"varint,2,opt,name=ios_platform_id,json=iosPlatformId" json:"ios_platform_id,omitempty"`
}

func (m *GetIosPlatformRequest) Reset()                    { *m = GetIosPlatformRequest{} }
func (m *GetIosPlatformRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIosPlatformRequest) ProtoMessage()               {}
func (*GetIosPlatformRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetIosPlatformRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *GetIosPlatformRequest) GetIosPlatformId() int32 {
	if m != nil {
		return m.IosPlatformId
	}
	return 0
}

type GetIosPlatformResponse struct {
	IosPlatform *IosPlatform `protobuf:"bytes,1,opt,name=ios_platform,json=iosPlatform" json:"ios_platform,omitempty"`
}

func (m *GetIosPlatformResponse) Reset()                    { *m = GetIosPlatformResponse{} }
func (m *GetIosPlatformResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIosPlatformResponse) ProtoMessage()               {}
func (*GetIosPlatformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetIosPlatformResponse) GetIosPlatform() *IosPlatform {
	if m != nil {
		return m.IosPlatform
	}
	return nil
}

type UpdateIosPlatformPushCertificateRequest struct {
	AuthContext           *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	IosPlatformId         int32                      `protobuf:"varint,2,opt,name=ios_platform_id,json=iosPlatformId" json:"ios_platform_id,omitempty"`
	CertificateData       []byte                     `protobuf:"bytes,3,opt,name=certificate_data,json=certificateData,proto3" json:"certificate_data,omitempty"`
	CertificatePassphrase string                     `protobuf:"bytes,4,opt,name=certificate_passphrase,json=certificatePassphrase" json:"certificate_passphrase,omitempty"`
	CertificateFilename   string                     `protobuf:"bytes,5,opt,name=certificate_filename,json=certificateFilename" json:"certificate_filename,omitempty"`
}

func (m *UpdateIosPlatformPushCertificateRequest) Reset() {
	*m = UpdateIosPlatformPushCertificateRequest{}
}
func (m *UpdateIosPlatformPushCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIosPlatformPushCertificateRequest) ProtoMessage()    {}
func (*UpdateIosPlatformPushCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{22}
}

func (m *UpdateIosPlatformPushCertificateRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *UpdateIosPlatformPushCertificateRequest) GetIosPlatformId() int32 {
	if m != nil {
		return m.IosPlatformId
	}
	return 0
}

func (m *UpdateIosPlatformPushCertificateRequest) GetCertificateData() []byte {
	if m != nil {
		return m.CertificateData
	}
	return nil
}

func (m *UpdateIosPlatformPushCertificateRequest) GetCertificatePassphrase() string {
	if m != nil {
		return m.CertificatePassphrase
	}
	return ""
}

func (m *UpdateIosPlatformPushCertificateRequest) GetCertificateFilename() string {
	if m != nil {
		return m.CertificateFilename
	}
	return ""
}

type UpdateIosPlatformPushCertificateResponse struct {
	IosPlatform *IosPlatform `protobuf:"bytes,1,opt,name=ios_platform,json=iosPlatform" json:"ios_platform,omitempty"`
}

func (m *UpdateIosPlatformPushCertificateResponse) Reset() {
	*m = UpdateIosPlatformPushCertificateResponse{}
}
func (m *UpdateIosPlatformPushCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateIosPlatformPushCertificateResponse) ProtoMessage()    {}
func (*UpdateIosPlatformPushCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{23}
}

func (m *UpdateIosPlatformPushCertificateResponse) GetIosPlatform() *IosPlatform {
	if m != nil {
		return m.IosPlatform
	}
	return nil
}

type CreateAndroidPlatformRequest struct {
	AuthContext              *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	Title                    string                     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	PushCredentialsServerKey string                     `protobuf:"bytes,4,opt,name=push_credentials_server_key,json=pushCredentialsServerKey" json:"push_credentials_server_key,omitempty"`
	PushCredentialsSenderId  string                     `protobuf:"bytes,5,opt,name=push_credentials_sender_id,json=pushCredentialsSenderId" json:"push_credentials_sender_id,omitempty"`
}

func (m *CreateAndroidPlatformRequest) Reset()                    { *m = CreateAndroidPlatformRequest{} }
func (m *CreateAndroidPlatformRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAndroidPlatformRequest) ProtoMessage()               {}
func (*CreateAndroidPlatformRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *CreateAndroidPlatformRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *CreateAndroidPlatformRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateAndroidPlatformRequest) GetPushCredentialsServerKey() string {
	if m != nil {
		return m.PushCredentialsServerKey
	}
	return ""
}

func (m *CreateAndroidPlatformRequest) GetPushCredentialsSenderId() string {
	if m != nil {
		return m.PushCredentialsSenderId
	}
	return ""
}

type CreateAndroidPlatformResponse struct {
	AndroidPlatform *AndroidPlatform `protobuf:"bytes,1,opt,name=android_platform,json=androidPlatform" json:"android_platform,omitempty"`
}

func (m *CreateAndroidPlatformResponse) Reset()                    { *m = CreateAndroidPlatformResponse{} }
func (m *CreateAndroidPlatformResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAndroidPlatformResponse) ProtoMessage()               {}
func (*CreateAndroidPlatformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *CreateAndroidPlatformResponse) GetAndroidPlatform() *AndroidPlatform {
	if m != nil {
		return m.AndroidPlatform
	}
	return nil
}

type GetAndroidPlatformRequest struct {
	AuthContext       *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	AndroidPlatformId int32                      `protobuf:"varint,2,opt,name=android_platform_id,json=androidPlatformId" json:"android_platform_id,omitempty"`
}

func (m *GetAndroidPlatformRequest) Reset()                    { *m = GetAndroidPlatformRequest{} }
func (m *GetAndroidPlatformRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAndroidPlatformRequest) ProtoMessage()               {}
func (*GetAndroidPlatformRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetAndroidPlatformRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *GetAndroidPlatformRequest) GetAndroidPlatformId() int32 {
	if m != nil {
		return m.AndroidPlatformId
	}
	return 0
}

type GetAndroidPlatformResponse struct {
	AndroidPlatform *AndroidPlatform `protobuf:"bytes,1,opt,name=android_platform,json=androidPlatform" json:"android_platform,omitempty"`
}

func (m *GetAndroidPlatformResponse) Reset()                    { *m = GetAndroidPlatformResponse{} }
func (m *GetAndroidPlatformResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAndroidPlatformResponse) ProtoMessage()               {}
func (*GetAndroidPlatformResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *GetAndroidPlatformResponse) GetAndroidPlatform() *AndroidPlatform {
	if m != nil {
		return m.AndroidPlatform
	}
	return nil
}

type UpdateAndroidPlatformPushCredentialsRequest struct {
	AuthContext              *rover_auth_v1.AuthContext `protobuf:"bytes,1,opt,name=auth_context,json=authContext" json:"auth_context,omitempty"`
	AndroidPlatformId        int32                      `protobuf:"varint,2,opt,name=android_platform_id,json=androidPlatformId" json:"android_platform_id,omitempty"`
	PushCredentialsServerKey string                     `protobuf:"bytes,3,opt,name=push_credentials_server_key,json=pushCredentialsServerKey" json:"push_credentials_server_key,omitempty"`
	PushCredentialsSenderId  string                     `protobuf:"bytes,4,opt,name=push_credentials_sender_id,json=pushCredentialsSenderId" json:"push_credentials_sender_id,omitempty"`
}

func (m *UpdateAndroidPlatformPushCredentialsRequest) Reset() {
	*m = UpdateAndroidPlatformPushCredentialsRequest{}
}
func (m *UpdateAndroidPlatformPushCredentialsRequest) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateAndroidPlatformPushCredentialsRequest) ProtoMessage() {}
func (*UpdateAndroidPlatformPushCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{28}
}

func (m *UpdateAndroidPlatformPushCredentialsRequest) GetAuthContext() *rover_auth_v1.AuthContext {
	if m != nil {
		return m.AuthContext
	}
	return nil
}

func (m *UpdateAndroidPlatformPushCredentialsRequest) GetAndroidPlatformId() int32 {
	if m != nil {
		return m.AndroidPlatformId
	}
	return 0
}

func (m *UpdateAndroidPlatformPushCredentialsRequest) GetPushCredentialsServerKey() string {
	if m != nil {
		return m.PushCredentialsServerKey
	}
	return ""
}

func (m *UpdateAndroidPlatformPushCredentialsRequest) GetPushCredentialsSenderId() string {
	if m != nil {
		return m.PushCredentialsSenderId
	}
	return ""
}

type UpdateAndroidPlatformPushCredentialsResponse struct {
	AndroidPlatform *AndroidPlatform `protobuf:"bytes,1,opt,name=android_platform,json=androidPlatform" json:"android_platform,omitempty"`
}

func (m *UpdateAndroidPlatformPushCredentialsResponse) Reset() {
	*m = UpdateAndroidPlatformPushCredentialsResponse{}
}
func (m *UpdateAndroidPlatformPushCredentialsResponse) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateAndroidPlatformPushCredentialsResponse) ProtoMessage() {}
func (*UpdateAndroidPlatformPushCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{29}
}

func (m *UpdateAndroidPlatformPushCredentialsResponse) GetAndroidPlatform() *AndroidPlatform {
	if m != nil {
		return m.AndroidPlatform
	}
	return nil
}

func init() {
	proto.RegisterType((*PushEnvironment)(nil), "rover.notification.v1.PushEnvironment")
	proto.RegisterType((*NotificationTapBehaviorType)(nil), "rover.notification.v1.NotificationTapBehaviorType")
	proto.RegisterType((*NotificationTapPresentationType)(nil), "rover.notification.v1.NotificationTapPresentationType")
	proto.RegisterType((*NotificationAttachmentType)(nil), "rover.notification.v1.NotificationAttachmentType")
	proto.RegisterType((*SendCampaignNotificationRequest)(nil), "rover.notification.v1.SendCampaignNotificationRequest")
	proto.RegisterType((*SendCampaignNotificationRequest_Message)(nil), "rover.notification.v1.SendCampaignNotificationRequest.Message")
	proto.RegisterType((*SendCampaignNotificationResponse)(nil), "rover.notification.v1.SendCampaignNotificationResponse")
	proto.RegisterType((*SendCampaignNotificationResponse_Result)(nil), "rover.notification.v1.SendCampaignNotificationResponse.Result")
	proto.RegisterType((*NotificationItem)(nil), "rover.notification.v1.NotificationItem")
	proto.RegisterType((*ListNotificationsRequest)(nil), "rover.notification.v1.ListNotificationsRequest")
	proto.RegisterType((*ListNotificationsResponse)(nil), "rover.notification.v1.ListNotificationsResponse")
	proto.RegisterType((*GetNotificationRequest)(nil), "rover.notification.v1.GetNotificationRequest")
	proto.RegisterType((*GetNotificationResponse)(nil), "rover.notification.v1.GetNotificationResponse")
	proto.RegisterType((*UpdateNotificationReadStatusRequest)(nil), "rover.notification.v1.UpdateNotificationReadStatusRequest")
	proto.RegisterType((*UpdateNotificationReadStatusResponse)(nil), "rover.notification.v1.UpdateNotificationReadStatusResponse")
	proto.RegisterType((*DeleteNotificationRequest)(nil), "rover.notification.v1.DeleteNotificationRequest")
	proto.RegisterType((*DeleteNotificationResponse)(nil), "rover.notification.v1.DeleteNotificationResponse")
	proto.RegisterType((*Platform)(nil), "rover.notification.v1.Platform")
	proto.RegisterType((*IosPlatform)(nil), "rover.notification.v1.IosPlatform")
	proto.RegisterType((*AndroidPlatform)(nil), "rover.notification.v1.AndroidPlatform")
	proto.RegisterType((*CreateIosPlatformRequest)(nil), "rover.notification.v1.CreateIosPlatformRequest")
	proto.RegisterType((*CreateIosPlatformResponse)(nil), "rover.notification.v1.CreateIosPlatformResponse")
	proto.RegisterType((*GetIosPlatformRequest)(nil), "rover.notification.v1.GetIosPlatformRequest")
	proto.RegisterType((*GetIosPlatformResponse)(nil), "rover.notification.v1.GetIosPlatformResponse")
	proto.RegisterType((*UpdateIosPlatformPushCertificateRequest)(nil), "rover.notification.v1.UpdateIosPlatformPushCertificateRequest")
	proto.RegisterType((*UpdateIosPlatformPushCertificateResponse)(nil), "rover.notification.v1.UpdateIosPlatformPushCertificateResponse")
	proto.RegisterType((*CreateAndroidPlatformRequest)(nil), "rover.notification.v1.CreateAndroidPlatformRequest")
	proto.RegisterType((*CreateAndroidPlatformResponse)(nil), "rover.notification.v1.CreateAndroidPlatformResponse")
	proto.RegisterType((*GetAndroidPlatformRequest)(nil), "rover.notification.v1.GetAndroidPlatformRequest")
	proto.RegisterType((*GetAndroidPlatformResponse)(nil), "rover.notification.v1.GetAndroidPlatformResponse")
	proto.RegisterType((*UpdateAndroidPlatformPushCredentialsRequest)(nil), "rover.notification.v1.UpdateAndroidPlatformPushCredentialsRequest")
	proto.RegisterType((*UpdateAndroidPlatformPushCredentialsResponse)(nil), "rover.notification.v1.UpdateAndroidPlatformPushCredentialsResponse")
	proto.RegisterEnum("rover.notification.v1.PushEnvironment_Enum", PushEnvironment_Enum_name, PushEnvironment_Enum_value)
	proto.RegisterEnum("rover.notification.v1.NotificationTapBehaviorType_Enum", NotificationTapBehaviorType_Enum_name, NotificationTapBehaviorType_Enum_value)
	proto.RegisterEnum("rover.notification.v1.NotificationTapPresentationType_Enum", NotificationTapPresentationType_Enum_name, NotificationTapPresentationType_Enum_value)
	proto.RegisterEnum("rover.notification.v1.NotificationAttachmentType_Enum", NotificationAttachmentType_Enum_name, NotificationAttachmentType_Enum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Notification service

type NotificationClient interface {
	SendCampaignNotification(ctx context.Context, in *SendCampaignNotificationRequest, opts ...grpc.CallOption) (*SendCampaignNotificationResponse, error)
	//
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error)
	UpdateNotificationReadStatus(ctx context.Context, in *UpdateNotificationReadStatusRequest, opts ...grpc.CallOption) (*UpdateNotificationReadStatusResponse, error)
	DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error)
	// rpc ListIosPlatforms(ListIosPlatformsRequest) returns (ListIosPlatformsResponse);
	GetIosPlatform(ctx context.Context, in *GetIosPlatformRequest, opts ...grpc.CallOption) (*GetIosPlatformResponse, error)
	CreateIosPlatform(ctx context.Context, in *CreateIosPlatformRequest, opts ...grpc.CallOption) (*CreateIosPlatformResponse, error)
	UpdateIosPlatformPushCertificate(ctx context.Context, in *UpdateIosPlatformPushCertificateRequest, opts ...grpc.CallOption) (*UpdateIosPlatformPushCertificateResponse, error)
	// rpc ListAndroidPlatform(ListAndroidPlatformRequest) returns(ListAndroidPlatformResponse);
	CreateAndroidPlatform(ctx context.Context, in *CreateAndroidPlatformRequest, opts ...grpc.CallOption) (*CreateAndroidPlatformResponse, error)
	GetAndroidPlatform(ctx context.Context, in *GetAndroidPlatformRequest, opts ...grpc.CallOption) (*GetAndroidPlatformResponse, error)
	UpdateAndroidPlatformPushCredentials(ctx context.Context, in *UpdateAndroidPlatformPushCredentialsRequest, opts ...grpc.CallOption) (*UpdateAndroidPlatformPushCredentialsResponse, error)
}

type notificationClient struct {
	cc *grpc.ClientConn
}

func NewNotificationClient(cc *grpc.ClientConn) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) SendCampaignNotification(ctx context.Context, in *SendCampaignNotificationRequest, opts ...grpc.CallOption) (*SendCampaignNotificationResponse, error) {
	out := new(SendCampaignNotificationResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/SendCampaignNotification", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	out := new(ListNotificationsResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/ListNotifications", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) GetNotification(ctx context.Context, in *GetNotificationRequest, opts ...grpc.CallOption) (*GetNotificationResponse, error) {
	out := new(GetNotificationResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/GetNotification", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) UpdateNotificationReadStatus(ctx context.Context, in *UpdateNotificationReadStatusRequest, opts ...grpc.CallOption) (*UpdateNotificationReadStatusResponse, error) {
	out := new(UpdateNotificationReadStatusResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/UpdateNotificationReadStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) DeleteNotification(ctx context.Context, in *DeleteNotificationRequest, opts ...grpc.CallOption) (*DeleteNotificationResponse, error) {
	out := new(DeleteNotificationResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/DeleteNotification", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) GetIosPlatform(ctx context.Context, in *GetIosPlatformRequest, opts ...grpc.CallOption) (*GetIosPlatformResponse, error) {
	out := new(GetIosPlatformResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/GetIosPlatform", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) CreateIosPlatform(ctx context.Context, in *CreateIosPlatformRequest, opts ...grpc.CallOption) (*CreateIosPlatformResponse, error) {
	out := new(CreateIosPlatformResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/CreateIosPlatform", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) UpdateIosPlatformPushCertificate(ctx context.Context, in *UpdateIosPlatformPushCertificateRequest, opts ...grpc.CallOption) (*UpdateIosPlatformPushCertificateResponse, error) {
	out := new(UpdateIosPlatformPushCertificateResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/UpdateIosPlatformPushCertificate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) CreateAndroidPlatform(ctx context.Context, in *CreateAndroidPlatformRequest, opts ...grpc.CallOption) (*CreateAndroidPlatformResponse, error) {
	out := new(CreateAndroidPlatformResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/CreateAndroidPlatform", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) GetAndroidPlatform(ctx context.Context, in *GetAndroidPlatformRequest, opts ...grpc.CallOption) (*GetAndroidPlatformResponse, error) {
	out := new(GetAndroidPlatformResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/GetAndroidPlatform", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) UpdateAndroidPlatformPushCredentials(ctx context.Context, in *UpdateAndroidPlatformPushCredentialsRequest, opts ...grpc.CallOption) (*UpdateAndroidPlatformPushCredentialsResponse, error) {
	out := new(UpdateAndroidPlatformPushCredentialsResponse)
	err := grpc.Invoke(ctx, "/rover.notification.v1.Notification/UpdateAndroidPlatformPushCredentials", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notification service

type NotificationServer interface {
	SendCampaignNotification(context.Context, *SendCampaignNotificationRequest) (*SendCampaignNotificationResponse, error)
	//
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	GetNotification(context.Context, *GetNotificationRequest) (*GetNotificationResponse, error)
	UpdateNotificationReadStatus(context.Context, *UpdateNotificationReadStatusRequest) (*UpdateNotificationReadStatusResponse, error)
	DeleteNotification(context.Context, *DeleteNotificationRequest) (*DeleteNotificationResponse, error)
	// rpc ListIosPlatforms(ListIosPlatformsRequest) returns (ListIosPlatformsResponse);
	GetIosPlatform(context.Context, *GetIosPlatformRequest) (*GetIosPlatformResponse, error)
	CreateIosPlatform(context.Context, *CreateIosPlatformRequest) (*CreateIosPlatformResponse, error)
	UpdateIosPlatformPushCertificate(context.Context, *UpdateIosPlatformPushCertificateRequest) (*UpdateIosPlatformPushCertificateResponse, error)
	// rpc ListAndroidPlatform(ListAndroidPlatformRequest) returns(ListAndroidPlatformResponse);
	CreateAndroidPlatform(context.Context, *CreateAndroidPlatformRequest) (*CreateAndroidPlatformResponse, error)
	GetAndroidPlatform(context.Context, *GetAndroidPlatformRequest) (*GetAndroidPlatformResponse, error)
	UpdateAndroidPlatformPushCredentials(context.Context, *UpdateAndroidPlatformPushCredentialsRequest) (*UpdateAndroidPlatformPushCredentialsResponse, error)
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_SendCampaignNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCampaignNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).SendCampaignNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/SendCampaignNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).SendCampaignNotification(ctx, req.(*SendCampaignNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/ListNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_GetNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).GetNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/GetNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).GetNotification(ctx, req.(*GetNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_UpdateNotificationReadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationReadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).UpdateNotificationReadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/UpdateNotificationReadStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).UpdateNotificationReadStatus(ctx, req.(*UpdateNotificationReadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_DeleteNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).DeleteNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/DeleteNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).DeleteNotification(ctx, req.(*DeleteNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_GetIosPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIosPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).GetIosPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/GetIosPlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).GetIosPlatform(ctx, req.(*GetIosPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_CreateIosPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIosPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CreateIosPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/CreateIosPlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CreateIosPlatform(ctx, req.(*CreateIosPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_UpdateIosPlatformPushCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIosPlatformPushCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).UpdateIosPlatformPushCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/UpdateIosPlatformPushCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).UpdateIosPlatformPushCertificate(ctx, req.(*UpdateIosPlatformPushCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_CreateAndroidPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAndroidPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).CreateAndroidPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/CreateAndroidPlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).CreateAndroidPlatform(ctx, req.(*CreateAndroidPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_GetAndroidPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAndroidPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).GetAndroidPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/GetAndroidPlatform",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).GetAndroidPlatform(ctx, req.(*GetAndroidPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_UpdateAndroidPlatformPushCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAndroidPlatformPushCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).UpdateAndroidPlatformPushCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rover.notification.v1.Notification/UpdateAndroidPlatformPushCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).UpdateAndroidPlatformPushCredentials(ctx, req.(*UpdateAndroidPlatformPushCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rover.notification.v1.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCampaignNotification",
			Handler:    _Notification_SendCampaignNotification_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _Notification_ListNotifications_Handler,
		},
		{
			MethodName: "GetNotification",
			Handler:    _Notification_GetNotification_Handler,
		},
		{
			MethodName: "UpdateNotificationReadStatus",
			Handler:    _Notification_UpdateNotificationReadStatus_Handler,
		},
		{
			MethodName: "DeleteNotification",
			Handler:    _Notification_DeleteNotification_Handler,
		},
		{
			MethodName: "GetIosPlatform",
			Handler:    _Notification_GetIosPlatform_Handler,
		},
		{
			MethodName: "CreateIosPlatform",
			Handler:    _Notification_CreateIosPlatform_Handler,
		},
		{
			MethodName: "UpdateIosPlatformPushCertificate",
			Handler:    _Notification_UpdateIosPlatformPushCertificate_Handler,
		},
		{
			MethodName: "CreateAndroidPlatform",
			Handler:    _Notification_CreateAndroidPlatform_Handler,
		},
		{
			MethodName: "GetAndroidPlatform",
			Handler:    _Notification_GetAndroidPlatform_Handler,
		},
		{
			MethodName: "UpdateAndroidPlatformPushCredentials",
			Handler:    _Notification_UpdateAndroidPlatformPushCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/notification.proto",
}

func init() { proto.RegisterFile("notification/v1/notification.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x5a, 0xdd, 0x73, 0xdb, 0x58,
	0x15, 0xaf, 0x9c, 0x2f, 0xfb, 0x38, 0xb5, 0x9d, 0xdb, 0x34, 0x51, 0x94, 0xa6, 0x09, 0xda, 0xa5,
	0xcd, 0xd2, 0xad, 0xb3, 0x4d, 0xcb, 0xb6, 0x6c, 0xd9, 0x32, 0x8e, 0x23, 0x82, 0xa6, 0xad, 0xed,
	0x55, 0xdc, 0x76, 0xd9, 0x61, 0x46, 0xdc, 0x58, 0xb7, 0x89, 0xa8, 0x2d, 0x69, 0xa5, 0x6b, 0xd3,
	0xcc, 0x30, 0x0c, 0x30, 0x3c, 0xb1, 0x0f, 0x3c, 0x02, 0x0f, 0x30, 0xcc, 0xec, 0xf0, 0xcc, 0x0b,
	0xc3, 0x23, 0x7f, 0x08, 0xcf, 0xbc, 0xf3, 0xce, 0x13, 0xa3, 0x7b, 0x65, 0x5b, 0x92, 0x25, 0x27,
	0x71, 0x12, 0xe8, 0x53, 0x7c, 0xef, 0x39, 0xe7, 0x77, 0xce, 0x3d, 0xf7, 0x7c, 0x5d, 0x4d, 0x40,
	0xb6, 0x6c, 0x6a, 0xbe, 0x36, 0x5b, 0x98, 0x9a, 0xb6, 0xb5, 0xd5, 0xbb, 0xb7, 0x15, 0x5e, 0x97,
	0x1d, 0xd7, 0xa6, 0x36, 0xba, 0xee, 0xda, 0x3d, 0xe2, 0x96, 0x23, 0x94, 0xde, 0x3d, 0x09, 0xe1,
	0x2e, 0x3d, 0xf2, 0x45, 0xfc, 0xbf, 0x9c, 0x55, 0x5a, 0x62, 0x7f, 0x0e, 0xba, 0xaf, 0xb7, 0x7a,
	0xc4, 0xf5, 0x06, 0x10, 0xd2, 0xf2, 0x60, 0xff, 0xa7, 0x2e, 0x76, 0x1c, 0xe2, 0x7a, 0x01, 0x61,
	0xfd, 0xd0, 0xb6, 0x0f, 0xdb, 0x64, 0x6b, 0x40, 0xa7, 0x66, 0x87, 0x78, 0x14, 0x77, 0x1c, 0xce,
	0x20, 0xef, 0x41, 0xb1, 0xd1, 0xf5, 0x8e, 0x14, 0xab, 0x67, 0xba, 0xb6, 0xd5, 0x21, 0x16, 0x95,
	0x1f, 0xc0, 0xb4, 0x62, 0x75, 0x3b, 0x28, 0x0f, 0x73, 0x2f, 0x6a, 0x4f, 0x6b, 0xf5, 0x57, 0xb5,
	0xd2, 0x15, 0x54, 0x00, 0x68, 0x68, 0xf5, 0xdd, 0x17, 0xd5, 0xa6, 0x5a, 0xaf, 0x95, 0x04, 0x54,
	0x84, 0xfc, 0xae, 0xf2, 0x52, 0x79, 0x56, 0x6f, 0x3c, 0x57, 0x6a, 0xcd, 0x52, 0x46, 0xb6, 0x60,
	0xb5, 0x16, 0x3a, 0x41, 0x13, 0x3b, 0x3b, 0xe4, 0x08, 0xf7, 0x4c, 0xdb, 0x6d, 0x1e, 0x3b, 0x44,
	0xae, 0x07, 0xa0, 0xd7, 0xa0, 0x58, 0x6f, 0x28, 0x35, 0x5d, 0xf9, 0xbc, 0xa1, 0x68, 0xaa, 0x52,
	0xab, 0x2a, 0xa5, 0x2b, 0x68, 0x1e, 0xb2, 0x6c, 0xb3, 0xd2, 0x68, 0x94, 0x04, 0x84, 0xa0, 0xc0,
	0x56, 0xbb, 0x8a, 0xd2, 0xd0, 0x9f, 0xa9, 0xb5, 0xa7, 0xa5, 0x0c, 0x2a, 0xc1, 0x3c, 0xdb, 0x7b,
	0xa5, 0xec, 0xec, 0xab, 0x4d, 0xa5, 0x34, 0x25, 0x6b, 0xb0, 0x1e, 0xd3, 0xd7, 0x70, 0x89, 0x47,
	0x2c, 0xca, 0x97, 0xbe, 0xce, 0xad, 0xa4, 0x83, 0x00, 0xcc, 0xaa, 0x7d, 0x4d, 0x05, 0x00, 0xb5,
	0xa6, 0xef, 0x68, 0xf5, 0x57, 0xfb, 0x8a, 0x56, 0xca, 0xc8, 0x1a, 0x48, 0x61, 0xcc, 0x0a, 0xa5,
	0xb8, 0x75, 0xe4, 0xfb, 0x84, 0xc1, 0x25, 0xfa, 0x25, 0x07, 0x33, 0xea, 0xf3, 0xca, 0x9e, 0x52,
	0x12, 0xfc, 0x9f, 0x95, 0x17, 0xbb, 0x6a, 0xbd, 0x94, 0xf1, 0x7f, 0xbe, 0x54, 0x77, 0x95, 0x7a,
	0x69, 0x4a, 0xfe, 0x0f, 0x82, 0xf5, 0x7d, 0x62, 0x19, 0x55, 0xdc, 0x71, 0xb0, 0x79, 0x68, 0x85,
	0x15, 0x68, 0xe4, 0xcb, 0x2e, 0xf1, 0x28, 0xfa, 0x14, 0xe6, 0xfd, 0x4b, 0xd6, 0x5b, 0xb6, 0x45,
	0xc9, 0x5b, 0x2a, 0x0a, 0x1b, 0xc2, 0x66, 0x7e, 0x5b, 0x2a, 0xf3, 0xc0, 0x60, 0xf7, 0xdf, 0xbb,
	0x57, 0xae, 0x74, 0xe9, 0x51, 0x95, 0x73, 0x68, 0x79, 0x3c, 0x5c, 0xa0, 0x75, 0xc8, 0xb7, 0x02,
	0x74, 0xdd, 0x34, 0xc4, 0xcc, 0x86, 0xb0, 0x39, 0xa3, 0x41, 0x7f, 0x4b, 0x35, 0xd0, 0x7b, 0x70,
	0x95, 0xbc, 0x75, 0x88, 0x6b, 0x12, 0xab, 0x45, 0x7c, 0x96, 0xa9, 0x0d, 0x61, 0x33, 0xa7, 0xcd,
	0x0f, 0x37, 0x55, 0x03, 0x3d, 0x81, 0xd5, 0x70, 0x08, 0xea, 0x78, 0x70, 0x7a, 0xbd, 0xeb, 0xb6,
	0x45, 0x60, 0x22, 0x2b, 0x56, 0xa2, 0x7f, 0x5e, 0xb8, 0x6d, 0xf4, 0x16, 0x6e, 0xa4, 0xc9, 0xd3,
	0x63, 0x87, 0x88, 0xf9, 0x0d, 0x61, 0xb3, 0xb0, 0xfd, 0x71, 0x39, 0x31, 0xda, 0xcb, 0xe9, 0x7e,
	0x2f, 0xfb, 0x4e, 0xd7, 0x24, 0x2b, 0x95, 0x01, 0xfd, 0x0c, 0x6e, 0x46, 0x34, 0x53, 0xec, 0xe8,
	0x07, 0x41, 0xf0, 0x71, 0xdd, 0xf3, 0x4c, 0xf7, 0xc3, 0x53, 0xe8, 0x8e, 0xc5, 0x2d, 0x57, 0x1e,
	0x71, 0x4c, 0x8c, 0x03, 0xfd, 0x41, 0x80, 0x3b, 0xe9, 0xea, 0x9d, 0x50, 0x50, 0x72, 0x5b, 0xae,
	0x32, 0x5b, 0x1e, 0x9f, 0xce, 0x96, 0x78, 0x4c, 0x73, 0x7b, 0x6e, 0xa7, 0xd8, 0x13, 0xe7, 0x46,
	0x15, 0x58, 0x4b, 0x37, 0xcd, 0xbf, 0xd5, 0x02, 0xbb, 0x55, 0x29, 0x05, 0xcf, 0xbf, 0xd6, 0xa7,
	0xd1, 0x1a, 0xa6, 0x9b, 0xb6, 0xc7, 0xe3, 0xd4, 0xa2, 0x3a, 0xee, 0x61, 0xb3, 0x8d, 0x0f, 0xda,
	0x44, 0x2c, 0x6e, 0x08, 0x9b, 0x59, 0x6d, 0x3d, 0xcc, 0xa9, 0xda, 0x5e, 0x95, 0xf3, 0x55, 0xfa,
	0x6c, 0x68, 0x0f, 0x36, 0x46, 0xc0, 0x3a, 0x5d, 0xea, 0xd3, 0xfa, 0xa0, 0x62, 0x89, 0x41, 0xad,
	0xc5, 0xa0, 0x9e, 0x73, 0xae, 0x00, 0x11, 0x3d, 0x80, 0xa5, 0x11, 0x20, 0xcf, 0xee, 0x5a, 0x86,
	0xb8, 0xc0, 0x4e, 0xb4, 0x18, 0x13, 0xdf, 0xf7, 0x69, 0xa8, 0x0e, 0xef, 0x8f, 0x9e, 0x05, 0x53,
	0x72, 0x68, 0xbb, 0xc7, 0xba, 0x69, 0x10, 0xcb, 0xa7, 0x11, 0x57, 0x44, 0x0c, 0xe3, 0x1b, 0xf1,
	0xd3, 0x04, 0x9c, 0xea, 0x80, 0x31, 0xd1, 0x39, 0xf4, 0xc8, 0x25, 0xd8, 0x08, 0xc3, 0x5d, 0x63,
	0x70, 0x71, 0xe7, 0x34, 0x19, 0x5f, 0x08, 0x4c, 0x81, 0xf5, 0x68, 0x02, 0x59, 0x86, 0x6b, 0x9b,
	0x86, 0xde, 0x3a, 0xc2, 0x96, 0x45, 0xda, 0x7e, 0xde, 0x2e, 0x32, 0xa4, 0x48, 0x9e, 0x55, 0x38,
	0x57, 0x95, 0x33, 0xa9, 0x06, 0xfa, 0x2e, 0x48, 0x89, 0x30, 0xdc, 0x3d, 0xd7, 0x19, 0x82, 0x98,
	0x80, 0xc0, 0x5d, 0xf4, 0x08, 0xc4, 0x44, 0x69, 0x8a, 0x0f, 0xc5, 0x25, 0x26, 0xbb, 0x94, 0x20,
	0xdb, 0xc4, 0x87, 0xe8, 0x21, 0x2c, 0x47, 0x24, 0xc9, 0x5b, 0xc7, 0x74, 0xd9, 0x4f, 0x71, 0x99,
	0x55, 0xa4, 0x88, 0xa0, 0x32, 0xa0, 0xa2, 0xaf, 0x84, 0x98, 0x24, 0xa6, 0xd4, 0x35, 0x0f, 0xba,
	0x94, 0x78, 0xa2, 0xb8, 0x31, 0xb5, 0x99, 0xdf, 0xd6, 0x52, 0x92, 0xe5, 0x84, 0xba, 0x1a, 0x2f,
	0x2a, 0x01, 0xa8, 0x62, 0x51, 0xf7, 0x38, 0x76, 0x8c, 0x01, 0x11, 0xfd, 0x28, 0x96, 0xcd, 0xb8,
	0x4d, 0x5c, 0xaa, 0xdb, 0x0e, 0x5b, 0x38, 0x5d, 0xef, 0x48, 0x0f, 0x93, 0xc5, 0x15, 0x16, 0xad,
	0x91, 0x84, 0xac, 0xf8, 0x12, 0x75, 0x26, 0xe0, 0xb7, 0xd6, 0xb0, 0x11, 0xe8, 0xc7, 0x70, 0x37,
	0x1d, 0x3d, 0x42, 0x69, 0x11, 0x8b, 0x12, 0x57, 0x94, 0x18, 0xfe, 0x07, 0x29, 0xf8, 0x61, 0xec,
	0x2a, 0x13, 0x40, 0x1a, 0xdc, 0x4a, 0xd7, 0x70, 0x80, 0x8d, 0x43, 0xa2, 0x5b, 0xdd, 0xce, 0x01,
	0x71, 0xc5, 0x55, 0x06, 0x2d, 0xa7, 0x40, 0xef, 0xf8, 0xac, 0x35, 0xc6, 0x89, 0xbe, 0x80, 0x6c,
	0x87, 0x78, 0x1e, 0x3e, 0x24, 0x9e, 0x78, 0x93, 0xdd, 0xc8, 0x93, 0x09, 0x6f, 0xe4, 0x39, 0x87,
	0xd1, 0x06, 0x78, 0x92, 0x1a, 0x9d, 0x1b, 0x62, 0xd7, 0x84, 0x4a, 0x30, 0xf5, 0x86, 0x1c, 0xb3,
	0x8e, 0x98, 0xd3, 0xfc, 0x9f, 0x68, 0x11, 0x66, 0x7a, 0xb8, 0xdd, 0x25, 0xac, 0xcf, 0xe5, 0x34,
	0xbe, 0xf8, 0x24, 0xf3, 0x48, 0x90, 0x7e, 0x3b, 0x0d, 0x73, 0x81, 0x02, 0x74, 0x07, 0x16, 0x22,
	0x6e, 0x38, 0xb0, 0x8d, 0x3e, 0x4a, 0x29, 0x4c, 0xd8, 0xb1, 0x8d, 0x63, 0x74, 0x17, 0x50, 0xb4,
	0x4c, 0x9a, 0xb4, 0xdd, 0xc7, 0x8f, 0xc0, 0x34, 0x7d, 0x02, 0x5a, 0x86, 0x39, 0xd3, 0xd3, 0x29,
	0xf1, 0xa8, 0x98, 0x63, 0x3e, 0x9c, 0x35, 0xbd, 0xa6, 0xdf, 0xc7, 0x57, 0x21, 0x67, 0x90, 0x9e,
	0xc9, 0x7b, 0x2c, 0x6f, 0x98, 0x59, 0xbe, 0xa1, 0x1a, 0xe8, 0x5b, 0xb0, 0x10, 0x10, 0x59, 0x14,
	0x51, 0xfb, 0x0d, 0xb1, 0x58, 0x53, 0xcc, 0x69, 0x45, 0x4e, 0xf0, 0xa3, 0xa5, 0xe9, 0x6f, 0x23,
	0x0b, 0xd6, 0x46, 0x78, 0x75, 0x32, 0x9c, 0xd1, 0x82, 0x86, 0x76, 0x27, 0xe5, 0x16, 0x62, 0x13,
	0x5d, 0xd0, 0x41, 0x63, 0x4a, 0x42, 0x0c, 0xe8, 0x23, 0x58, 0x0c, 0xf4, 0x61, 0xc7, 0xd1, 0x2d,
	0xdc, 0x21, 0x9e, 0x83, 0x5b, 0xbc, 0x57, 0xe5, 0x34, 0xc4, 0x69, 0x15, 0xc7, 0xa9, 0xf5, 0x29,
	0xe8, 0x33, 0x58, 0x0e, 0x49, 0x44, 0xe2, 0xaa, 0x10, 0x99, 0x5e, 0xfa, 0x93, 0x67, 0x59, 0xb5,
	0xe8, 0xfd, 0xed, 0x97, 0xfe, 0x65, 0x69, 0x8b, 0x03, 0xc0, 0x70, 0x94, 0x2d, 0xc3, 0x9c, 0xed,
	0x31, 0xe5, 0xac, 0x9d, 0xe4, 0xb4, 0x59, 0xdb, 0xf3, 0x15, 0xa2, 0x47, 0x90, 0xf7, 0x8c, 0x37,
	0x7a, 0x30, 0xf2, 0xb2, 0x06, 0x91, 0xdf, 0x5e, 0x8e, 0xe3, 0xbf, 0xe4, 0x64, 0x0d, 0x3c, 0xe3,
	0x4d, 0xf0, 0x5b, 0xfe, 0xbb, 0x00, 0x1b, 0xe9, 0x21, 0xe9, 0x39, 0xb6, 0xe5, 0x11, 0xf4, 0x39,
	0xcc, 0xb9, 0xc4, 0xeb, 0xb6, 0xa9, 0x27, 0x0a, 0x13, 0x06, 0x37, 0x47, 0x2a, 0x6b, 0x0c, 0x46,
	0xeb, 0xc3, 0x49, 0x8f, 0x60, 0x96, 0x6f, 0xf9, 0x41, 0x4b, 0x5c, 0xd7, 0x76, 0x59, 0x08, 0x66,
	0x35, 0xbe, 0x40, 0x22, 0xcc, 0x05, 0x79, 0x10, 0x04, 0x5b, 0x7f, 0x29, 0xff, 0x6b, 0x06, 0x4a,
	0x61, 0x15, 0x2a, 0x25, 0x1d, 0x54, 0x80, 0x8c, 0x69, 0x04, 0x41, 0x9c, 0x31, 0x8d, 0x0b, 0x9a,
	0xfb, 0x16, 0x61, 0x86, 0xc7, 0xfb, 0x34, 0xcf, 0x27, 0xb6, 0x40, 0x08, 0xa6, 0x59, 0xca, 0xcc,
	0xb0, 0x4d, 0xf6, 0x1b, 0x7d, 0x13, 0x0a, 0xb1, 0xa1, 0x70, 0x96, 0x51, 0xaf, 0xe2, 0xc8, 0x20,
	0xa8, 0x43, 0x31, 0x3e, 0xfb, 0xcd, 0x9d, 0x6b, 0xf6, 0x0b, 0x69, 0x65, 0x53, 0xcd, 0x26, 0x94,
	0x46, 0x06, 0x99, 0x2c, 0xb3, 0xa4, 0x40, 0xa3, 0xc3, 0x4b, 0x0b, 0x16, 0x46, 0x87, 0xc1, 0xdc,
	0xf9, 0x86, 0xc1, 0x22, 0x8d, 0x0d, 0x80, 0xbf, 0x10, 0xe0, 0xe6, 0x09, 0x33, 0x1f, 0x9c, 0x7f,
	0xe6, 0x5b, 0xa5, 0x63, 0xe6, 0xbc, 0x2a, 0xdc, 0x34, 0xbd, 0xa4, 0xfe, 0xa1, 0x13, 0xcb, 0x1f,
	0x9b, 0x0c, 0x56, 0x68, 0xb2, 0xda, 0xaa, 0xe9, 0x8d, 0xb6, 0x0c, 0x85, 0xb3, 0x04, 0x65, 0xcd,
	0x1f, 0x4a, 0x58, 0x79, 0x61, 0x65, 0x4d, 0x23, 0xd8, 0x40, 0x6b, 0x00, 0xa6, 0xa7, 0x1b, 0xa4,
	0x4d, 0x28, 0x31, 0x58, 0x4d, 0xc8, 0x6a, 0x39, 0xd3, 0xdb, 0xe5, 0x1b, 0xe8, 0x3b, 0x00, 0x2d,
	0x97, 0x60, 0x4a, 0x0c, 0x1d, 0x53, 0x36, 0xec, 0xf8, 0xd9, 0xcf, 0x1f, 0x9e, 0xc3, 0xf4, 0x6c,
	0xf6, 0x1f, 0x9e, 0x5a, 0x2e, 0xe0, 0xae, 0x50, 0xb9, 0x07, 0xe2, 0x33, 0xd3, 0xa3, 0x61, 0x9b,
	0xbc, 0x0b, 0x7a, 0x14, 0x45, 0x6a, 0x71, 0x26, 0x5a, 0x8b, 0xe5, 0x9f, 0xc0, 0x4a, 0x82, 0xde,
	0xa0, 0x1e, 0x3c, 0x87, 0xab, 0x61, 0x4f, 0xf6, 0xab, 0xc2, 0xed, 0x53, 0xdc, 0x9e, 0x9f, 0xa6,
	0x5a, 0x54, 0x5a, 0xfe, 0xa3, 0x00, 0x4b, 0x7b, 0x84, 0x5e, 0xc2, 0xbb, 0x6f, 0xdc, 0x11, 0xd1,
	0x6d, 0x28, 0x46, 0x47, 0xd3, 0x7e, 0xf6, 0x17, 0x22, 0x73, 0xa8, 0x21, 0xbf, 0x86, 0xe5, 0x11,
	0xf3, 0x02, 0x4f, 0x3c, 0x85, 0xf9, 0xc8, 0xb0, 0xc3, 0xed, 0x3b, 0xb5, 0x23, 0x22, 0xc2, 0xf2,
	0x3f, 0x04, 0x78, 0xef, 0x85, 0x63, 0x60, 0x4a, 0xa2, 0xba, 0xb0, 0xb1, 0x4f, 0x31, 0xed, 0x7a,
	0xef, 0x92, 0x53, 0xfc, 0xf2, 0xc7, 0x12, 0x61, 0x9a, 0x05, 0x3b, 0xfb, 0x2d, 0xdf, 0x82, 0xf7,
	0xc7, 0xdb, 0xcf, 0xbd, 0x26, 0xff, 0x59, 0x80, 0x15, 0x9e, 0x1b, 0xef, 0xec, 0x9d, 0xdf, 0x00,
	0x29, 0xc9, 0xc2, 0xe0, 0x00, 0x7f, 0x13, 0x20, 0xdb, 0x68, 0x63, 0xfa, 0xda, 0x76, 0x3b, 0x68,
	0x0f, 0xe6, 0xfd, 0x57, 0x8d, 0x13, 0xac, 0x03, 0x7b, 0xe5, 0x94, 0x18, 0x50, 0x6d, 0xaf, 0x2f,
	0xf9, 0x83, 0x2b, 0x5a, 0xde, 0x1c, 0x2e, 0xd1, 0x3e, 0x94, 0xfa, 0x8f, 0x89, 0x01, 0x58, 0x86,
	0x81, 0xdd, 0x4a, 0x01, 0x0b, 0x1e, 0x17, 0x21, 0xc0, 0x22, 0x8e, 0x6e, 0xed, 0x00, 0x64, 0x1d,
	0xdc, 0x66, 0xbf, 0xe5, 0x3f, 0x4d, 0x43, 0x3e, 0xa4, 0x3f, 0xd4, 0x2e, 0x67, 0x58, 0xbb, 0x5c,
	0x03, 0xc0, 0xad, 0x96, 0xdd, 0xb5, 0xe8, 0xb0, 0x5b, 0xe6, 0x82, 0x9d, 0x70, 0x1f, 0x9c, 0x0a,
	0xf7, 0xc1, 0x55, 0xc8, 0x1d, 0x74, 0x2d, 0xa3, 0xcd, 0xfc, 0xcd, 0x3b, 0x64, 0x96, 0x6f, 0xa8,
	0x06, 0xfa, 0x00, 0x4a, 0x2d, 0xe2, 0x06, 0x46, 0x13, 0xdd, 0xc0, 0x14, 0xb3, 0x86, 0x39, 0xaf,
	0x15, 0x43, 0xfb, 0xbb, 0x98, 0x62, 0xf4, 0x6d, 0x58, 0x0a, 0xb3, 0x3a, 0xd8, 0xf3, 0x9c, 0x23,
	0x17, 0x7b, 0x24, 0xe8, 0xa1, 0xd7, 0x43, 0xd4, 0xc6, 0x80, 0x88, 0xee, 0xc1, 0x62, 0x58, 0xec,
	0xb5, 0xd9, 0x26, 0x6c, 0x40, 0x9a, 0x63, 0x42, 0xd7, 0x42, 0xb4, 0xef, 0x07, 0x24, 0xd4, 0x88,
	0x6a, 0x62, 0xcf, 0x30, 0xe2, 0xf9, 0xa5, 0x39, 0x7b, 0x62, 0x69, 0x0e, 0x2b, 0x53, 0xb8, 0x60,
	0x85, 0xc6, 0x11, 0xbb, 0x2c, 0x09, 0x58, 0xb1, 0xcf, 0x9d, 0x09, 0x91, 0x67, 0x8f, 0x51, 0xa1,
	0x7e, 0xcb, 0x08, 0xa1, 0xa0, 0x93, 0x5b, 0x46, 0x37, 0x2c, 0x3a, 0x69, 0xb7, 0xf9, 0x7a, 0x0a,
	0x8a, 0xb1, 0x98, 0xba, 0x98, 0x20, 0xf9, 0x14, 0x56, 0xd9, 0x9c, 0xde, 0x72, 0x09, 0x7b, 0xce,
	0xe3, 0xb6, 0xa7, 0x7b, 0xc4, 0xed, 0x11, 0x57, 0xf7, 0x1f, 0x2f, 0x7c, 0x86, 0x12, 0x7d, 0x96,
	0xea, 0x90, 0x63, 0x9f, 0x31, 0x3c, 0x25, 0xc7, 0xe8, 0x31, 0x48, 0x09, 0xe2, 0x96, 0x41, 0x5c,
	0xdf, 0x06, 0x1e, 0x1f, 0xcb, 0x23, 0xd2, 0x3e, 0x5d, 0x35, 0xd0, 0x0f, 0x13, 0x74, 0x87, 0x7c,
	0x3b, 0x77, 0xa2, 0x83, 0xe2, 0x76, 0xa5, 0xdd, 0x12, 0x4c, 0x7e, 0x4b, 0xf9, 0xb3, 0xdc, 0xd2,
	0xaf, 0x33, 0x20, 0x56, 0xd9, 0x2a, 0x94, 0xcc, 0x17, 0x54, 0x3d, 0x93, 0xaf, 0xef, 0x5d, 0x4c,
	0x63, 0xf9, 0x00, 0x56, 0x12, 0xbc, 0x10, 0x34, 0x66, 0x65, 0xd2, 0xa2, 0x1c, 0x29, 0xc9, 0xf2,
	0xcf, 0xe1, 0xfa, 0x1e, 0xa1, 0x17, 0xef, 0xe6, 0x5b, 0x50, 0x0c, 0x9b, 0x37, 0xcc, 0xa4, 0xab,
	0x21, 0xed, 0xaa, 0x21, 0xeb, 0x6c, 0x32, 0xba, 0xc4, 0x03, 0xfe, 0x25, 0x03, 0xb7, 0x79, 0x3c,
	0x87, 0x58, 0xfc, 0x17, 0x70, 0x75, 0xe8, 0xf1, 0xff, 0xed, 0x99, 0x13, 0x83, 0x6d, 0xea, 0xac,
	0xc1, 0x36, 0x3d, 0x49, 0xb0, 0xcd, 0xa4, 0x07, 0xdb, 0x97, 0xb0, 0x79, 0xb2, 0x9b, 0x2e, 0xf6,
	0x6a, 0xfe, 0x2d, 0xc0, 0x0d, 0x1e, 0xe0, 0xb1, 0x92, 0x7c, 0xa9, 0xa9, 0x7e, 0x42, 0xa5, 0x9e,
	0x3e, 0x57, 0xa5, 0x9e, 0x19, 0x5b, 0xa9, 0x65, 0x17, 0xd6, 0x52, 0x0e, 0x1c, 0x78, 0xf6, 0xb3,
	0x84, 0x09, 0x49, 0x38, 0xcb, 0x84, 0x34, 0x32, 0x1f, 0xc9, 0xbf, 0x11, 0x60, 0x65, 0x8f, 0xd0,
	0xcb, 0x71, 0x71, 0x19, 0xae, 0xc5, 0xed, 0x1d, 0x86, 0xfd, 0x42, 0xcc, 0x14, 0xd5, 0x90, 0x6d,
	0x90, 0x92, 0x6c, 0xb9, 0xbc, 0xd3, 0xff, 0x3e, 0x03, 0x77, 0x78, 0x5c, 0xc7, 0x58, 0x1b, 0xd1,
	0x2b, 0xfa, 0xff, 0xf8, 0xe3, 0xa4, 0x60, 0x9c, 0x3a, 0x57, 0x30, 0x4e, 0x8f, 0x0f, 0xc6, 0x5f,
	0x0a, 0xf0, 0xe1, 0xe9, 0x5c, 0x73, 0x69, 0xd7, 0xb3, 0xfd, 0xcf, 0x3c, 0xcc, 0x47, 0xbe, 0x8e,
	0x7f, 0x25, 0x80, 0x98, 0xf6, 0x91, 0x0d, 0x7d, 0x3c, 0xd9, 0x27, 0x67, 0xe9, 0xe1, 0x84, 0x5f,
	0xf3, 0x50, 0x0f, 0x16, 0x46, 0x3e, 0x12, 0xa0, 0xad, 0x14, 0xb4, 0xb4, 0xcf, 0x18, 0xd2, 0x47,
	0xa7, 0x17, 0x08, 0xf4, 0x3a, 0x50, 0x8c, 0x3d, 0xc8, 0xd1, 0xdd, 0x14, 0x90, 0xe4, 0xef, 0x0a,
	0x52, 0xf9, 0xb4, 0xec, 0x81, 0xc6, 0xdf, 0x09, 0x70, 0x63, 0xdc, 0xd3, 0x16, 0x7d, 0x92, 0x02,
	0x78, 0x8a, 0xf7, 0xbc, 0xf4, 0x78, 0x22, 0xd9, 0xc0, 0xb2, 0x63, 0x40, 0xa3, 0x0f, 0x55, 0x94,
	0xe6, 0xd3, 0xd4, 0x57, 0xb7, 0x74, 0xef, 0x0c, 0x12, 0x81, 0xea, 0x0e, 0x14, 0xa2, 0xc3, 0x09,
	0xfa, 0x30, 0xdd, 0xad, 0xa3, 0x33, 0x94, 0x74, 0xf7, 0x94, 0xdc, 0xc3, 0x68, 0x1b, 0x99, 0xf7,
	0x52, 0xa3, 0x2d, 0x6d, 0x3e, 0x4e, 0x8d, 0xb6, 0xf4, 0x51, 0xf2, 0x6b, 0x01, 0x36, 0x4e, 0xea,
	0xfd, 0xe8, 0xc9, 0xd8, 0x3b, 0x3c, 0x71, 0xb6, 0x92, 0xbe, 0x37, 0xb1, 0x7c, 0x60, 0xe5, 0xaf,
	0x04, 0xb8, 0x9e, 0xd8, 0x3c, 0xd1, 0xfd, 0xb1, 0x27, 0x4e, 0x6e, 0x7c, 0xd2, 0x83, 0xb3, 0x09,
	0x0d, 0x83, 0x71, 0xb4, 0x7f, 0xa5, 0x06, 0x63, 0x6a, 0xdb, 0x4d, 0x0d, 0xc6, 0x31, 0xcd, 0xf1,
	0xaf, 0x42, 0xff, 0xe3, 0xd3, 0xf8, 0x72, 0x8d, 0x76, 0xc6, 0x7a, 0xfa, 0x54, 0x6d, 0x50, 0xaa,
	0x9e, 0x0b, 0x83, 0x5b, 0xbc, 0x73, 0xf3, 0x8b, 0x1b, 0xb1, 0xff, 0x7d, 0x7a, 0x1c, 0x5e, 0x1f,
	0xcc, 0xb2, 0x57, 0xe0, 0xfd, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x70, 0x51, 0x81, 0x6f, 0x22,
	0x25, 0x00, 0x00,
}
