#!/bin/sh

set -e
source ./docker/functions.bash

run_collector() {
	go run ./analytics/backend/cmd/collector/main.go 
}

run_service() {
	go run ./analytics/backend/cmd/service/main.go
}

test_collector() {
	echo "Implement Me"
	exit 1
}

test_service() {
	echo "Implement Me"
	exit 1
}

main $@
