test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
    adapter: postgresql
    encoding: unicode
    database: rover-local
    pool: 5
    username: myapp
    password: password1

production:
    adapter: postgresql
    encoding: unicode
    database: rover
    pool: 5
    username: <%=ENV['POSTGRESQL_DB_USERNAME']%>
    password: <%=ENV['POSTGRESQL_DB_PASSWORD']%>
    host: <%=ENV['POSTGRESQL_DB_HOST']%>
    port: <%=ENV['POSTGRESQL_DB_PORT']%>
