test:
    adapter: postgresql
    encoding: unicode
    database: rover-test
    pool: 15
    username: rover_test
    password: password1

development:
    adapter: postgresql
    encoding: unicode
    database: rover-local
    pool: 15
    username: rover_development
    password: password1

production:
    adapter: postgresql
    encoding: unicode
    database: rover
    pool: 15
    username: <%=ENV['POSTGRESQL_DB_USERNAME']%>
    password: <%=ENV['POSTGRESQL_DB_PASSWORD']%>
    host: <%=ENV['POSTGRESQL_DB_HOST']%>
    port: <%=ENV['POSTGRESQL_DB_PORT']%>
