development:
    name: "sandbox"
    api_key: "key-ef6a48e781d32c3abd524afb5c91838e"
    api_url: "sandboxbb6b6014e8464f18ad8a7cd4af4cdfcf.mailgun.org"

production:
    name: "production"
    api_key: <%=ENV['MAILGUN_API_KEY']%>
    api_url: <%=ENV['MAILGUN_API_URL']%>