development:
    user: guest
    password: guest
    host: aws-us-east-1-portal.10.dblayer.com:10093/rover-rabbitmq-staging
    vhost: '/'
    heartbeat: 10


production:
    user: <%=ENV['RABBITMQ_USER']%>
    password: <%=ENV['RABBITMQ_PASSWORD']%>
    host: <%=ENV['RABBITMQ_HOST']%>
    vhost: <%=ENV['RABBITMQ_VHOST']%>
    heartbeat: 10

