development:
    amqp: amqp://guest:guest@localhost
    vhost: /
    heartbeat: 10
    pool: 5
    ssl: false


production:
    amqp: <%=ENV['RABBITMQ_AMQP']%>
    heartbeat: 10
    pool: <%=ENV['WEB_CONCURRENCY']%>
    ssl: true
    public_key: <%= Rails.root.join("config", "certs", "rabbit_mq_public_key.pem").to_s %>


