development:
    amqp: amqp://guest:guest@localhost
    vhost: /
    heartbeat: 10
    pool: 5
    ssl: false


production:
    amqp: <%= ENV['CLOUDAMQP_URL'] %>
    heartbeat: 10
    pool: <%=ENV['WEB_CONCURRENCY'] || 5 %>
    ssl: true


