version: "3"

volumes:
  cachefs:
  pgdata:
  esdata:

services:


  elastic2:
    image: elasticsearch:2.4
    ports: [9200, 9300]
    volumes:
      - ../../rover:/rover

  content-api:
    image: ruby:2.3.3
    links: [postgres, mongo, audience-service, auth-service, elastic2, notification-service ]
    ports: [5000]
    command: ./docker/content-api/cmd _bundle migrate # test
    volumes:
      - ../../rover:/rover
      - cachefs:/cachefs/
    working_dir: /rover/content-api
    environment:
      AUTH_V1_SERVICE_HOST: auth-service
      AUDIENCE_V1_SERVICE_HOST: audience-service
      NOTIFICATION_SERVICE_URL: "notification-service:5100"
      MONGODB_URI: mongodb://mongo:27017/rover-local
      ELASTICSEARCH_URLS: elastic2:9200
      POSTGRESQL_DB_HOST: postgres
      BUNDLE_PATH: /cachefs/content-api.bundle
      RACK_ENV: development
      WEB_CONCURRENCY: 1
      MAX_THREADS: 1
