steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'barcodes'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/barcodes:$REVISION_ID', 'barcodes']
images: ['gcr.io/$PROJECT_ID/barcodes:$REVISION_ID']