version: "3"

services:

  rabbitmq:
    image: rabbitmq

  redis:
    image: redis

  sdkapi:
    image: node:7.5
    links: [rabbitmq, redis, postgres, audience-service, auth-service]
    working_dir: /rover/sdk-api
    ports: ["3100:3100"]
    volumes:
      - ../../rover:/rover
    command: node index.js
    environment:
      NODE_ENV: production
      NPM_TOKEN: "db2323f3-e375-4945-97d6-02eeabf09a3f"

      POSTGRESQL_DB_HOST: postgres
      POSTGRESQL_DB_NAME: rover-local

      REDIS_URL: redis://redis:6379/0
      REDIS_INBOX_URL: redis://redis:6379/1

      AUDIENCE_V1_SERVICE_HOST: audience-service
      AUTH_V1_SERVICE_HOST: auth-service

      MONGODB_URI: mongodb://mongo:27017/sdk-api-dev

      ELASTICSEARCH_URLS: http://elastic5:9200/

      CLOUDAMQP_URL: amqp://rabbitmq

      LOG_LEVEL: "debug"
      PORT: 3100
