steps:
- name: 'gcr.io/rover-production/npm:7.5.0'
  args: ['install']
  dir: 'node-phone-simulator'
  env:
    - 'NPM_TOKEN=dad33a01-0f48-47df-9797-9b36dd5f957c'
- name: 'gcr.io/rover-production/npm:7.5.0'
  args: ['run', 'build']
  dir: 'node-phone-simulator'
  env:
    - 'NPM_TOKEN=dad33a01-0f48-47df-9797-9b36dd5f957c'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/node-phone-simulator:$REVISION_ID', 'node-phone-simulator']
images: ['gcr.io/$PROJECT_ID/node-phone-simulator:$REVISION_ID']
