default: &default
    dsn: postgresql://postgres:@localhost:5432/segment_service_dev?sslmode=disable

test:
    <<: *default

development: 
    <<: *default

production:
    dsn: <%= ENV['POSTGRESQL_DSN'] %>


