/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var protobuf_wrappers_pb = require('../../protobuf/wrappers_pb.js');
var protobuf_version_pb = require('../../protobuf/version_pb.js');
var protobuf_struct_pb = require('../../protobuf/struct_pb.js');
var protobuf_timestamp_pb = require('../../protobuf/timestamp_pb.js');
var auth_v1_auth_pb = require('../../auth/v1/auth_pb.js');
var audience_v1_audience_pb = require('../../audience/v1/audience_pb.js');
goog.exportSymbol('proto.rover.event.v1.DeviceContext', null, global);
goog.exportSymbol('proto.rover.event.v1.DeviceEventInput', null, global);
goog.exportSymbol('proto.rover.event.v1.DeviceSource', null, global);
goog.exportSymbol('proto.rover.event.v1.Event', null, global);
goog.exportSymbol('proto.rover.event.v1.EventInput', null, global);
goog.exportSymbol('proto.rover.event.v1.ProfileEventInput', null, global);
goog.exportSymbol('proto.rover.event.v1.ProfileSource', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.DeviceContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.event.v1.DeviceContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.DeviceContext.displayName = 'proto.rover.event.v1.DeviceContext';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.DeviceContext.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.DeviceContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.DeviceContext} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.DeviceContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    profileIdentifier: jspb.Message.getFieldWithDefault(msg, 2, ""),
    attributes: (f = msg.getAttributes()) && protobuf_struct_pb.Struct.toObject(includeInstance, f),
    appBuild: jspb.Message.getFieldWithDefault(msg, 4, ""),
    appName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    appNamespace: jspb.Message.getFieldWithDefault(msg, 6, ""),
    appVersion: jspb.Message.getFieldWithDefault(msg, 7, ""),
    appBadgeNumber: (f = msg.getAppBadgeNumber()) && protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
    deviceManufacturer: jspb.Message.getFieldWithDefault(msg, 9, ""),
    deviceModel: jspb.Message.getFieldWithDefault(msg, 10, ""),
    isLocationServicesEnabled: (f = msg.getIsLocationServicesEnabled()) && protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    locationAuthorization: jspb.Message.getFieldWithDefault(msg, 12, 0),
    localeLanguage: jspb.Message.getFieldWithDefault(msg, 13, ""),
    localeRegion: jspb.Message.getFieldWithDefault(msg, 14, ""),
    localeScript: jspb.Message.getFieldWithDefault(msg, 15, ""),
    operatingSystemName: jspb.Message.getFieldWithDefault(msg, 16, ""),
    operatingSystemVersion: (f = msg.getOperatingSystemVersion()) && protobuf_version_pb.Version.toObject(includeInstance, f),
    notificationAuthorization: jspb.Message.getFieldWithDefault(msg, 18, 0),
    pushEnvironment: jspb.Message.getFieldWithDefault(msg, 19, 0),
    pushToken: jspb.Message.getFieldWithDefault(msg, 20, ""),
    radio: jspb.Message.getFieldWithDefault(msg, 21, ""),
    carrierName: jspb.Message.getFieldWithDefault(msg, 22, ""),
    timeZone: jspb.Message.getFieldWithDefault(msg, 23, ""),
    ip: jspb.Message.getFieldWithDefault(msg, 24, ""),
    isCellularEnabled: (f = msg.getIsCellularEnabled()) && protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    isWifiEnabled: (f = msg.getIsWifiEnabled()) && protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    screenWidth: jspb.Message.getFieldWithDefault(msg, 27, 0),
    screenHeight: jspb.Message.getFieldWithDefault(msg, 28, 0),
    frameworksMap: (f = msg.getFrameworksMap()) ? f.toObject(includeInstance, proto.rover.protobuf.Version.toObject) : [],
    label: jspb.Message.getFieldWithDefault(msg, 30, ""),
    advertisingId: jspb.Message.getFieldWithDefault(msg, 31, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.DeviceContext}
 */
proto.rover.event.v1.DeviceContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.DeviceContext;
  return proto.rover.event.v1.DeviceContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.DeviceContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.DeviceContext}
 */
proto.rover.event.v1.DeviceContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfileIdentifier(value);
      break;
    case 3:
      var value = new protobuf_struct_pb.Struct;
      reader.readMessage(value,protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setAttributes(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppBuild(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppNamespace(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppVersion(value);
      break;
    case 8:
      var value = new protobuf_wrappers_pb.Int32Value;
      reader.readMessage(value,protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
      msg.setAppBadgeNumber(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceManufacturer(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceModel(value);
      break;
    case 11:
      var value = new protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setIsLocationServicesEnabled(value);
      break;
    case 12:
      var value = /** @type {!proto.rover.audience.v1.LocationAuthorization.Value} */ (reader.readEnum());
      msg.setLocationAuthorization(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocaleLanguage(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocaleRegion(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocaleScript(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperatingSystemName(value);
      break;
    case 17:
      var value = new protobuf_version_pb.Version;
      reader.readMessage(value,protobuf_version_pb.Version.deserializeBinaryFromReader);
      msg.setOperatingSystemVersion(value);
      break;
    case 18:
      var value = /** @type {!proto.rover.audience.v1.NotificationAuthorization.Value} */ (reader.readEnum());
      msg.setNotificationAuthorization(value);
      break;
    case 19:
      var value = /** @type {!proto.rover.audience.v1.PushEnvironment.Value} */ (reader.readEnum());
      msg.setPushEnvironment(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setPushToken(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setRadio(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarrierName(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimeZone(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 25:
      var value = new protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setIsCellularEnabled(value);
      break;
    case 26:
      var value = new protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setIsWifiEnabled(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenWidth(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setScreenHeight(value);
      break;
    case 29:
      var value = msg.getFrameworksMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.rover.protobuf.Version.deserializeBinaryFromReader);
         });
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.setLabel(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdvertisingId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.DeviceContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.DeviceContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.DeviceContext} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.DeviceContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfileIdentifier();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAttributes();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getAppBuild();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAppName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAppNamespace();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getAppVersion();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getAppBadgeNumber();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getDeviceManufacturer();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDeviceModel();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getIsLocationServicesEnabled();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getLocationAuthorization();
  if (f !== 0.0) {
    writer.writeEnum(
      12,
      f
    );
  }
  f = message.getLocaleLanguage();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getLocaleRegion();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getLocaleScript();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getOperatingSystemName();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getOperatingSystemVersion();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      protobuf_version_pb.Version.serializeBinaryToWriter
    );
  }
  f = message.getNotificationAuthorization();
  if (f !== 0.0) {
    writer.writeEnum(
      18,
      f
    );
  }
  f = message.getPushEnvironment();
  if (f !== 0.0) {
    writer.writeEnum(
      19,
      f
    );
  }
  f = message.getPushToken();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getRadio();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getCarrierName();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getTimeZone();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getIp();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getIsCellularEnabled();
  if (f != null) {
    writer.writeMessage(
      25,
      f,
      protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getIsWifiEnabled();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getScreenWidth();
  if (f !== 0) {
    writer.writeInt32(
      27,
      f
    );
  }
  f = message.getScreenHeight();
  if (f !== 0) {
    writer.writeInt32(
      28,
      f
    );
  }
  f = message.getFrameworksMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(29, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.rover.protobuf.Version.serializeBinaryToWriter);
  }
  f = message.getLabel();
  if (f.length > 0) {
    writer.writeString(
      30,
      f
    );
  }
  f = message.getAdvertisingId();
  if (f.length > 0) {
    writer.writeString(
      31,
      f
    );
  }
};


/**
 * optional string profile_identifier = 2;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getProfileIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setProfileIdentifier = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional rover.protobuf.Struct attributes = 3;
 * @return {?proto.rover.protobuf.Struct}
 */
proto.rover.event.v1.DeviceContext.prototype.getAttributes = function() {
  return /** @type{?proto.rover.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, protobuf_struct_pb.Struct, 3));
};


/** @param {?proto.rover.protobuf.Struct|undefined} value */
proto.rover.event.v1.DeviceContext.prototype.setAttributes = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.rover.event.v1.DeviceContext.prototype.clearAttributes = function() {
  this.setAttributes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceContext.prototype.hasAttributes = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string app_build = 4;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getAppBuild = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setAppBuild = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string app_name = 5;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getAppName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setAppName = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string app_namespace = 6;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getAppNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setAppNamespace = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string app_version = 7;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getAppVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setAppVersion = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional rover.protobuf.Int32Value app_badge_number = 8;
 * @return {?proto.rover.protobuf.Int32Value}
 */
proto.rover.event.v1.DeviceContext.prototype.getAppBadgeNumber = function() {
  return /** @type{?proto.rover.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, protobuf_wrappers_pb.Int32Value, 8));
};


/** @param {?proto.rover.protobuf.Int32Value|undefined} value */
proto.rover.event.v1.DeviceContext.prototype.setAppBadgeNumber = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.rover.event.v1.DeviceContext.prototype.clearAppBadgeNumber = function() {
  this.setAppBadgeNumber(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceContext.prototype.hasAppBadgeNumber = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional string device_manufacturer = 9;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getDeviceManufacturer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setDeviceManufacturer = function(value) {
  jspb.Message.setField(this, 9, value);
};


/**
 * optional string device_model = 10;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getDeviceModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setDeviceModel = function(value) {
  jspb.Message.setField(this, 10, value);
};


/**
 * optional rover.protobuf.BoolValue is_location_services_enabled = 11;
 * @return {?proto.rover.protobuf.BoolValue}
 */
proto.rover.event.v1.DeviceContext.prototype.getIsLocationServicesEnabled = function() {
  return /** @type{?proto.rover.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, protobuf_wrappers_pb.BoolValue, 11));
};


/** @param {?proto.rover.protobuf.BoolValue|undefined} value */
proto.rover.event.v1.DeviceContext.prototype.setIsLocationServicesEnabled = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.rover.event.v1.DeviceContext.prototype.clearIsLocationServicesEnabled = function() {
  this.setIsLocationServicesEnabled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceContext.prototype.hasIsLocationServicesEnabled = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional rover.audience.v1.LocationAuthorization.Value location_authorization = 12;
 * @return {!proto.rover.audience.v1.LocationAuthorization.Value}
 */
proto.rover.event.v1.DeviceContext.prototype.getLocationAuthorization = function() {
  return /** @type {!proto.rover.audience.v1.LocationAuthorization.Value} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/** @param {!proto.rover.audience.v1.LocationAuthorization.Value} value */
proto.rover.event.v1.DeviceContext.prototype.setLocationAuthorization = function(value) {
  jspb.Message.setField(this, 12, value);
};


/**
 * optional string locale_language = 13;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getLocaleLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setLocaleLanguage = function(value) {
  jspb.Message.setField(this, 13, value);
};


/**
 * optional string locale_region = 14;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getLocaleRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setLocaleRegion = function(value) {
  jspb.Message.setField(this, 14, value);
};


/**
 * optional string locale_script = 15;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getLocaleScript = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setLocaleScript = function(value) {
  jspb.Message.setField(this, 15, value);
};


/**
 * optional string operating_system_name = 16;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getOperatingSystemName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setOperatingSystemName = function(value) {
  jspb.Message.setField(this, 16, value);
};


/**
 * optional rover.protobuf.Version operating_system_version = 17;
 * @return {?proto.rover.protobuf.Version}
 */
proto.rover.event.v1.DeviceContext.prototype.getOperatingSystemVersion = function() {
  return /** @type{?proto.rover.protobuf.Version} */ (
    jspb.Message.getWrapperField(this, protobuf_version_pb.Version, 17));
};


/** @param {?proto.rover.protobuf.Version|undefined} value */
proto.rover.event.v1.DeviceContext.prototype.setOperatingSystemVersion = function(value) {
  jspb.Message.setWrapperField(this, 17, value);
};


proto.rover.event.v1.DeviceContext.prototype.clearOperatingSystemVersion = function() {
  this.setOperatingSystemVersion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceContext.prototype.hasOperatingSystemVersion = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional rover.audience.v1.NotificationAuthorization.Value notification_authorization = 18;
 * @return {!proto.rover.audience.v1.NotificationAuthorization.Value}
 */
proto.rover.event.v1.DeviceContext.prototype.getNotificationAuthorization = function() {
  return /** @type {!proto.rover.audience.v1.NotificationAuthorization.Value} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/** @param {!proto.rover.audience.v1.NotificationAuthorization.Value} value */
proto.rover.event.v1.DeviceContext.prototype.setNotificationAuthorization = function(value) {
  jspb.Message.setField(this, 18, value);
};


/**
 * optional rover.audience.v1.PushEnvironment.Value push_environment = 19;
 * @return {!proto.rover.audience.v1.PushEnvironment.Value}
 */
proto.rover.event.v1.DeviceContext.prototype.getPushEnvironment = function() {
  return /** @type {!proto.rover.audience.v1.PushEnvironment.Value} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/** @param {!proto.rover.audience.v1.PushEnvironment.Value} value */
proto.rover.event.v1.DeviceContext.prototype.setPushEnvironment = function(value) {
  jspb.Message.setField(this, 19, value);
};


/**
 * optional string push_token = 20;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getPushToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setPushToken = function(value) {
  jspb.Message.setField(this, 20, value);
};


/**
 * optional string radio = 21;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getRadio = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setRadio = function(value) {
  jspb.Message.setField(this, 21, value);
};


/**
 * optional string carrier_name = 22;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getCarrierName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setCarrierName = function(value) {
  jspb.Message.setField(this, 22, value);
};


/**
 * optional string time_zone = 23;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getTimeZone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setTimeZone = function(value) {
  jspb.Message.setField(this, 23, value);
};


/**
 * optional string ip = 24;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setIp = function(value) {
  jspb.Message.setField(this, 24, value);
};


/**
 * optional rover.protobuf.BoolValue is_cellular_enabled = 25;
 * @return {?proto.rover.protobuf.BoolValue}
 */
proto.rover.event.v1.DeviceContext.prototype.getIsCellularEnabled = function() {
  return /** @type{?proto.rover.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, protobuf_wrappers_pb.BoolValue, 25));
};


/** @param {?proto.rover.protobuf.BoolValue|undefined} value */
proto.rover.event.v1.DeviceContext.prototype.setIsCellularEnabled = function(value) {
  jspb.Message.setWrapperField(this, 25, value);
};


proto.rover.event.v1.DeviceContext.prototype.clearIsCellularEnabled = function() {
  this.setIsCellularEnabled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceContext.prototype.hasIsCellularEnabled = function() {
  return jspb.Message.getField(this, 25) != null;
};


/**
 * optional rover.protobuf.BoolValue is_wifi_enabled = 26;
 * @return {?proto.rover.protobuf.BoolValue}
 */
proto.rover.event.v1.DeviceContext.prototype.getIsWifiEnabled = function() {
  return /** @type{?proto.rover.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, protobuf_wrappers_pb.BoolValue, 26));
};


/** @param {?proto.rover.protobuf.BoolValue|undefined} value */
proto.rover.event.v1.DeviceContext.prototype.setIsWifiEnabled = function(value) {
  jspb.Message.setWrapperField(this, 26, value);
};


proto.rover.event.v1.DeviceContext.prototype.clearIsWifiEnabled = function() {
  this.setIsWifiEnabled(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceContext.prototype.hasIsWifiEnabled = function() {
  return jspb.Message.getField(this, 26) != null;
};


/**
 * optional int32 screen_width = 27;
 * @return {number}
 */
proto.rover.event.v1.DeviceContext.prototype.getScreenWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/** @param {number} value */
proto.rover.event.v1.DeviceContext.prototype.setScreenWidth = function(value) {
  jspb.Message.setField(this, 27, value);
};


/**
 * optional int32 screen_height = 28;
 * @return {number}
 */
proto.rover.event.v1.DeviceContext.prototype.getScreenHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/** @param {number} value */
proto.rover.event.v1.DeviceContext.prototype.setScreenHeight = function(value) {
  jspb.Message.setField(this, 28, value);
};


/**
 * map<string, rover.protobuf.Version> frameworks = 29;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.rover.protobuf.Version>}
 */
proto.rover.event.v1.DeviceContext.prototype.getFrameworksMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.rover.protobuf.Version>} */ (
      jspb.Message.getMapField(this, 29, opt_noLazyCreate,
      proto.rover.protobuf.Version));
};


proto.rover.event.v1.DeviceContext.prototype.clearFrameworksMap = function() {
  this.getFrameworksMap().clear();
};


/**
 * optional string label = 30;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 30, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setLabel = function(value) {
  jspb.Message.setField(this, 30, value);
};


/**
 * optional string advertising_id = 31;
 * @return {string}
 */
proto.rover.event.v1.DeviceContext.prototype.getAdvertisingId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 31, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceContext.prototype.setAdvertisingId = function(value) {
  jspb.Message.setField(this, 31, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.EventInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rover.event.v1.EventInput.oneofGroups_);
};
goog.inherits(proto.rover.event.v1.EventInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.EventInput.displayName = 'proto.rover.event.v1.EventInput';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rover.event.v1.EventInput.oneofGroups_ = [[7,8]];

/**
 * @enum {number}
 */
proto.rover.event.v1.EventInput.TypeCase = {
  TYPE_NOT_SET: 0,
  DEVICE_EVENT_INPUT: 7,
  PROFILE_EVENT_INPUT: 8
};

/**
 * @return {proto.rover.event.v1.EventInput.TypeCase}
 */
proto.rover.event.v1.EventInput.prototype.getTypeCase = function() {
  return /** @type {proto.rover.event.v1.EventInput.TypeCase} */(jspb.Message.computeOneofCase(this, proto.rover.event.v1.EventInput.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.EventInput.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.EventInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.EventInput} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.EventInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    authContext: (f = msg.getAuthContext()) && auth_v1_auth_pb.AuthContext.toObject(includeInstance, f),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timestamp: (f = msg.getTimestamp()) && protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    receivedAt: (f = msg.getReceivedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    attributes: (f = msg.getAttributes()) && protobuf_struct_pb.Struct.toObject(includeInstance, f),
    deviceEventInput: (f = msg.getDeviceEventInput()) && proto.rover.event.v1.DeviceEventInput.toObject(includeInstance, f),
    profileEventInput: (f = msg.getProfileEventInput()) && proto.rover.event.v1.ProfileEventInput.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.EventInput}
 */
proto.rover.event.v1.EventInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.EventInput;
  return proto.rover.event.v1.EventInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.EventInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.EventInput}
 */
proto.rover.event.v1.EventInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new auth_v1_auth_pb.AuthContext;
      reader.readMessage(value,auth_v1_auth_pb.AuthContext.deserializeBinaryFromReader);
      msg.setAuthContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = new protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setReceivedAt(value);
      break;
    case 6:
      var value = new protobuf_struct_pb.Struct;
      reader.readMessage(value,protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setAttributes(value);
      break;
    case 7:
      var value = new proto.rover.event.v1.DeviceEventInput;
      reader.readMessage(value,proto.rover.event.v1.DeviceEventInput.deserializeBinaryFromReader);
      msg.setDeviceEventInput(value);
      break;
    case 8:
      var value = new proto.rover.event.v1.ProfileEventInput;
      reader.readMessage(value,proto.rover.event.v1.ProfileEventInput.deserializeBinaryFromReader);
      msg.setProfileEventInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.EventInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.EventInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.EventInput} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.EventInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      auth_v1_auth_pb.AuthContext.serializeBinaryToWriter
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getReceivedAt();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAttributes();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getDeviceEventInput();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.rover.event.v1.DeviceEventInput.serializeBinaryToWriter
    );
  }
  f = message.getProfileEventInput();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.rover.event.v1.ProfileEventInput.serializeBinaryToWriter
    );
  }
};


/**
 * optional rover.auth.v1.AuthContext auth_context = 1;
 * @return {?proto.rover.auth.v1.AuthContext}
 */
proto.rover.event.v1.EventInput.prototype.getAuthContext = function() {
  return /** @type{?proto.rover.auth.v1.AuthContext} */ (
    jspb.Message.getWrapperField(this, auth_v1_auth_pb.AuthContext, 1));
};


/** @param {?proto.rover.auth.v1.AuthContext|undefined} value */
proto.rover.event.v1.EventInput.prototype.setAuthContext = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.rover.event.v1.EventInput.prototype.clearAuthContext = function() {
  this.setAuthContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.EventInput.prototype.hasAuthContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.rover.event.v1.EventInput.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.rover.event.v1.EventInput.prototype.setId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.rover.event.v1.EventInput.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.rover.event.v1.EventInput.prototype.setName = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional rover.protobuf.Timestamp timestamp = 4;
 * @return {?proto.rover.protobuf.Timestamp}
 */
proto.rover.event.v1.EventInput.prototype.getTimestamp = function() {
  return /** @type{?proto.rover.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.rover.protobuf.Timestamp|undefined} value */
proto.rover.event.v1.EventInput.prototype.setTimestamp = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.rover.event.v1.EventInput.prototype.clearTimestamp = function() {
  this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.EventInput.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp received_at = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.rover.event.v1.EventInput.prototype.getReceivedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.rover.event.v1.EventInput.prototype.setReceivedAt = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.rover.event.v1.EventInput.prototype.clearReceivedAt = function() {
  this.setReceivedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.EventInput.prototype.hasReceivedAt = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional rover.protobuf.Struct attributes = 6;
 * @return {?proto.rover.protobuf.Struct}
 */
proto.rover.event.v1.EventInput.prototype.getAttributes = function() {
  return /** @type{?proto.rover.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, protobuf_struct_pb.Struct, 6));
};


/** @param {?proto.rover.protobuf.Struct|undefined} value */
proto.rover.event.v1.EventInput.prototype.setAttributes = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.rover.event.v1.EventInput.prototype.clearAttributes = function() {
  this.setAttributes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.EventInput.prototype.hasAttributes = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional DeviceEventInput device_event_input = 7;
 * @return {?proto.rover.event.v1.DeviceEventInput}
 */
proto.rover.event.v1.EventInput.prototype.getDeviceEventInput = function() {
  return /** @type{?proto.rover.event.v1.DeviceEventInput} */ (
    jspb.Message.getWrapperField(this, proto.rover.event.v1.DeviceEventInput, 7));
};


/** @param {?proto.rover.event.v1.DeviceEventInput|undefined} value */
proto.rover.event.v1.EventInput.prototype.setDeviceEventInput = function(value) {
  jspb.Message.setOneofWrapperField(this, 7, proto.rover.event.v1.EventInput.oneofGroups_[0], value);
};


proto.rover.event.v1.EventInput.prototype.clearDeviceEventInput = function() {
  this.setDeviceEventInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.EventInput.prototype.hasDeviceEventInput = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ProfileEventInput profile_event_input = 8;
 * @return {?proto.rover.event.v1.ProfileEventInput}
 */
proto.rover.event.v1.EventInput.prototype.getProfileEventInput = function() {
  return /** @type{?proto.rover.event.v1.ProfileEventInput} */ (
    jspb.Message.getWrapperField(this, proto.rover.event.v1.ProfileEventInput, 8));
};


/** @param {?proto.rover.event.v1.ProfileEventInput|undefined} value */
proto.rover.event.v1.EventInput.prototype.setProfileEventInput = function(value) {
  jspb.Message.setOneofWrapperField(this, 8, proto.rover.event.v1.EventInput.oneofGroups_[0], value);
};


proto.rover.event.v1.EventInput.prototype.clearProfileEventInput = function() {
  this.setProfileEventInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.EventInput.prototype.hasProfileEventInput = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.DeviceEventInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.event.v1.DeviceEventInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.DeviceEventInput.displayName = 'proto.rover.event.v1.DeviceEventInput';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.DeviceEventInput.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.DeviceEventInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.DeviceEventInput} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.DeviceEventInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    deviceId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    context: (f = msg.getContext()) && proto.rover.event.v1.DeviceContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.DeviceEventInput}
 */
proto.rover.event.v1.DeviceEventInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.DeviceEventInput;
  return proto.rover.event.v1.DeviceEventInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.DeviceEventInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.DeviceEventInput}
 */
proto.rover.event.v1.DeviceEventInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceId(value);
      break;
    case 2:
      var value = new proto.rover.event.v1.DeviceContext;
      reader.readMessage(value,proto.rover.event.v1.DeviceContext.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.DeviceEventInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.DeviceEventInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.DeviceEventInput} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.DeviceEventInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeviceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.rover.event.v1.DeviceContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional string device_id = 1;
 * @return {string}
 */
proto.rover.event.v1.DeviceEventInput.prototype.getDeviceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.rover.event.v1.DeviceEventInput.prototype.setDeviceId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional DeviceContext context = 2;
 * @return {?proto.rover.event.v1.DeviceContext}
 */
proto.rover.event.v1.DeviceEventInput.prototype.getContext = function() {
  return /** @type{?proto.rover.event.v1.DeviceContext} */ (
    jspb.Message.getWrapperField(this, proto.rover.event.v1.DeviceContext, 2));
};


/** @param {?proto.rover.event.v1.DeviceContext|undefined} value */
proto.rover.event.v1.DeviceEventInput.prototype.setContext = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.rover.event.v1.DeviceEventInput.prototype.clearContext = function() {
  this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceEventInput.prototype.hasContext = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.ProfileEventInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.event.v1.ProfileEventInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.ProfileEventInput.displayName = 'proto.rover.event.v1.ProfileEventInput';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.ProfileEventInput.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.ProfileEventInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.ProfileEventInput} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.ProfileEventInput.toObject = function(includeInstance, msg) {
  var f, obj = {
    profileIdentifier: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.ProfileEventInput}
 */
proto.rover.event.v1.ProfileEventInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.ProfileEventInput;
  return proto.rover.event.v1.ProfileEventInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.ProfileEventInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.ProfileEventInput}
 */
proto.rover.event.v1.ProfileEventInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfileIdentifier(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.ProfileEventInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.ProfileEventInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.ProfileEventInput} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.ProfileEventInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfileIdentifier();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string profile_identifier = 1;
 * @return {string}
 */
proto.rover.event.v1.ProfileEventInput.prototype.getProfileIdentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.rover.event.v1.ProfileEventInput.prototype.setProfileIdentifier = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.rover.event.v1.Event.oneofGroups_);
};
goog.inherits(proto.rover.event.v1.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.Event.displayName = 'proto.rover.event.v1.Event';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.rover.event.v1.Event.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.rover.event.v1.Event.SourceCase = {
  SOURCE_NOT_SET: 0,
  DEVICE_SOURCE: 3,
  PROFILE_SOURCE: 4
};

/**
 * @return {proto.rover.event.v1.Event.SourceCase}
 */
proto.rover.event.v1.Event.prototype.getSourceCase = function() {
  return /** @type {proto.rover.event.v1.Event.SourceCase} */(jspb.Message.computeOneofCase(this, proto.rover.event.v1.Event.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.Event} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
    input: (f = msg.getInput()) && proto.rover.event.v1.EventInput.toObject(includeInstance, f),
    processedAt: (f = msg.getProcessedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deviceSource: (f = msg.getDeviceSource()) && proto.rover.event.v1.DeviceSource.toObject(includeInstance, f),
    profileSource: (f = msg.getProfileSource()) && proto.rover.event.v1.ProfileSource.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.Event}
 */
proto.rover.event.v1.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.Event;
  return proto.rover.event.v1.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.Event}
 */
proto.rover.event.v1.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rover.event.v1.EventInput;
      reader.readMessage(value,proto.rover.event.v1.EventInput.deserializeBinaryFromReader);
      msg.setInput(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setProcessedAt(value);
      break;
    case 3:
      var value = new proto.rover.event.v1.DeviceSource;
      reader.readMessage(value,proto.rover.event.v1.DeviceSource.deserializeBinaryFromReader);
      msg.setDeviceSource(value);
      break;
    case 4:
      var value = new proto.rover.event.v1.ProfileSource;
      reader.readMessage(value,proto.rover.event.v1.ProfileSource.deserializeBinaryFromReader);
      msg.setProfileSource(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.Event} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInput();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.rover.event.v1.EventInput.serializeBinaryToWriter
    );
  }
  f = message.getProcessedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeviceSource();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.rover.event.v1.DeviceSource.serializeBinaryToWriter
    );
  }
  f = message.getProfileSource();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.rover.event.v1.ProfileSource.serializeBinaryToWriter
    );
  }
};


/**
 * optional EventInput input = 1;
 * @return {?proto.rover.event.v1.EventInput}
 */
proto.rover.event.v1.Event.prototype.getInput = function() {
  return /** @type{?proto.rover.event.v1.EventInput} */ (
    jspb.Message.getWrapperField(this, proto.rover.event.v1.EventInput, 1));
};


/** @param {?proto.rover.event.v1.EventInput|undefined} value */
proto.rover.event.v1.Event.prototype.setInput = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.rover.event.v1.Event.prototype.clearInput = function() {
  this.setInput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.Event.prototype.hasInput = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp processed_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.rover.event.v1.Event.prototype.getProcessedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.rover.event.v1.Event.prototype.setProcessedAt = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.rover.event.v1.Event.prototype.clearProcessedAt = function() {
  this.setProcessedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.Event.prototype.hasProcessedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DeviceSource device_source = 3;
 * @return {?proto.rover.event.v1.DeviceSource}
 */
proto.rover.event.v1.Event.prototype.getDeviceSource = function() {
  return /** @type{?proto.rover.event.v1.DeviceSource} */ (
    jspb.Message.getWrapperField(this, proto.rover.event.v1.DeviceSource, 3));
};


/** @param {?proto.rover.event.v1.DeviceSource|undefined} value */
proto.rover.event.v1.Event.prototype.setDeviceSource = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.rover.event.v1.Event.oneofGroups_[0], value);
};


proto.rover.event.v1.Event.prototype.clearDeviceSource = function() {
  this.setDeviceSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.Event.prototype.hasDeviceSource = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ProfileSource profile_source = 4;
 * @return {?proto.rover.event.v1.ProfileSource}
 */
proto.rover.event.v1.Event.prototype.getProfileSource = function() {
  return /** @type{?proto.rover.event.v1.ProfileSource} */ (
    jspb.Message.getWrapperField(this, proto.rover.event.v1.ProfileSource, 4));
};


/** @param {?proto.rover.event.v1.ProfileSource|undefined} value */
proto.rover.event.v1.Event.prototype.setProfileSource = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.rover.event.v1.Event.oneofGroups_[0], value);
};


proto.rover.event.v1.Event.prototype.clearProfileSource = function() {
  this.setProfileSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.Event.prototype.hasProfileSource = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.DeviceSource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rover.event.v1.DeviceSource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.DeviceSource.displayName = 'proto.rover.event.v1.DeviceSource';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.DeviceSource.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.DeviceSource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.DeviceSource} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.DeviceSource.toObject = function(includeInstance, msg) {
  var f, obj = {
    device: (f = msg.getDevice()) && audience_v1_audience_pb.Device.toObject(includeInstance, f),
    associatedProfile: (f = msg.getAssociatedProfile()) && audience_v1_audience_pb.Profile.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.DeviceSource}
 */
proto.rover.event.v1.DeviceSource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.DeviceSource;
  return proto.rover.event.v1.DeviceSource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.DeviceSource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.DeviceSource}
 */
proto.rover.event.v1.DeviceSource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new audience_v1_audience_pb.Device;
      reader.readMessage(value,audience_v1_audience_pb.Device.deserializeBinaryFromReader);
      msg.setDevice(value);
      break;
    case 2:
      var value = new audience_v1_audience_pb.Profile;
      reader.readMessage(value,audience_v1_audience_pb.Profile.deserializeBinaryFromReader);
      msg.setAssociatedProfile(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.DeviceSource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.DeviceSource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.DeviceSource} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.DeviceSource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevice();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      audience_v1_audience_pb.Device.serializeBinaryToWriter
    );
  }
  f = message.getAssociatedProfile();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      audience_v1_audience_pb.Profile.serializeBinaryToWriter
    );
  }
};


/**
 * optional rover.audience.v1.Device device = 1;
 * @return {?proto.rover.audience.v1.Device}
 */
proto.rover.event.v1.DeviceSource.prototype.getDevice = function() {
  return /** @type{?proto.rover.audience.v1.Device} */ (
    jspb.Message.getWrapperField(this, audience_v1_audience_pb.Device, 1));
};


/** @param {?proto.rover.audience.v1.Device|undefined} value */
proto.rover.event.v1.DeviceSource.prototype.setDevice = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.rover.event.v1.DeviceSource.prototype.clearDevice = function() {
  this.setDevice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceSource.prototype.hasDevice = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional rover.audience.v1.Profile associated_profile = 2;
 * @return {?proto.rover.audience.v1.Profile}
 */
proto.rover.event.v1.DeviceSource.prototype.getAssociatedProfile = function() {
  return /** @type{?proto.rover.audience.v1.Profile} */ (
    jspb.Message.getWrapperField(this, audience_v1_audience_pb.Profile, 2));
};


/** @param {?proto.rover.audience.v1.Profile|undefined} value */
proto.rover.event.v1.DeviceSource.prototype.setAssociatedProfile = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.rover.event.v1.DeviceSource.prototype.clearAssociatedProfile = function() {
  this.setAssociatedProfile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.DeviceSource.prototype.hasAssociatedProfile = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rover.event.v1.ProfileSource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rover.event.v1.ProfileSource.repeatedFields_, null);
};
goog.inherits(proto.rover.event.v1.ProfileSource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.rover.event.v1.ProfileSource.displayName = 'proto.rover.event.v1.ProfileSource';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rover.event.v1.ProfileSource.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rover.event.v1.ProfileSource.prototype.toObject = function(opt_includeInstance) {
  return proto.rover.event.v1.ProfileSource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rover.event.v1.ProfileSource} msg The msg instance to transform.
 * @return {!Object}
 */
proto.rover.event.v1.ProfileSource.toObject = function(includeInstance, msg) {
  var f, obj = {
    profile: (f = msg.getProfile()) && audience_v1_audience_pb.Profile.toObject(includeInstance, f),
    associatedDevicesList: jspb.Message.toObjectList(msg.getAssociatedDevicesList(),
    audience_v1_audience_pb.Device.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rover.event.v1.ProfileSource}
 */
proto.rover.event.v1.ProfileSource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rover.event.v1.ProfileSource;
  return proto.rover.event.v1.ProfileSource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rover.event.v1.ProfileSource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rover.event.v1.ProfileSource}
 */
proto.rover.event.v1.ProfileSource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new audience_v1_audience_pb.Profile;
      reader.readMessage(value,audience_v1_audience_pb.Profile.deserializeBinaryFromReader);
      msg.setProfile(value);
      break;
    case 2:
      var value = new audience_v1_audience_pb.Device;
      reader.readMessage(value,audience_v1_audience_pb.Device.deserializeBinaryFromReader);
      msg.addAssociatedDevices(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rover.event.v1.ProfileSource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rover.event.v1.ProfileSource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rover.event.v1.ProfileSource} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.rover.event.v1.ProfileSource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfile();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      audience_v1_audience_pb.Profile.serializeBinaryToWriter
    );
  }
  f = message.getAssociatedDevicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      audience_v1_audience_pb.Device.serializeBinaryToWriter
    );
  }
};


/**
 * optional rover.audience.v1.Profile profile = 1;
 * @return {?proto.rover.audience.v1.Profile}
 */
proto.rover.event.v1.ProfileSource.prototype.getProfile = function() {
  return /** @type{?proto.rover.audience.v1.Profile} */ (
    jspb.Message.getWrapperField(this, audience_v1_audience_pb.Profile, 1));
};


/** @param {?proto.rover.audience.v1.Profile|undefined} value */
proto.rover.event.v1.ProfileSource.prototype.setProfile = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.rover.event.v1.ProfileSource.prototype.clearProfile = function() {
  this.setProfile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.rover.event.v1.ProfileSource.prototype.hasProfile = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated rover.audience.v1.Device associated_devices = 2;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.rover.audience.v1.Device>}
 */
proto.rover.event.v1.ProfileSource.prototype.getAssociatedDevicesList = function() {
  return /** @type{!Array.<!proto.rover.audience.v1.Device>} */ (
    jspb.Message.getRepeatedWrapperField(this, audience_v1_audience_pb.Device, 2));
};


/** @param {!Array.<!proto.rover.audience.v1.Device>} value */
proto.rover.event.v1.ProfileSource.prototype.setAssociatedDevicesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.rover.audience.v1.Device=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rover.audience.v1.Device}
 */
proto.rover.event.v1.ProfileSource.prototype.addAssociatedDevices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.rover.audience.v1.Device, opt_index);
};


proto.rover.event.v1.ProfileSource.prototype.clearAssociatedDevicesList = function() {
  this.setAssociatedDevicesList([]);
};


goog.object.extend(exports, proto.rover.event.v1);
