#!/bin/sh

set -e

test() {
  go test -tags integration \
    github.com/roverplatform/rover/audience/service/...
}

bench() {
  go test -tags integration -bench . -run NONE -benchtime 10s \
    ./audience/service/...
}

configure_pubsub() {
  go run /go/src/github.com/roverplatform/rover/audience/service/cmd/pubsub-cli/main.go
}

run() {
    go run /go/src/github.com/roverplatform/rover/audience/service/cmd/segments-worker/main.go
}


for cmd in $*; do
  $cmd
done
