#!/bin/sh

set -e

test() {
  go test -tags integration \
    github.com/roverplatform/rover/audience/service/...
}

bench() {
  go test -tags integration -bench . -run NONE -benchtime 10s \
    ./audience/service/...
}

configure_pubsub() {
  go run /go/src/github.com/roverplatform/rover/audience/service/cmd/pubsub-cli/main.go
}

run() {
    go run /go/src/github.com/roverplatform/rover/audience/service/cmd/segments-worker/main.go -gcp-project-id=${GCP_PROJECT_ID} -pubsub-subscription=${PUBSUB_SUBSCRIPTION} -mongo-dsn=${AUDIENCE_SERVICE_MONGO_DSN} -elastic-dsn=${AUDIENCE_SERVICE_ELASTIC_DSN}
}


for cmd in $*; do
  $cmd
done
