version: "3"

services:

  kafka:
    image: spotify/kafka
    environment:
      - AUTO_CREATE_TOPICS=true
      - ADVERTISED_HOST=kafka
      - NUM_PARTITIONS=3

  postgres:
    image: postgres:9.6-alpine

  events-pipeline:
    image: roverio/golang-rdkafka:1.10-alpine
    command: ./docker/events/pipeline/cmd test
    volumes:
      - ../../:/go/src/github.com/roverplatform/rover
    working_dir: /go/src/github.com/roverplatform/rover
    depends_on:
      - kafka
      - postgres
    environment:
      CGO_ENABLED: 1
      TEST_POSTGRES_DSN: "postgres://postgres:@postgres:5432/events_pipeline_test?sslmode=disable"