version: "3"

services:
  graphql-gateway:
    links: [audience-service, auth-service]
    image: node:7.5.0
    volumes:
      - ../../rover:/rover/
    working_dir: /rover/graphql-gateway
    environment:
      AUTH_V1_SERVICE_HOST: auth-service
      AUDIENCE_V1_SERVICE_HOST: audience-service
      NODE_ENV: development
      BASE_URL: https://api-staging.rover.io/v1/
