#!/bin/sh

set -e
source ./docker/functions.bash


run() {
	go run ./auth/service/cmd/auth-service/main.go -db-dsn=${DB_DSN}
}

test() {
  waiton postgres 5432

  go test -tags integration ./auth/service/... \
    -pg-dsn=${TEST_DB_DSN} \
    -service.migrations.dir=./db/migrations/postgres \
    -service.migrations.run true
}

bench() {
  go test -tags integration -bench . -run NONE -benchtime 10s \
    ./auth/service/... \
    -service.DSN=${TEST_DB_DSN}
}

migrate() {
  waiton postgres 5432

  go run ./go/cmd/postgres-cli/main.go \
      -db-dsn=${DB_DSN} \
      -migration-path=${MIGRATION_DIR}
}

create_account() {
  go run ./auth/service/cmd/auth-cli/main.go -pg-dsn ${DB_DSN} -name ${NAME} -password ${PASSWORD} -email ${EMAIL}
}

main $@
