version: "2"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
