# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'sneakers/tasks'
Rails.application.load_tasks

task "db:init" do
  `psql -hlocalhost -Upostgres -d "postgres" -c "create role rover_test with createdb login; create role rover_development with createdb login"`
  `rake db:create`
  `psql -hlocalhost -Upostgres -d "rover-local" -f db/structure.sql`
end
